"""ADR-38 — live-VM smoke: syslog export of pfBlockerNG security events.

Proves the §2.2 contract (as revised by Amendment 1) on a real pfSense CE VM:

  1. Toggle OFF ⇒ zero event export, CSV logging unchanged.
  2. Toggle ON  ⇒ a ``pfblockerng`` key=value record per DNSBL block event in the
     dedicated /var/log/pfblockerng_syslog.log, emitted HOST-SIDE by
     ``pfb_daemon_filterlog`` — not by the chrooted python.
  3. Toggle ON + IP path ⇒ a ``pfblockerng`` record per IP Block event, exercised
     LIVE: civm reaches a blocked WAN-subnet IP through a floating, logged
     Deny_Outbound rule on WAN, and the host daemon exports the act=block event.
  4. CSV logging is unchanged in both states (export is purely additive).
  5. The toggle takes effect LIVE — no service restart between flipping it and
     the next event (the daemon re-reads config on config.xml change).
  6. Events go to the dedicated file ONLY — NOT duplicated into system.log.

ADR-38 Amendment 1: the export uses pfSense's standard package ``<logging>``
mechanism (declarative, in pfblockerng.xml) — core builds the syslog.d routing
drop-in (``!pfblockerng`` → pfblockerng_syslog.log), a newsyslog rotation entry,
and the Status→System Logs→Packages subtab, and removes the drop-in on uninstall.
Both syslog legs emit host-side (no chroot socket). Facility/severity are fixed
(LOG_LOCAL6 / LOG_INFO); the only user control is the log_syslog master toggle.

DESELECTED from the default ``python -m pytest`` (``--ignore=tests/smoke`` in
pyproject.toml). Run only by the smoke workflow::

    python -m pytest tests/smoke -m smoke --override-ini="addopts="

Needs the booted ``smoke_vm`` fixture, the branch ``.pkg`` (``SMOKE_PKG``), and
the ``stub_dns`` fixture. Without these all cases skip cleanly.
"""

from __future__ import annotations

import os
import time
from collections.abc import Iterator

import pytest

from . import helpers as h
from .conftest import PFSENSE_LAN_IP, SmokeVM, _StubDnsServer

pytestmark = pytest.mark.smoke

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

# ADR-38: the dedicated package syslog file (from the <logging> block). The
# !pfblockerng syslog.d drop-in routes ONLY program=pfblockerng records here, so
# every line in this file is one exported security event.
PFB_SYSLOG_LOG = "/var/log/pfblockerng_syslog.log"
# Generated by pfSense core from the <logging> block (routing + rotation).
SYSLOG_DROPIN = "/var/etc/syslog.d/pfblockerng_syslog.log.conf"
NEWSYSLOG_ENTRY = "/var/etc/newsyslog.conf.d/pfblockerng_syslog.log.conf"
# General System log — export events must NOT appear here (excluded by the drop-in).
SYSTEM_LOG = "/var/log/system.log"

# pfBlockerNG CSV security logs (unchanged by syslog export).
PFB_LOGDIR = "/var/log/pfblockerng"
DNSBL_LOG = f"{PFB_LOGDIR}/dnsbl.log"
IP_BLOCK_LOG = f"{PFB_LOGDIR}/ip_block.log"

# Config path for the syslog export toggle (under the General settings section).
CFG_GENERAL = "installedpackages/pfblockerng/config/0"

# The IP the pfBlockerNG floating Deny_Outbound rule blocks, exercised by civm.
# It MUST sit in the pfSense WAN subnet (192.168.89.0/24, the QEMU SLIRP net) so the
# forwarded SYN is routed straight out the directly-connected WAN — a non-WAN
# TEST-NET dst depends on the SLIRP default gateway (flaky/down in CI) and never
# traverses the WAN-out path, so the rule never matches. .9 is unused: NOT the
# SLIRP gateway (.1), the runner/stub-DNS/mock-feed host alias (.2), or DNS (.3).
TEST_IP_BLOCK_RANGE = "192.168.89.9/32"
TEST_IP_BLOCK_DST = "192.168.89.9"

# Settle budget for the tail_pfb → daemon → syslogd → file path.
FILTERLOG_SETTLE_SECS = 5.0
EVENT_WAIT_SECS = 15.0
# IP action tokens any IP security event may carry (block/permit/match).
IP_ACT_TOKENS = ("act=block", "act=pass", "act=match")


# --------------------------------------------------------------------------- #
# Module-scoped fixture: deploy once, inject DNSBL + IP, reload (syslog OFF)
# --------------------------------------------------------------------------- #


@pytest.fixture(scope="module")
def deployed_vm(
    smoke_vm: SmokeVM,
    client_vm: SmokeVM,
    stub_dns: _StubDnsServer,
) -> Iterator[SmokeVM]:
    """Deploy the branch .pkg once; wire DNSBL + IP; reload with syslog OFF.

    Given: the smoke VM is booted and the branch .pkg is available.
    When:  we deploy, wire DNSBL (TWO unique blocked domains, VIP — the syslog-toggle
           test uses one per OFF/ON probe so it never has to rely on the SAME domain
           re-triggering the python hook on a repeat query) + one IP block feed
           (RFC 5737), and do a full reload with syslog export OFF (the default).
           The reload runs sync_package_pfblockerng, which materializes the syslog
           routing drop-in (ADR-38) and (re)starts the filterlog daemon tailing
           filter.log + dnsbl.log + dns_reply.log.
    Then:  the module VM is ready for the per-test assertions.
    """
    if not os.environ.get("SMOKE_PKG"):
        pytest.skip("SMOKE_PKG not set — no built .pkg to deploy")

    h.deploy(smoke_vm)
    h.use_system_dns_upstream(smoke_vm)
    h.ensure_dnsbl_vip(smoke_vm)

    _dnsbl_domain = h.unique_domain("pfbsyslogdnsbl")
    _dnsbl_domain_on = h.unique_domain("pfbsyslogdnsbl2")
    _dnsbl_feed_path = h.write_local_feed(smoke_vm, "pfb_syslog_dnsbl.txt", f"{_dnsbl_domain}\n{_dnsbl_domain_on}\n")
    h.inject(
        smoke_vm,
        h.DnsblCase(
            aliasname="pfb_syslog_test",
            feed_url=_dnsbl_feed_path,
            mode=h.DnsblMode.VIP,
            header="pfb_syslog_dnsbl",
            hsts=False,  # explicit — test domain is not HSTS-preloaded
        ),
    )

    # IP feed: a floating, LOGGED Deny_Outbound rule for a WAN-subnet victim IP.
    # inject() wires inbound/outbound_interface=wan (SMOKE_IP_IFACE);
    # _enable_ip_floating_logged_rule then flips it to a floating `block out quick log`
    # on WAN — which catches civm's forwarded SYN leaving WAN (a non-floating WAN rule
    # is block-IN and never matches forwarded-out traffic; a LAN-interface rule breaks
    # civm connectivity) and emits a filter.log line the daemon can export.
    _ip_feed_path = h.write_local_feed(smoke_vm, "pfb_syslog_ip.txt", f"{TEST_IP_BLOCK_RANGE}\n")
    h.inject(
        smoke_vm,
        h.IpCase(
            aliasname="pfb_syslog_iptest",
            feed_url=_ip_feed_path,
            action="Deny_Outbound",
            family="v4",
            header="pfb_syslog_ip",
        ),
    )
    _enable_ip_floating_logged_rule(smoke_vm)

    # Syslog export OFF (the default) at module start.
    _set_syslog_enabled(smoke_vm, on=False)

    # Full reload: installs DNSBL + IP block, materializes the syslog routing, and
    # starts the filterlog daemon.
    h.reload(smoke_vm, "update")

    # Precondition: the civm -> pfSense LAN link is healthy (civm can resolve via
    # pfSense). All cases drive traffic from civm, so a dead LAN link must surface
    # as a clear "civm/LAN link" diagnosis here, not a bare dig timeout deep in a test.
    h.assert_link_health(client_vm, smoke_vm, control_name=h.unique_domain())

    # civm's ACTUAL LAN IP (static or dynamic lease) — the expected qip/source in
    # the export events. Captured once the link is proven healthy.
    _civm_ip = _civm_lan_ip(client_vm)

    # Precondition: DNSBL is blocking the test domain (VIP shape), as seen by the
    # civm client behind the firewall (the realistic consumer path).
    ans = h.dns_probe_client(client_vm, _dnsbl_domain, "A")
    if not h.is_vip(ans):
        pytest.skip(
            f"DNSBL VIP block not observed for {_dnsbl_domain} (got {ans}) — "
            f"DNSBL precondition failed; skipping syslog tests"
        )

    smoke_vm._pfb_dnsbl_domain = _dnsbl_domain  # type: ignore[attr-defined]
    smoke_vm._pfb_dnsbl_domain_on = _dnsbl_domain_on  # type: ignore[attr-defined]
    smoke_vm._pfb_civm_ip = _civm_ip  # type: ignore[attr-defined]
    yield smoke_vm


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _set_syslog_enabled(vm: SmokeVM, *, on: bool, timeout: float = 60.0) -> None:
    """Toggle log_syslog and write_config — NO service restart.

    ADR-38 Amendment 1: the long-running pfb_filter daemon re-reads log_syslog on
    config.xml change (pfb_filterlog_refresh_config + pfb_syslog_event read fresh),
    so a LIVE toggle takes effect on the next block event with no restart. The test
    deliberately does NOT restart anything — that is the behaviour being proven.
    """
    val = "on" if on else ""
    snippet = (
        f"$g = config_get_path({h._php_str(CFG_GENERAL)}, array());\n"
        f"$g['log_syslog'] = {h._php_str(val)};\n"
        f"config_set_path({h._php_str(CFG_GENERAL)}, $g);\n"
        "write_config('pfBlockerNG smoke: toggle log_syslog');\n"
        "echo 'OK';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"_set_syslog_enabled({on}) failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _enable_ip_floating_logged_rule(vm: SmokeVM, *, timeout: float = 60.0) -> None:
    """Make pfBlockerNG emit the IP deny rule as a FLOATING, LOGGED ``out`` rule.

    Two ipsettings flags, both required for the IP-block syslog leg:

    * ``enable_float``: inject() wires inbound/outbound_interface=wan (SMOKE_IP_IFACE).
      A *non*-floating Deny_Outbound on WAN is a block-IN rule (pfblockerng.inc:8142) —
      it never sees civm's forwarded traffic LEAVING via WAN. enable_float flips it to
      ``direction=out`` (inc:8148): a floating ``block out quick`` on WAN that DOES match
      the forwarded SYN. Floating-on-WAN also leaves the LAN allow intact — a
      per-interface LAN rule rebuild drops the "allow LAN→any" and breaks civm's DNS.
    * ``enable_log`` (global IP logging): pfBlockerNG only stamps ``log`` on the rule when
      global logging is on or the list's aliaslog='enabled' (inc:8175). Without it the
      rule blocks SILENTLY — no filter.log line — so the host filterlog daemon never sees
      the event and nothing is exported. This is the flag the IP syslog leg hinges on.
    """
    snippet = (
        f"$ip = config_get_path({h._php_str(h.CFG_IP_SETTINGS)}, array());\n"
        "$ip['enable_float'] = 'on';\n"
        "$ip['enable_log'] = 'on';\n"
        f"config_set_path({h._php_str(h.CFG_IP_SETTINGS)}, $ip);\n"
        "write_config('pfBlockerNG smoke: enable floating + logged IP rule');\n"
        "echo 'OK';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"_enable_ip_floating_logged_rule failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _civm_lan_ip(client_vm: SmokeVM, *, timeout: float = 30.0) -> str:
    """civm's ACTUAL IPv4 on the pfSense LAN subnet (192.168.1.0/24).

    Queried from civm rather than assuming the 192.168.1.10 static lease — so the
    tests work whether civm got the static lease OR a dynamic one. Used as the
    expected ``qip=`` / source in the export-event assertions.
    """
    r = client_vm.ssh(
        "/bin/sh", "-c", "ip -4 -o addr show 2>/dev/null | grep -oE '192\\.168\\.1\\.[0-9]+' | head -1", timeout=timeout
    )
    ip = r.stdout.strip()
    if not ip:
        raise RuntimeError(f"civm has no 192.168.1.x LAN IP: rc={r.returncode} out={r.stdout!r} err={r.stderr!r}")
    return ip


def _pfb_event_lines(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Exported security-event lines in the dedicated pfblockerng_syslog.log.

    The !pfblockerng drop-in routes ONLY program=pfblockerng records here, and the
    body always begins ``act=`` — so a non-empty line containing ``act=`` is one of
    our events. Returns [] if the file is absent (export never fired).
    """
    content = h.read_log_file(vm, PFB_SYSLOG_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "act=" in ln]


def _system_log_export_leaks(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Export records that LEAKED into system.log (must always be empty).

    Matches program=pfblockerng (``pfblockerng[<pid>]:``) AND an ``act=`` body.
    The operational ``[pfBlockerNG]`` logs are program=php (no ``act=`` body), so
    they are not matched — only a genuine leak of an export event would show here.
    """
    content = h.read_log_file(vm, SYSTEM_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "pfblockerng[" in ln and "act=" in ln]


def _wait_for_event(
    vm: SmokeVM,
    *,
    baseline_len: int,
    want: tuple[str, ...],
    any_of: tuple[str, ...] = (),
    timeout: float = EVENT_WAIT_SECS,
    interval: float = 1.0,
) -> str:
    """Poll the dedicated file for a NEW event line; return it, or '' on timeout."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        new = _pfb_event_lines(vm)[baseline_len:]
        for ln in new:
            if all(tok in ln for tok in want) and (not any_of or any(tok in ln for tok in any_of)):
                return ln
        time.sleep(interval)
    return ""


def syslog_export_state_snapshot(vm: SmokeVM) -> str:
    """On-box syslog-export state for failure diagnostics. Never raises."""
    try:
        log_syslog = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    except Exception:
        log_syslog = "(error)"
    try:
        ls = vm.ssh("/bin/ls", "-l", SYSLOG_DROPIN, PFB_SYSLOG_LOG, timeout=10.0)
        routing = ls.stdout.strip() or "(absent)"
    except Exception:
        routing = "(error)"
    daemon = "(error)"
    try:
        ps = vm.ssh(
            "/bin/sh",
            "-c",
            "/bin/ps -waxo pid,start,command | /usr/bin/grep '[p]fblockerng.inc filterlog'",
            timeout=10.0,
        )
        daemon = ps.stdout.strip() or "(not running)"
    except Exception:
        pass
    try:
        events = _pfb_event_lines(vm)
    except Exception:
        events = []
    # Dump the ACTUAL recent event lines, not just a count — so a failure shows what
    # WAS emitted vs what the assertion expected (read the logs, don't chase ghosts).
    recent = "\n    ".join(events[-8:]) if events else "(none)"
    return (
        f"log_syslog={log_syslog!r} event_lines={len(events)}\n"
        f"  routing: {routing}\n  filterlog: {daemon}\n"
        f"  recent {PFB_SYSLOG_LOG} lines (last {min(len(events), 8)}):\n    {recent}"
    )


def _trigger_ip_block(client: SmokeVM, *, timeout: float = 30.0) -> None:
    """Generate a pf-logged IP block by curling the blocked WAN IP FROM civm.

    The block must be triggered by PASS-THROUGH traffic — a client BEHIND the
    firewall (civm) reaching the blocked WAN IP — not by pfSense's own stack: the
    floating Deny_Outbound rule acts on forwarded traffic leaving WAN, so a curl
    from pfSense itself would not hit it.

    civm has TWO equal-metric default routes (mgmt ens4 via the QEMU mgmt SLIRP,
    and LAN ens5 via pfSense), so a bare curl may egress the mgmt NIC and never
    reach pfSense. Pin a host route for the victim via pfSense (192.168.1.1) out
    the LAN device first, forcing the SYN civm -> pfSense -> WAN-out -> the block.
    """
    client.ssh(
        "/bin/sh",
        "-c",
        "dev=$(ip -4 -o addr show | awk '/192\\.168\\.1\\./{print $2; exit}'); "
        f'ip route replace {TEST_IP_BLOCK_DST}/32 via {PFSENSE_LAN_IP} dev "$dev" 2>/dev/null || true; '
        f"curl --connect-timeout 2 --max-time 4 http://{TEST_IP_BLOCK_DST}/ >/dev/null 2>&1 || true",
        timeout=timeout,
    )


# --------------------------------------------------------------------------- #
# Test 0: the <logging> mechanism is materialized (routing + rotation)
# --------------------------------------------------------------------------- #


def test_syslog_routing_and_rotation_registered(deployed_vm: SmokeVM) -> None:
    """ADR-38: the declarative <logging> block yields the routing drop-in + newsyslog entry.

    Given: pfBlockerNG deployed and reloaded (the fixture).
    Then:  pfSense core has generated BOTH the syslog.d routing drop-in (so events
           reach the dedicated file) AND the newsyslog.conf.d rotation entry (so the
           file is size-capped/rotated for us — no bespoke rotation needed).
    """
    vm = deployed_vm

    dropin = vm.ssh("/bin/cat", SYSLOG_DROPIN, timeout=15.0)
    assert dropin.returncode == 0, (
        f"syslog routing drop-in {SYSLOG_DROPIN} is absent — the <logging> block did not "
        f"materialize (sync should run system_syslogd_start).\n{syslog_export_state_snapshot(vm)}"
    )
    assert "pfblockerng" in dropin.stdout and "pfblockerng_syslog.log" in dropin.stdout, (
        f"drop-in does not route program=pfblockerng to the dedicated file: {dropin.stdout!r}"
    )

    newsyslog = vm.ssh("/bin/cat", NEWSYSLOG_ENTRY, timeout=15.0)
    assert newsyslog.returncode == 0 and "pfblockerng_syslog.log" in newsyslog.stdout, (
        f"newsyslog rotation entry {NEWSYSLOG_ENTRY} is absent — the dedicated file would grow "
        f"unbounded.\n  got: {newsyslog.stdout!r} (rc={newsyslog.returncode})"
    )


# --------------------------------------------------------------------------- #
# Test 1: ON ⇒ DNSBL event exported to the dedicated file (LIVE toggle)
# --------------------------------------------------------------------------- #


def test_syslog_on_dnsbl_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """OFF ⇒ no export record; ON ⇒ a pfblockerng record per DNSBL block, host-side, no restart.

    Given: DNSBL blocking TWO distinct domains (VIP); syslog export OFF (fixture default),
           so NO event line exists in pfblockerng_syslog.log yet.
    When:  domain_off is probed WHILE export is STILL OFF (no restart) — the DNSBL block
           itself still fires (proven via the CSV dnsbl.log marker), but must export
           nothing. THEN log_syslog is enabled (write_config ONLY — no restart) and the
           civm client (192.168.1.10) resolves a SECOND, never-before-queried domain
           (domain_on — dodges any residual Unbound/module state from the OFF-phase probe,
           so the python hook is guaranteed to run fresh) via pfSense.
    Then:  the OFF-phase probe produces NO new record in pfblockerng_syslog.log. The
           ON-phase probe DOES produce a NEW record with act=dnsbl + the queried name —
           proving the toggle took effect LIVE, and that OFF truly exported nothing (not
           just "no probe happened yet").
    And:   the event did NOT leak into system.log; the CSV dnsbl.log was written for BOTH probes.
    """
    vm = deployed_vm
    domain_off: str = vm._pfb_dnsbl_domain  # type: ignore[attr-defined]
    domain_on: str = vm._pfb_dnsbl_domain_on  # type: ignore[attr-defined]
    civm_ip: str = vm._pfb_civm_ip  # type: ignore[attr-defined]

    # Given: syslog export OFF (fixture default) — no event lines recorded yet.
    before = _pfb_event_lines(vm)
    sys_leak_before = len(_system_log_export_leaks(vm))

    # Before: probe a blocked domain WHILE export is still OFF. The block itself must still
    # fire (CSV assertion below) but must produce NO export line — the missing half of the
    # toggle's before/after proof (CLAUDE.md: assert the before-state, not just the after).
    dnsbl_off_before = h.count_log_marker(vm, DNSBL_LOG, domain_off)
    ans_off = h.dns_probe_client(client_vm, domain_off, "A")
    assert h.is_vip(ans_off), f"DNSBL block shape unexpected before enabling syslog: expected VIP, got {ans_off}"
    time.sleep(FILTERLOG_SETTLE_SECS)

    dnsbl_off_after = h.count_log_marker(vm, DNSBL_LOG, domain_off)
    assert dnsbl_off_after > dnsbl_off_before, (
        f"CSV dnsbl.log was NOT written for the OFF-phase probe (before {dnsbl_off_before}, after "
        f"{dnsbl_off_after}) — the block itself must fire regardless of the syslog toggle"
    )
    after_off = _pfb_event_lines(vm)
    assert len(after_off) == len(before), (
        f"A pfblockerng export record appeared for {domain_off} while syslog export is OFF "
        f"(before {len(before)} lines, after {len(after_off)}) — the OFF gate is not working.\n"
        f"{syslog_export_state_snapshot(vm)}"
    )

    # When: enable LIVE (no restart) + probe a DIFFERENT, never-before-queried domain from
    # the civm client (dodges any residual state from the OFF-phase probe above).
    dnsbl_on_before = h.count_log_marker(vm, DNSBL_LOG, domain_on)
    _set_syslog_enabled(vm, on=True)
    ans = h.dns_probe_client(client_vm, domain_on, "A")

    # Then: DNSBL still blocks (additive).
    assert h.is_vip(ans), f"DNSBL block shape changed after enabling syslog: expected VIP, got {ans}"

    # Then: a NEW dedicated-file record (poll — tail/daemon latency). Match on
    # act=dnsbl + the queried name (qname=). NOTE: b_type is the MATCH type
    # ('DNSBL'/'TLD'/'Python'), NOT the sinkhole mode — there is no 'VIP' b_type.
    line = _wait_for_event(vm, baseline_len=len(after_off), want=("act=dnsbl", f"qname={domain_on}", f"qip={civm_ip}"))
    assert line, (
        f"No new DNSBL export record after enabling export (LIVE, no restart) and probing {domain_on}.\n"
        f"  expected a new line in {PFB_SYSLOG_LOG} with: act=dnsbl qname={domain_on} qip={civm_ip}\n"
        f"  {syslog_export_state_snapshot(vm)}"
    )

    # And: it did NOT leak into system.log.
    assert len(_system_log_export_leaks(vm)) == sys_leak_before, (
        f"export event leaked into {SYSTEM_LOG} — the !pfblockerng drop-in should route it to the "
        f"dedicated file ONLY.\n  leaks: {_system_log_export_leaks(vm)[-5:]!r}"
    )

    # And: CSV dnsbl.log also written for the ON-phase probe (additive).
    dnsbl_on_after = h.count_log_marker(vm, DNSBL_LOG, domain_on)
    assert dnsbl_on_after > dnsbl_on_before, (
        f"CSV dnsbl.log was NOT written after enabling syslog (before {dnsbl_on_before}, after "
        f"{dnsbl_on_after}) — export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 2: ON ⇒ IP Block event exported to the dedicated file (LIVE).
#
# The IP-block leg is exercised live via a FLOATING, LOGGED Deny_Outbound rule on
# WAN (_enable_ip_floating_logged_rule) blocking a WAN-subnet victim (TEST_IP_BLOCK_DST):
#   * a LAN-interface pfB rule was found to break ALL civm->pfSense traffic (the
#     LAN filter rebuild drops the permissive allow; civm DNS/ICMP then hit the
#     default block, rule 1000000103 — filterlog-confirmed);
#   * a NON-floating WAN Deny_Outbound is a block-IN rule (inc:8142), so it never
#     matches civm's forwarded traffic LEAVING via WAN;
#   * a non-WAN TEST-NET dst depends on the (flaky) SLIRP default gateway and
#     never traverses the WAN-out path;
#   * without global IP logging the rule blocks SILENTLY (no `log`, inc:8175), so
#     filter.log/the daemon never see it — enable_log is what makes it exportable.
# The floating `block out quick log` on WAN matches the forwarded SYN AND leaves the
# LAN allow intact (it matches only dst=<alias>); the WAN-subnet victim is
# directly connected so it routes out WAN with no default-gateway dependency.
# --------------------------------------------------------------------------- #


def test_syslog_on_ip_block_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """ON ⇒ a pfblockerng record per IP Block event in the dedicated file.

    Given: a floating Deny_Outbound rule covering TEST_IP_BLOCK_RANGE; syslog export
           ON (from the DNSBL test); the filterlog daemon running; the civm client
           behind the firewall.
    When:  the civm client curls the blocked WAN IP (pass-through traffic pf blocks
           + logs on WAN-out — NOT pfSense's own traffic, which the rule misses).
    Then:  a new pfblockerng record appears in the dedicated file with an IP action
           token (act=block/pass/match).
    And:   the CSV ip_block.log is also written (additive).
    """
    vm = deployed_vm

    val = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    assert val == "on", f"Precondition: expected log_syslog='on' from prior test, got {val!r}"

    before = _pfb_event_lines(vm)
    ip_block_before = h.read_log_file(vm, IP_BLOCK_LOG)

    _trigger_ip_block(client_vm)

    line = _wait_for_event(vm, baseline_len=len(before), want=(), any_of=IP_ACT_TOKENS)
    if not line:
        ps = vm.ssh("/bin/ps", "-wax", timeout=30)
        daemon_running = "pfblockerng.inc filterlog" in ps.stdout
        pfctl = vm.ssh("/sbin/pfctl", "-t", "pfB_pfb_syslog_iptest_v4", "-T", "show", timeout=30)
        alias_populated = TEST_IP_BLOCK_DST in pfctl.stdout
        # An unpopulated alias or a dead filterlog daemon are NOT benign preconditions to skip
        # past -- this un-xfailed leg (ADR-38 A2.4) exists specifically to catch those two
        # regression classes (a failed IP feed reload / a crashed export daemon), so both fold
        # into the same hard failure instead of turning a target regression into a green skip.
        if not alias_populated:
            precondition = (
                f"IP block alias pfB_pfb_syslog_iptest_v4 not populated with {TEST_IP_BLOCK_RANGE} "
                "— IP feed reload likely failed"
            )
        elif not daemon_running:
            precondition = "filterlog daemon not running — the pfBlockerNG export daemon died"
        else:
            precondition = "none — daemon running and alias populated"
        raise AssertionError(
            f"No new IP-block export record after connection to {TEST_IP_BLOCK_DST}.\n"
            f"  expected a new line in {PFB_SYSLOG_LOG} with one of {list(IP_ACT_TOKENS)!r}\n"
            f"  actual:   no matching line found\n"
            f"  daemon_running={daemon_running} alias_populated={alias_populated}\n"
            f"  precondition broken: {precondition}\n"
            f"  ps: {ps.stdout[:400]!r}\n"
            f"  pfctl: {pfctl.stdout!r}\n"
            f"  {syslog_export_state_snapshot(vm)}"
        )

    ip_block_after = h.read_log_file(vm, IP_BLOCK_LOG)
    assert len(ip_block_after) > len(ip_block_before), (
        "CSV ip_block.log was NOT written after enabling syslog — export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 3: OFF ⇒ no new export records (LIVE toggle, before/after proof)
# --------------------------------------------------------------------------- #


def test_syslog_off_no_new_records(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """OFF ⇒ zero export; CSV logging unchanged — LIVE toggle, no restart.

    Before/after proof: first assert ON produced records (true from prior tests),
    then disable LIVE and assert the count does NOT increase. Exercised via the
    DNSBL leg (a re-probe of the blocked domain from civm).

    Given: syslog export ON (from prior tests), records already in the dedicated file.
    When:  log_syslog set OFF (write_config ONLY — no restart); the blocked domain is
           probed again from civm.
    Then:  the export-record count does NOT increase — the daemon honored the LIVE off.
    And:   the CSV dnsbl.log is STILL written (additive path, independent of the toggle).
    """
    vm = deployed_vm
    domain: str = vm._pfb_dnsbl_domain  # type: ignore[attr-defined]

    count_while_on = len(_pfb_event_lines(vm))
    assert count_while_on > 0, (
        f"Precondition: expected export records from prior ON tests, but {PFB_SYSLOG_LOG} has "
        f"{count_while_on}.\n{syslog_export_state_snapshot(vm)}"
    )

    dnsbl_csv_before = h.count_log_marker(vm, DNSBL_LOG, domain)

    # When: disable LIVE (no restart) + re-probe the blocked domain from civm.
    _set_syslog_enabled(vm, on=False)
    ans = h.dns_probe_client(client_vm, domain, "A")
    assert h.is_vip(ans), f"DNSBL block should still work when syslog is OFF, got {ans}"
    time.sleep(FILTERLOG_SETTLE_SECS)

    # Then: no new export records (the LIVE off took effect).
    count_while_off = len(_pfb_event_lines(vm))
    assert count_while_off == count_while_on, (
        f"New export records appeared after disabling export LIVE (before {count_while_on}, after "
        f"{count_while_off}) — the live OFF gate is not working.\n{syslog_export_state_snapshot(vm)}"
    )

    # And: CSV still written in the OFF state (additive path independent of the toggle).
    dnsbl_csv_after = h.count_log_marker(vm, DNSBL_LOG, domain)
    assert dnsbl_csv_after > dnsbl_csv_before, (
        f"CSV dnsbl.log was NOT written while syslog export is OFF (before {dnsbl_csv_before}, "
        f"after {dnsbl_csv_after}) — the CSV path must be independent of the syslog toggle"
    )
