"""ADR-38 — live-VM smoke: syslog export of pfBlockerNG security events.

Proves the §2.2 contract (as revised by Amendment 1) on a real pfSense CE VM:

  1. Toggle OFF ⇒ zero event export, CSV logging unchanged.
  2. Toggle ON  ⇒ a ``pfblockerng`` key=value record per DNSBL block event in the
     dedicated /var/log/pfblockerng_syslog.log, emitted HOST-SIDE by
     ``pfb_daemon_filterlog`` — not by the chrooted python.
  3. Toggle ON + IP path ⇒ a ``pfblockerng`` record per IP Block event. DEFERRED
     (xfail) — the IP-block LIVE trigger needs harness work (a reachable non-infra
     victim target + a WAN/floating rule; a LAN rule breaks civm connectivity).
     The IP syslog mechanism is the same host-side path the DNSBL leg proves, and
     ``pfb_syslog_format_ip`` is unit-tested. Tracked as a follow-up.
  4. CSV logging is unchanged in both states (export is purely additive).
  5. The toggle takes effect LIVE — no service restart between flipping it and
     the next event (the daemon re-reads config on config.xml change).
  6. Events go to the dedicated file ONLY — NOT duplicated into system.log.

ADR-38 Amendment 1: the export uses pfSense's standard package ``<logging>``
mechanism (declarative, in pfblockerng.xml) — core builds the syslog.d routing
drop-in (``!pfblockerng`` → pfblockerng_syslog.log), a newsyslog rotation entry,
and the Status→System Logs→Packages subtab, and removes the drop-in on uninstall.
Both syslog legs emit host-side (no chroot socket). Facility/severity are fixed
(LOG_LOCAL6 / LOG_INFO); the only user control is the log_syslog master toggle.

DESELECTED from the default ``python -m pytest`` (``--ignore=tests/smoke`` in
pyproject.toml). Run only by the smoke workflow::

    python -m pytest tests/smoke -m smoke --override-ini="addopts="

Needs the booted ``smoke_vm`` fixture, the branch ``.pkg`` (``SMOKE_PKG``), and
the ``stub_dns`` fixture. Without these all cases skip cleanly.
"""

from __future__ import annotations

import os
import time
from collections.abc import Iterator

import pytest

from . import helpers as h
from .conftest import SmokeVM, _StubDnsServer

pytestmark = pytest.mark.smoke

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

# ADR-38: the dedicated package syslog file (from the <logging> block). The
# !pfblockerng syslog.d drop-in routes ONLY program=pfblockerng records here, so
# every line in this file is one exported security event.
PFB_SYSLOG_LOG = "/var/log/pfblockerng_syslog.log"
# Generated by pfSense core from the <logging> block (routing + rotation).
SYSLOG_DROPIN = "/var/etc/syslog.d/pfblockerng_syslog.log.conf"
NEWSYSLOG_ENTRY = "/var/etc/newsyslog.conf.d/pfblockerng_syslog.log.conf"
# General System log — export events must NOT appear here (excluded by the drop-in).
SYSTEM_LOG = "/var/log/system.log"

# pfBlockerNG CSV security logs (unchanged by syslog export).
PFB_LOGDIR = "/var/log/pfblockerng"
DNSBL_LOG = f"{PFB_LOGDIR}/dnsbl.log"
IP_BLOCK_LOG = f"{PFB_LOGDIR}/ip_block.log"

# Config path for the syslog export toggle (under the General settings section).
CFG_GENERAL = "installedpackages/pfblockerng/config/0"

# A test IP range whose pfBlockerNG block rule we trigger traffic against.
# RFC 5737 TEST-NET-3 (203.0.113.0/24) — not routable, but pf still blocks
# an outbound connection attempt if it matches an alias table for that range.
TEST_IP_BLOCK_RANGE = "203.0.113.0/24"
TEST_IP_BLOCK_DST = "203.0.113.1"

# Settle budget for the tail_pfb → daemon → syslogd → file path.
FILTERLOG_SETTLE_SECS = 5.0
EVENT_WAIT_SECS = 15.0
# IP action tokens any IP security event may carry (block/permit/match).
IP_ACT_TOKENS = ("act=block", "act=pass", "act=match")


# --------------------------------------------------------------------------- #
# Module-scoped fixture: deploy once, inject DNSBL + IP, reload (syslog OFF)
# --------------------------------------------------------------------------- #


@pytest.fixture(scope="module")
def deployed_vm(
    smoke_vm: SmokeVM,
    client_vm: SmokeVM,
    stub_dns: _StubDnsServer,
) -> Iterator[SmokeVM]:
    """Deploy the branch .pkg once; wire DNSBL + IP; reload with syslog OFF.

    Given: the smoke VM is booted and the branch .pkg is available.
    When:  we deploy, wire DNSBL (unique blocked domain, VIP) + one IP block feed
           (RFC 5737), and do a full reload with syslog export OFF (the default).
           The reload runs sync_package_pfblockerng, which materializes the syslog
           routing drop-in (ADR-38) and (re)starts the filterlog daemon tailing
           filter.log + dnsbl.log + dns_reply.log.
    Then:  the module VM is ready for the per-test assertions.
    """
    if not os.environ.get("SMOKE_PKG"):
        pytest.skip("SMOKE_PKG not set — no built .pkg to deploy")

    h.deploy(smoke_vm)
    h.use_system_dns_upstream(smoke_vm)
    h.ensure_dnsbl_vip(smoke_vm)

    _dnsbl_domain = h.unique_domain("pfbsyslogdnsbl")
    _dnsbl_feed_path = h.write_local_feed(smoke_vm, "pfb_syslog_dnsbl.txt", f"{_dnsbl_domain}\n")
    h.inject(
        smoke_vm,
        h.DnsblCase(
            aliasname="pfb_syslog_test",
            feed_url=_dnsbl_feed_path,
            mode=h.DnsblMode.VIP,
            header="pfb_syslog_dnsbl",
            hsts=False,  # explicit — test domain is not HSTS-preloaded
        ),
    )

    # IP feed (alias only; default WAN rule). NOTE: the IP-block LIVE leg is deferred
    # (see test_syslog_on_ip_block_event_exported xfail + follow-up). A LAN-interface
    # rule was found to break ALL civm->pfSense traffic (the LAN filter rebuild drops
    # the permissive allow), and a WAN rule to an unreachable TEST-NET IP never logs;
    # a clean live test needs a reachable non-infra target + a WAN/floating rule.
    _ip_feed_path = h.write_local_feed(smoke_vm, "pfb_syslog_ip.txt", f"{TEST_IP_BLOCK_RANGE}\n")
    h.inject(
        smoke_vm,
        h.IpCase(
            aliasname="pfb_syslog_iptest",
            feed_url=_ip_feed_path,
            action="Deny_Outbound",
            family="v4",
            header="pfb_syslog_ip",
        ),
    )

    # Syslog export OFF (the default) at module start.
    _set_syslog_enabled(smoke_vm, on=False)

    # Full reload: installs DNSBL + IP block, materializes the syslog routing, and
    # starts the filterlog daemon.
    h.reload(smoke_vm, "update")

    # Precondition: the civm -> pfSense LAN link is healthy (civm can resolve via
    # pfSense). All cases drive traffic from civm, so a dead LAN link must surface
    # as a clear "civm/LAN link" diagnosis here, not a bare dig timeout deep in a test.
    h.assert_link_health(client_vm, smoke_vm, control_name=h.unique_domain())

    # civm's ACTUAL LAN IP (static or dynamic lease) — the expected qip/source in
    # the export events. Captured once the link is proven healthy.
    _civm_ip = _civm_lan_ip(client_vm)

    # Precondition: DNSBL is blocking the test domain (VIP shape), as seen by the
    # civm client behind the firewall (the realistic consumer path).
    ans = h.dns_probe_client(client_vm, _dnsbl_domain, "A")
    if not h.is_vip(ans):
        pytest.skip(
            f"DNSBL VIP block not observed for {_dnsbl_domain} (got {ans}) — "
            f"DNSBL precondition failed; skipping syslog tests"
        )

    smoke_vm._pfb_dnsbl_domain = _dnsbl_domain  # type: ignore[attr-defined]
    smoke_vm._pfb_civm_ip = _civm_ip  # type: ignore[attr-defined]
    yield smoke_vm


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _set_syslog_enabled(vm: SmokeVM, *, on: bool, timeout: float = 60.0) -> None:
    """Toggle log_syslog and write_config — NO service restart.

    ADR-38 Amendment 1: the long-running pfb_filter daemon re-reads log_syslog on
    config.xml change (pfb_filterlog_refresh_config + pfb_syslog_event read fresh),
    so a LIVE toggle takes effect on the next block event with no restart. The test
    deliberately does NOT restart anything — that is the behaviour being proven.
    """
    val = "on" if on else ""
    snippet = (
        f"$g = config_get_path({h._php_str(CFG_GENERAL)}, array());\n"
        f"$g['log_syslog'] = {h._php_str(val)};\n"
        f"config_set_path({h._php_str(CFG_GENERAL)}, $g);\n"
        "write_config('pfBlockerNG smoke: toggle log_syslog');\n"
        "echo 'OK';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"_set_syslog_enabled({on}) failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _civm_lan_ip(client_vm: SmokeVM, *, timeout: float = 30.0) -> str:
    """civm's ACTUAL IPv4 on the pfSense LAN subnet (192.168.1.0/24).

    Queried from civm rather than assuming the 192.168.1.10 static lease — so the
    tests work whether civm got the static lease OR a dynamic one. Used as the
    expected ``qip=`` / source in the export-event assertions.
    """
    r = client_vm.ssh(
        "/bin/sh", "-c", "ip -4 -o addr show 2>/dev/null | grep -oE '192\\.168\\.1\\.[0-9]+' | head -1", timeout=timeout
    )
    ip = r.stdout.strip()
    if not ip:
        raise RuntimeError(f"civm has no 192.168.1.x LAN IP: rc={r.returncode} out={r.stdout!r} err={r.stderr!r}")
    return ip


def _pfb_event_lines(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Exported security-event lines in the dedicated pfblockerng_syslog.log.

    The !pfblockerng drop-in routes ONLY program=pfblockerng records here, and the
    body always begins ``act=`` — so a non-empty line containing ``act=`` is one of
    our events. Returns [] if the file is absent (export never fired).
    """
    content = h.read_log_file(vm, PFB_SYSLOG_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "act=" in ln]


def _system_log_export_leaks(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Export records that LEAKED into system.log (must always be empty).

    Matches program=pfblockerng (``pfblockerng[<pid>]:``) AND an ``act=`` body.
    The operational ``[pfBlockerNG]`` logs are program=php (no ``act=`` body), so
    they are not matched — only a genuine leak of an export event would show here.
    """
    content = h.read_log_file(vm, SYSTEM_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "pfblockerng[" in ln and "act=" in ln]


def _wait_for_event(
    vm: SmokeVM,
    *,
    baseline_len: int,
    want: tuple[str, ...],
    any_of: tuple[str, ...] = (),
    timeout: float = EVENT_WAIT_SECS,
    interval: float = 1.0,
) -> str:
    """Poll the dedicated file for a NEW event line; return it, or '' on timeout."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        new = _pfb_event_lines(vm)[baseline_len:]
        for ln in new:
            if all(tok in ln for tok in want) and (not any_of or any(tok in ln for tok in any_of)):
                return ln
        time.sleep(interval)
    return ""


def syslog_export_state_snapshot(vm: SmokeVM) -> str:
    """On-box syslog-export state for failure diagnostics. Never raises."""
    try:
        log_syslog = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    except Exception:
        log_syslog = "(error)"
    try:
        ls = vm.ssh("/bin/ls", "-l", SYSLOG_DROPIN, PFB_SYSLOG_LOG, timeout=10.0)
        routing = ls.stdout.strip() or "(absent)"
    except Exception:
        routing = "(error)"
    daemon = "(error)"
    try:
        ps = vm.ssh(
            "/bin/sh",
            "-c",
            "/bin/ps -waxo pid,start,command | /usr/bin/grep '[p]fblockerng.inc filterlog'",
            timeout=10.0,
        )
        daemon = ps.stdout.strip() or "(not running)"
    except Exception:
        pass
    try:
        events = _pfb_event_lines(vm)
    except Exception:
        events = []
    # Dump the ACTUAL recent event lines, not just a count — so a failure shows what
    # WAS emitted vs what the assertion expected (read the logs, don't chase ghosts).
    recent = "\n    ".join(events[-8:]) if events else "(none)"
    return (
        f"log_syslog={log_syslog!r} event_lines={len(events)}\n"
        f"  routing: {routing}\n  filterlog: {daemon}\n"
        f"  recent {PFB_SYSLOG_LOG} lines (last {min(len(events), 8)}):\n    {recent}"
    )


def _trigger_ip_block(client: SmokeVM, *, timeout: float = 30.0) -> None:
    """Generate a pf-logged IP block by curling a blocked IP FROM the civm client.

    The block must be triggered by PASS-THROUGH traffic — a client BEHIND the
    firewall (civm, 192.168.1.10) reaching a blocked WAN IP — not by the pfSense
    box itself: pfBlockerNG's deny rule acts on forwarded traffic, so a curl from
    pfSense's own stack would not hit it. civm's outbound to 203.0.113.1 is routed
    out WAN and dropped+logged by the pfB rule (curl uses busybox/debian on civm).
    """
    client.ssh(
        "/bin/sh",
        "-c",
        f"curl --connect-timeout 2 --max-time 4 http://{TEST_IP_BLOCK_DST}/ >/dev/null 2>&1 || true",
        timeout=timeout,
    )


# --------------------------------------------------------------------------- #
# Test 0: the <logging> mechanism is materialized (routing + rotation)
# --------------------------------------------------------------------------- #


def test_syslog_routing_and_rotation_registered(deployed_vm: SmokeVM) -> None:
    """ADR-38: the declarative <logging> block yields the routing drop-in + newsyslog entry.

    Given: pfBlockerNG deployed and reloaded (the fixture).
    Then:  pfSense core has generated BOTH the syslog.d routing drop-in (so events
           reach the dedicated file) AND the newsyslog.conf.d rotation entry (so the
           file is size-capped/rotated for us — no bespoke rotation needed).
    """
    vm = deployed_vm

    dropin = vm.ssh("/bin/cat", SYSLOG_DROPIN, timeout=15.0)
    assert dropin.returncode == 0, (
        f"syslog routing drop-in {SYSLOG_DROPIN} is absent — the <logging> block did not "
        f"materialize (sync should run system_syslogd_start).\n{syslog_export_state_snapshot(vm)}"
    )
    assert "pfblockerng" in dropin.stdout and "pfblockerng_syslog.log" in dropin.stdout, (
        f"drop-in does not route program=pfblockerng to the dedicated file: {dropin.stdout!r}"
    )

    newsyslog = vm.ssh("/bin/cat", NEWSYSLOG_ENTRY, timeout=15.0)
    assert newsyslog.returncode == 0 and "pfblockerng_syslog.log" in newsyslog.stdout, (
        f"newsyslog rotation entry {NEWSYSLOG_ENTRY} is absent — the dedicated file would grow "
        f"unbounded.\n  got: {newsyslog.stdout!r} (rc={newsyslog.returncode})"
    )


# --------------------------------------------------------------------------- #
# Test 1: ON ⇒ DNSBL event exported to the dedicated file (LIVE toggle)
# --------------------------------------------------------------------------- #


def test_syslog_on_dnsbl_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """ON ⇒ a pfblockerng record per DNSBL block in the dedicated file, host-side, no restart.

    Given: DNSBL blocking _dnsbl_domain (VIP); syslog export OFF (fixture default),
           so NO event line exists in pfblockerng_syslog.log yet.
    When:  log_syslog is enabled (write_config ONLY — no restart) and the civm client
           (192.168.1.10) resolves the blocked domain via pfSense (python writes
           dnsbl.log, the host daemon tails it, re-reads the toggle live, and emits).
    Then:  a NEW record appears in pfblockerng_syslog.log with act=dnsbl + the
           queried name — proving the toggle took effect LIVE.
    And:   the event did NOT leak into system.log; the CSV dnsbl.log was also written.
    """
    vm = deployed_vm
    domain: str = vm._pfb_dnsbl_domain  # type: ignore[attr-defined]
    civm_ip: str = vm._pfb_civm_ip  # type: ignore[attr-defined]

    # Given: OFF before-state.
    before = _pfb_event_lines(vm)
    dnsbl_before = h.count_log_marker(vm, DNSBL_LOG, domain)
    sys_leak_before = len(_system_log_export_leaks(vm))

    # When: enable LIVE (no restart) + probe from the civm client.
    _set_syslog_enabled(vm, on=True)
    ans = h.dns_probe_client(client_vm, domain, "A")

    # Then: DNSBL still blocks (additive).
    assert h.is_vip(ans), f"DNSBL block shape changed after enabling syslog: expected VIP, got {ans}"

    # Then: a NEW dedicated-file record (poll — tail/daemon latency). Match on
    # act=dnsbl + the queried name (qname=). NOTE: b_type is the MATCH type
    # ('DNSBL'/'TLD'/'Python'), NOT the sinkhole mode — there is no 'VIP' b_type.
    line = _wait_for_event(vm, baseline_len=len(before), want=("act=dnsbl", f"qname={domain}", f"qip={civm_ip}"))
    assert line, (
        f"No new DNSBL export record after enabling export (LIVE, no restart) and probing {domain}.\n"
        f"  expected a new line in {PFB_SYSLOG_LOG} with: act=dnsbl qname={domain} qip={civm_ip}\n"
        f"  {syslog_export_state_snapshot(vm)}"
    )

    # And: it did NOT leak into system.log.
    assert len(_system_log_export_leaks(vm)) == sys_leak_before, (
        f"export event leaked into {SYSTEM_LOG} — the !pfblockerng drop-in should route it to the "
        f"dedicated file ONLY.\n  leaks: {_system_log_export_leaks(vm)[-5:]!r}"
    )

    # And: CSV dnsbl.log also written (additive).
    dnsbl_after = h.count_log_marker(vm, DNSBL_LOG, domain)
    assert dnsbl_after > dnsbl_before, (
        f"CSV dnsbl.log was NOT written after enabling syslog (before {dnsbl_before}, after {dnsbl_after}) "
        f"— export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 2: ON ⇒ IP Block event exported to the dedicated file
#
# DEFERRED (xfail) — the IP-block LIVE leg needs harness work, tracked as a
# follow-up. The IP syslog *mechanism* is the same host-side pfb_syslog_event +
# daemon path proven live by the DNSBL leg, and pfb_syslog_format_ip is unit-
# tested (tests/php/SyslogFormatTest.php). What is missing is a way to TRIGGER a
# pf-logged IP block from civm in the single-runner smoke:
#   * a LAN-interface pfB rule breaks ALL civm->pfSense traffic (the LAN filter
#     rebuild drops the permissive allow; civm DNS/ICMP then hit the default
#     block, rule 1000000103 — filterlog-confirmed);
#   * a WAN rule to the unreachable TEST-NET IP never logs (the SYN never
#     traverses the WAN-outbound path);
#   * the only IP civm can reach through pfSense is the runner (10.10.0.2), which
#     is the stub DNS + mock-feed server — blocking it breaks the harness.
# The follow-up adds a reachable, non-infra victim target + a WAN/floating rule
# (floating inbound/outbound/any) and un-xfails this.
# --------------------------------------------------------------------------- #


@pytest.mark.xfail(
    reason="IP-block live trigger needs a reachable non-infra target + WAN/floating rule "
    "(LAN rule breaks civm connectivity). Tracked as a follow-up; mechanism proven by the "
    "DNSBL leg + pfb_syslog_format_ip unit test.",
    strict=False,
)
def test_syslog_on_ip_block_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """ON ⇒ a pfblockerng record per IP Block event in the dedicated file.

    Given: an IP block alias covering 203.0.113.0/24; syslog export ON (from the
           DNSBL test); the filterlog daemon running; the civm client behind the
           firewall.
    When:  the civm client (192.168.1.10) curls a blocked IP (pass-through traffic
           pf blocks + logs — NOT pfSense's own traffic, which the rule misses).
    Then:  a new pfblockerng record appears in the dedicated file with an IP action
           token (act=block/pass/match).
    And:   the CSV ip_block.log is also written (additive).
    """
    vm = deployed_vm

    val = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    assert val == "on", f"Precondition: expected log_syslog='on' from prior test, got {val!r}"

    before = _pfb_event_lines(vm)
    ip_block_before = h.read_log_file(vm, IP_BLOCK_LOG)

    _trigger_ip_block(client_vm)

    line = _wait_for_event(vm, baseline_len=len(before), want=("act=",), any_of=IP_ACT_TOKENS)
    if not line:
        ps = vm.ssh("/bin/ps", "-wax", timeout=30)
        daemon_running = "pfblockerng.inc filterlog" in ps.stdout
        pfctl = vm.ssh("/sbin/pfctl", "-t", "pfB_pfb_syslog_iptest_v4", "-T", "show", timeout=30)
        alias_populated = TEST_IP_BLOCK_RANGE in pfctl.stdout or "203.0.113" in pfctl.stdout
        if not alias_populated:
            pytest.skip(
                f"IP block alias pfB_pfb_syslog_iptest_v4 not populated with {TEST_IP_BLOCK_RANGE} "
                f"— IP feed reload may have failed. pfctl: {pfctl.stdout!r}"
            )
        if not daemon_running:
            pytest.skip(f"filterlog daemon not running — cannot exercise the IP syslog path (ps: {ps.stdout[:400]!r})")
        raise AssertionError(
            f"No new IP-block export record after connection to {TEST_IP_BLOCK_DST}.\n"
            f"  expected a new line in {PFB_SYSLOG_LOG} with one of {list(IP_ACT_TOKENS)!r}\n"
            f"  daemon_running={daemon_running} alias_populated={alias_populated}\n"
            f"  {syslog_export_state_snapshot(vm)}"
        )

    ip_block_after = h.read_log_file(vm, IP_BLOCK_LOG)
    assert len(ip_block_after) > len(ip_block_before), (
        "CSV ip_block.log was NOT written after enabling syslog — export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 3: OFF ⇒ no new export records (LIVE toggle, before/after proof)
# --------------------------------------------------------------------------- #


def test_syslog_off_no_new_records(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """OFF ⇒ zero export; CSV logging unchanged — LIVE toggle, no restart.

    Before/after proof: first assert ON produced records (true from prior tests),
    then disable LIVE and assert the count does NOT increase. Exercised via the
    DNSBL leg (the IP-block live trigger is deferred — see the xfail above).

    Given: syslog export ON (from prior tests), records already in the dedicated file.
    When:  log_syslog set OFF (write_config ONLY — no restart); the blocked domain is
           probed again from civm.
    Then:  the export-record count does NOT increase — the daemon honored the LIVE off.
    And:   the CSV dnsbl.log is STILL written (additive path, independent of the toggle).
    """
    vm = deployed_vm
    domain: str = vm._pfb_dnsbl_domain  # type: ignore[attr-defined]

    count_while_on = len(_pfb_event_lines(vm))
    assert count_while_on > 0, (
        f"Precondition: expected export records from prior ON tests, but {PFB_SYSLOG_LOG} has "
        f"{count_while_on}.\n{syslog_export_state_snapshot(vm)}"
    )

    dnsbl_csv_before = h.count_log_marker(vm, DNSBL_LOG, domain)

    # When: disable LIVE (no restart) + re-probe the blocked domain from civm.
    _set_syslog_enabled(vm, on=False)
    ans = h.dns_probe_client(client_vm, domain, "A")
    assert h.is_vip(ans), f"DNSBL block should still work when syslog is OFF, got {ans}"
    time.sleep(FILTERLOG_SETTLE_SECS)

    # Then: no new export records (the LIVE off took effect).
    count_while_off = len(_pfb_event_lines(vm))
    assert count_while_off == count_while_on, (
        f"New export records appeared after disabling export LIVE (before {count_while_on}, after "
        f"{count_while_off}) — the live OFF gate is not working.\n{syslog_export_state_snapshot(vm)}"
    )

    # And: CSV still written in the OFF state (additive path independent of the toggle).
    dnsbl_csv_after = h.count_log_marker(vm, DNSBL_LOG, domain)
    assert dnsbl_csv_after > dnsbl_csv_before, (
        f"CSV dnsbl.log was NOT written while syslog export is OFF (before {dnsbl_csv_before}, "
        f"after {dnsbl_csv_after}) — the CSV path must be independent of the syslog toggle"
    )
