"""ADR-38 — live-VM smoke: syslog export of pfBlockerNG security events.

Proves the §2.2 contract (as revised by Amendment 1) on a real pfSense CE VM:

  1. Toggle OFF ⇒ zero event export, CSV logging unchanged.
  2. Toggle ON  ⇒ a ``pfblockerng`` key=value record per DNSBL block event in the
     dedicated /var/log/pfblockerng_syslog.log, emitted HOST-SIDE by
     ``pfb_daemon_filterlog`` — not by the chrooted python.
  3. Toggle ON + IP path ⇒ a ``pfblockerng`` record per IP Block event, exercised
     LIVE: civm reaches a blocked WAN-subnet IP through a floating, logged
     Deny_Outbound rule on WAN, and the host daemon exports the act=block event.
  4. CSV logging is unchanged in both states (export is purely additive).
  5. The toggle takes effect LIVE — no service restart between flipping it and
     the next event (the daemon re-reads config on config.xml change).
  6. Events go to the dedicated file ONLY — NOT duplicated into system.log.

ADR-38 Amendment 1: the export uses pfSense's standard package ``<logging>``
mechanism (declarative, in pfblockerng.xml) — core builds the syslog.d routing
drop-in (``!pfblockerng`` → pfblockerng_syslog.log), a newsyslog rotation entry,
and the Status→System Logs→Packages subtab, and removes the drop-in on uninstall.
Both syslog legs emit host-side (no chroot socket). Facility/severity are fixed
(LOG_LOCAL6 / LOG_INFO); the only user control is the log_syslog master toggle.

DESELECTED from the default ``python -m pytest`` (``--ignore=tests/smoke`` in
pyproject.toml). Run only by the smoke workflow::

    python -m pytest tests/smoke -m smoke --override-ini="addopts="

Needs the booted ``smoke_vm`` fixture, the branch ``.pkg`` (``SMOKE_PKG``), and
the ``stub_dns`` fixture. Without these all cases skip cleanly.
"""

from __future__ import annotations

import csv
import json
import os
import time
from collections.abc import Iterator

import pytest

from . import helpers as h
from .conftest import PFSENSE_LAN_IP, SmokeVM, _StubDnsServer

pytestmark = pytest.mark.smoke

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

# ADR-38: the dedicated package syslog file (from the <logging> block). The
# !pfblockerng syslog.d drop-in routes ONLY program=pfblockerng records here, so
# every line in this file is one exported security event.
PFB_SYSLOG_LOG = "/var/log/pfblockerng_syslog.log"
# Generated by pfSense core from the <logging> block (routing + rotation).
SYSLOG_DROPIN = "/var/etc/syslog.d/pfblockerng_syslog.log.conf"
NEWSYSLOG_ENTRY = "/var/etc/newsyslog.conf.d/pfblockerng_syslog.log.conf"
# General System log — export events must NOT appear here (excluded by the drop-in).
SYSTEM_LOG = "/var/log/system.log"

# pfBlockerNG CSV security logs (unchanged by syslog export).
PFB_LOGDIR = "/var/log/pfblockerng"
DNSBL_LOG = f"{PFB_LOGDIR}/dnsbl.log"
IP_BLOCK_LOG = f"{PFB_LOGDIR}/ip_block.log"
UNIFIED_LOG = f"{PFB_LOGDIR}/unified.log"
IP_CACHE = "/var/db/pfblockerng/ip_cache.sqlite"

# Config path for the syslog export toggle (under the General settings section).
CFG_GENERAL = "installedpackages/pfblockerng/config/0"

# The IP the pfBlockerNG floating Deny_Outbound rule blocks, exercised by civm.
# It MUST sit in the pfSense WAN subnet (192.168.89.0/24, the QEMU SLIRP net) so the
# forwarded SYN is routed straight out the directly-connected WAN — a non-WAN
# TEST-NET dst depends on the SLIRP default gateway (flaky/down in CI) and never
# traverses the WAN-out path, so the rule never matches. .9 is unused: NOT the
# SLIRP gateway (.1), the runner/stub-DNS/mock-feed host alias (.2), or DNS (.3).
TEST_IP_BLOCK_RANGE = "192.168.89.9/32"
TEST_IP_BLOCK_DST = "192.168.89.9"

EVENT_WAIT_SECS = 15.0
# IP action tokens any IP security event may carry (block/permit/match).
IP_ACT_TOKENS = ("act=block", "act=pass", "act=match")


# --------------------------------------------------------------------------- #
# Module-scoped fixture: deploy once, inject DNSBL + IP, reload (syslog OFF)
# --------------------------------------------------------------------------- #


@pytest.fixture(scope="module")
def deployed_vm(
    smoke_vm: SmokeVM,
    client_vm: SmokeVM,
    stub_dns: _StubDnsServer,
) -> Iterator[SmokeVM]:
    """Deploy the branch .pkg once; wire DNSBL + IP; reload with syslog OFF.

    Given: the smoke VM is booted and the branch .pkg is available.
    When:  we deploy, wire DNSBL (five unique blocked domains, VIP — seed, subject, OFF-state
           drain, and ON-state barrier queries stay distinguishable) + one IP block feed
           (RFC 5737), and do a full reload with syslog export OFF (the default).
           The reload runs sync_package_pfblockerng, which materializes the syslog
           routing drop-in (ADR-38) and (re)starts the filterlog daemon tailing
           filter.log + dnsbl.log + dns_reply.log.
    Then:  the module VM is ready for the per-test assertions.
    """
    if not os.environ.get("SMOKE_PKG"):
        pytest.skip("SMOKE_PKG not set — no built .pkg to deploy")

    h.deploy(smoke_vm)
    h.use_system_dns_upstream(smoke_vm)
    h.ensure_dnsbl_vip(smoke_vm)

    _dnsbl_domain = h.unique_domain("pfbsyslogdnsbl")
    _dnsbl_domain_on = h.unique_domain("pfbsyslogdnsbl2")
    _dnsbl_seed = h.unique_domain("pfbsyslogdnsblseed")
    _dnsbl_drain = h.unique_domain("pfbsyslogdnsbldrain")
    _dnsbl_barrier = h.unique_domain("pfbsyslogdnsblbarrier")
    _dnsbl_feed_path = h.write_local_feed(
        smoke_vm,
        "pfb_syslog_dnsbl.txt",
        f"{_dnsbl_domain}\n{_dnsbl_domain_on}\n{_dnsbl_seed}\n{_dnsbl_drain}\n{_dnsbl_barrier}\n",
    )
    h.inject(
        smoke_vm,
        h.DnsblCase(
            aliasname="pfb_syslog_test",
            feed_url=_dnsbl_feed_path,
            mode=h.DnsblMode.VIP,
            header="pfb_syslog_dnsbl",
            hsts=False,  # explicit — test domain is not HSTS-preloaded
        ),
    )

    # IP feed: a floating, LOGGED Deny_Outbound rule for a WAN-subnet victim IP.
    # inject() wires inbound/outbound_interface=wan (SMOKE_IP_IFACE);
    # _enable_ip_floating_logged_rule then flips it to a floating `block out quick log`
    # on WAN — which catches civm's forwarded SYN leaving WAN (a non-floating WAN rule
    # is block-IN and never matches forwarded-out traffic; a LAN-interface rule breaks
    # civm connectivity) and emits a filter.log line the daemon can export.
    _ip_feed_path = h.write_local_feed(smoke_vm, "pfb_syslog_ip.txt", f"{TEST_IP_BLOCK_RANGE}\n")
    h.inject(
        smoke_vm,
        h.IpCase(
            aliasname="pfb_syslog_iptest",
            feed_url=_ip_feed_path,
            action="Deny_Outbound",
            family="v4",
            header="pfb_syslog_ip",
        ),
    )
    _enable_ip_floating_logged_rule(smoke_vm)

    # Syslog export OFF (the default) at module start.
    _set_syslog_enabled(smoke_vm, on=False)

    # Full reload: installs DNSBL + IP block, materializes the syslog routing, and
    # starts the filterlog daemon.
    h.reload(smoke_vm, "update")

    # Precondition: the civm -> pfSense LAN link is healthy (civm can resolve via
    # pfSense). All cases drive traffic from civm, so a dead LAN link must surface
    # as a clear "civm/LAN link" diagnosis here, not a bare dig timeout deep in a test.
    h.assert_link_health(client_vm, smoke_vm, control_name=h.unique_domain())

    # civm's ACTUAL LAN IP (static or dynamic lease) — the expected qip/source in
    # the export events. Captured once the link is proven healthy.
    _civm_ip = _civm_lan_ip(client_vm)

    # Precondition: DNSBL is blocking the test domain (VIP shape), as seen by the
    # civm client behind the firewall (the realistic consumer path).
    ans = h.dns_probe_client(client_vm, _dnsbl_domain, "A")
    if not h.is_vip(ans):
        pytest.skip(
            f"DNSBL VIP block not observed for {_dnsbl_domain} (got {ans}) — "
            f"DNSBL precondition failed; skipping syslog tests"
        )

    smoke_vm._pfb_dnsbl_domain = _dnsbl_domain  # type: ignore[attr-defined]
    smoke_vm._pfb_dnsbl_domain_on = _dnsbl_domain_on  # type: ignore[attr-defined]
    smoke_vm._pfb_syslog_seed = _dnsbl_seed  # type: ignore[attr-defined]
    smoke_vm._pfb_syslog_drain = _dnsbl_drain  # type: ignore[attr-defined]
    smoke_vm._pfb_syslog_barrier = _dnsbl_barrier  # type: ignore[attr-defined]
    smoke_vm._pfb_civm_ip = _civm_ip  # type: ignore[attr-defined]
    yield smoke_vm


@pytest.fixture(autouse=True)
def _syslog_export_off(deployed_vm: SmokeVM) -> None:
    """Per-test isolation (#1396): every test starts with syslog export OFF.

    A test that needs export ON seeds it itself — no test may inherit the toggle
    (or prior export records) from a sibling, so each node passes alone through
    the filtered smoke path and in any order. Fails loudly if the reset does not
    take (a module-scoped baseline is NOT per-test isolation).
    """
    _set_syslog_enabled(deployed_vm, on=False)
    val = h.config_get(deployed_vm, CFG_GENERAL + "/log_syslog")
    assert val == "", f"syslog-export OFF reset did not take: log_syslog={val!r}"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def _set_syslog_enabled(vm: SmokeVM, *, on: bool, timeout: float = 60.0) -> None:
    """Toggle log_syslog and write_config — NO service restart.

    ADR-38 Amendment 1: the long-running pfb_filter daemon re-reads log_syslog on
    config.xml change (pfb_filterlog_refresh_config + pfb_syslog_event read fresh),
    so a LIVE toggle takes effect on the next block event with no restart. The test
    deliberately does NOT restart anything — that is the behaviour being proven.
    """
    val = "on" if on else ""
    snippet = (
        f"$g = config_get_path({h._php_str(CFG_GENERAL)}, array());\n"
        f"$g['log_syslog'] = {h._php_str(val)};\n"
        f"config_set_path({h._php_str(CFG_GENERAL)}, $g);\n"
        "write_config('pfBlockerNG smoke: toggle log_syslog');\n"
        "echo 'OK';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"_set_syslog_enabled({on}) failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _enable_ip_floating_logged_rule(vm: SmokeVM, *, timeout: float = 60.0) -> None:
    """Make pfBlockerNG emit the IP deny rule as a FLOATING, LOGGED ``out`` rule.

    Two ipsettings flags, both required for the IP-block syslog leg:

    * ``enable_float``: inject() wires inbound/outbound_interface=wan (SMOKE_IP_IFACE).
      A *non*-floating Deny_Outbound on WAN is a block-IN rule (pfblockerng.inc:8142) —
      it never sees civm's forwarded traffic LEAVING via WAN. enable_float flips it to
      ``direction=out`` (inc:8148): a floating ``block out quick`` on WAN that DOES match
      the forwarded SYN. Floating-on-WAN also leaves the LAN allow intact — a
      per-interface LAN rule rebuild drops the "allow LAN→any" and breaks civm's DNS.
    * ``enable_log`` (global IP logging): pfBlockerNG only stamps ``log`` on the rule when
      global logging is on or the list's aliaslog='enabled' (inc:8175). Without it the
      rule blocks SILENTLY — no filter.log line — so the host filterlog daemon never sees
      the event and nothing is exported. This is the flag the IP syslog leg hinges on.
    """
    snippet = (
        f"$ip = config_get_path({h._php_str(h.CFG_IP_SETTINGS)}, array());\n"
        "$ip['enable_float'] = 'on';\n"
        "$ip['enable_log'] = 'on';\n"
        f"config_set_path({h._php_str(h.CFG_IP_SETTINGS)}, $ip);\n"
        "write_config('pfBlockerNG smoke: enable floating + logged IP rule');\n"
        "echo 'OK';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"_enable_ip_floating_logged_rule failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _civm_lan_ip(client_vm: SmokeVM, *, timeout: float = 30.0) -> str:
    """civm's ACTUAL IPv4 on the pfSense LAN subnet (192.168.1.0/24).

    Queried from civm rather than assuming the 192.168.1.10 static lease — so the
    tests work whether civm got the static lease OR a dynamic one. Used as the
    expected ``qip=`` / source in the export-event assertions.
    """
    r = client_vm.ssh(
        "/bin/sh", "-c", "ip -4 -o addr show 2>/dev/null | grep -oE '192\\.168\\.1\\.[0-9]+' | head -1", timeout=timeout
    )
    ip = r.stdout.strip()
    if not ip:
        raise RuntimeError(f"civm has no 192.168.1.x LAN IP: rc={r.returncode} out={r.stdout!r} err={r.stderr!r}")
    return ip


def _pfb_event_lines(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Exported security-event lines in the dedicated pfblockerng_syslog.log.

    The !pfblockerng drop-in routes ONLY program=pfblockerng records here, and the
    body always begins ``act=`` — so a non-empty line containing ``act=`` is one of
    our events. Returns [] if the file is absent (export never fired).
    """
    content = h.read_log_file(vm, PFB_SYSLOG_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "act=" in ln]


def _pfb_event_history_lines(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Return dedicated events across the current log and newsyslog rotations."""
    script = (
        "set -e\n"
        f"for file in {PFB_SYSLOG_LOG} {PFB_SYSLOG_LOG}.[0-9]*; do\n"
        '  [ -f "$file" ] || continue\n'
        '  /usr/bin/bsdcat "$file"\n'
        "done\n"
    )
    result = vm.ssh("/bin/sh", "-c", script, timeout=timeout)
    if result.returncode != 0:
        raise RuntimeError(
            f"dedicated syslog history read failed: rc={result.returncode} "
            f"stdout={result.stdout!r} stderr={result.stderr!r}"
        )
    return [line for line in result.stdout.splitlines() if "act=" in line]


def _system_log_export_leaks(vm: SmokeVM, *, timeout: float = 30.0) -> list[str]:
    """Export records that LEAKED into system.log (must always be empty).

    Matches program=pfblockerng (``pfblockerng[<pid>]:``) AND an ``act=`` body.
    The operational ``[pfBlockerNG]`` logs are program=php (no ``act=`` body), so
    they are not matched — only a genuine leak of an export event would show here.
    """
    content = h.read_log_file(vm, SYSTEM_LOG, timeout=timeout)
    return [ln for ln in content.splitlines() if "pfblockerng[" in ln and "act=" in ln]


def _wait_for_event(
    vm: SmokeVM,
    *,
    baseline_len: int,
    want: tuple[str, ...],
    any_of: tuple[str, ...] = (),
    timeout: float = EVENT_WAIT_SECS,
    interval: float = 1.0,
) -> str:
    """Poll the dedicated file for a NEW event line or raise a salvage-only expiry."""
    deadline = time.monotonic() + timeout
    last_new: list[str] = []
    while True:
        new = _pfb_event_lines(vm)[baseline_len:]
        last_new = new
        for ln in new:
            if all(tok in ln for tok in want) and (not any_of or any(tok in ln for tok in any_of)):
                return ln
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise RuntimeError(
                f"salvage cap expired / stuck or environment: _wait_for_event expected want={want!r} "
                f"and any_of={any_of!r}; observed last new lines={last_new!r}"
            )
        time.sleep(min(interval, remaining))


def _unified_dnsbl_lines(vm: SmokeVM) -> list[str]:
    """Return DNSBL rows already consumed by the filterlog daemon."""
    return [line for line in h.read_log_file(vm, UNIFIED_LOG).splitlines() if line.startswith("DNSBL-python,")]


def _wait_for_unified_dnsbl(vm: SmokeVM, domain: str, *, baseline_len: int, dnsbl_baseline: int) -> str:
    """Wait for a later drain row proving earlier DNSBL input was consumed."""
    found = [""]
    observed_rows = _unified_dnsbl_lines(vm)
    marker_count = h.count_log_marker(vm, DNSBL_LOG, domain)

    def observed() -> bool:
        nonlocal marker_count, observed_rows
        found[0] = ""
        observed_rows = _unified_dnsbl_lines(vm)
        for line in observed_rows[baseline_len:]:
            try:
                fields = next(csv.reader([line]))
            except csv.Error:
                continue
            if len(fields) == 11 and fields[2] == domain:
                found[0] = line
                break
        marker_count = h.count_log_marker(vm, DNSBL_LOG, domain)
        return bool(found[0]) and marker_count > dnsbl_baseline

    try:
        h.wait_until(observed, timeout=EVENT_WAIT_SECS, interval=1.0)
    except RuntimeError as exc:
        raise RuntimeError(
            "salvage cap expired / stuck or environment: _wait_for_unified_dnsbl expected "
            f"domain={domain!r} after baseline_len={baseline_len} and marker count > {dnsbl_baseline}; "
            f"observed marker count={marker_count} unified rows={observed_rows!r}"
        ) from exc
    return found[0]


def syslog_export_state_snapshot(vm: SmokeVM) -> str:
    """On-box syslog-export state for failure diagnostics. Never raises."""
    try:
        log_syslog = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    except Exception:
        log_syslog = "(error)"
    try:
        ls = vm.ssh("/bin/ls", "-l", SYSLOG_DROPIN, PFB_SYSLOG_LOG, timeout=10.0)
        routing = ls.stdout.strip() or "(absent)"
    except Exception:
        routing = "(error)"
    daemon = "(error)"
    try:
        ps = vm.ssh(
            "/bin/sh",
            "-c",
            "/bin/ps -waxo pid,start,command | /usr/bin/grep '[p]fblockerng.inc filterlog'",
            timeout=10.0,
        )
        daemon = ps.stdout.strip() or "(not running)"
    except Exception:
        pass
    try:
        events = _pfb_event_lines(vm)
    except Exception:
        events = []
    # Dump the ACTUAL recent event lines, not just a count — so a failure shows what
    # WAS emitted vs what the assertion expected (read the logs, don't chase ghosts).
    recent = "\n    ".join(events[-8:]) if events else "(none)"
    return (
        f"log_syslog={log_syslog!r} event_lines={len(events)}\n"
        f"  routing: {routing}\n  filterlog: {daemon}\n"
        f"  recent {PFB_SYSLOG_LOG} lines (last {min(len(events), 8)}):\n    {recent}"
    )


def _trigger_ip_block(client: SmokeVM, *, port: int = 80, timeout: float = 30.0) -> None:
    """Generate a pf-logged IP block by curling the blocked WAN IP FROM civm.

    The block must be triggered by PASS-THROUGH traffic — a client BEHIND the
    firewall (civm) reaching the blocked WAN IP — not by pfSense's own stack: the
    floating Deny_Outbound rule acts on forwarded traffic leaving WAN, so a curl
    from pfSense itself would not hit it.

    civm has TWO equal-metric default routes (mgmt ens4 via the QEMU mgmt SLIRP,
    and LAN ens5 via pfSense), so a bare curl may egress the mgmt NIC and never
    reach pfSense. Pin a host route for the victim via pfSense (192.168.1.1) out
    the LAN device first, forcing the SYN civm -> pfSense -> WAN-out -> the block.
    """
    client.ssh(
        "/bin/sh",
        "-c",
        "dev=$(ip -4 -o addr show | awk '/192\\.168\\.1\\./{print $2; exit}'); "
        f'ip route replace {TEST_IP_BLOCK_DST}/32 via {PFSENSE_LAN_IP} dev "$dev" 2>/dev/null || true; '
        f"curl --connect-timeout 2 --max-time 4 http://{TEST_IP_BLOCK_DST}:{port}/ >/dev/null 2>&1 || true",
        timeout=timeout,
    )


def _ip_cache_snapshot(vm: SmokeVM, *, timeout: float = 30.0) -> tuple[int, dict[str, tuple[str, str]]] | None:
    """Return the cache inode plus host -> (feed, evaluated entry), or None when absent."""
    open_marker = "<<<IPCACHE>>>"
    close_marker = "<<<IPCACHEEND>>>"
    snippet = (
        f"$path = {h._php_str(IP_CACHE)};\n"
        f"if (!file_exists($path)) {{ echo {h._php_str(open_marker + 'MISSING' + close_marker)}; }} else {{\n"
        "$db = new SQLite3($path);\n"
        "$rows = array();\n"
        "$result = $db->query('SELECT host, q0, q1 FROM ipcache ORDER BY host');\n"
        "while ($row = $result->fetchArray(SQLITE3_ASSOC)) { $rows[] = $row; }\n"
        f"echo {h._php_str(open_marker)} . json_encode(array('inode' => fileinode($path), 'rows' => $rows))"
        f" . {h._php_str(close_marker)};\n"
        "$db->close();\n"
        "}"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0:
        raise RuntimeError(f"IP cache snapshot failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}")
    start = result.stdout.find(open_marker)
    end = result.stdout.find(close_marker, start + len(open_marker))
    if start == -1 or end == -1:
        raise RuntimeError(f"IP cache snapshot markers absent: {result.stdout!r}")
    raw = result.stdout[start + len(open_marker) : end]
    if raw == "MISSING":
        return None
    payload = json.loads(raw)
    rows = {str(row["host"]): (str(row["q0"]), str(row["q1"])) for row in payload["rows"]}
    return int(payload["inode"]), rows


def _seed_ip_cache_row(vm: SmokeVM, host: str, feed: str, evaluated: str, *, timeout: float = 30.0) -> None:
    """Add a second production-shaped cache row so a whole-file flush is observable."""
    snippet = (
        f"$db = new SQLite3({h._php_str(IP_CACHE)});\n"
        "$stmt = $db->prepare('INSERT INTO ipcache (host, q0, q1, geoip, resolved_host) "
        "VALUES (:host, :q0, :q1, :geoip, :resolved_host)');\n"
        f"$stmt->bindValue(':host', {h._php_str(host)}, SQLITE3_TEXT);\n"
        f"$stmt->bindValue(':q0', {h._php_str(feed)}, SQLITE3_TEXT);\n"
        f"$stmt->bindValue(':q1', {h._php_str(evaluated)}, SQLITE3_TEXT);\n"
        "$stmt->bindValue(':geoip', 'Unk', SQLITE3_TEXT);\n"
        "$stmt->bindValue(':resolved_host', 'Unknown', SQLITE3_TEXT);\n"
        "$ok = $stmt->execute();\n"
        "echo $ok ? 'OK' : 'FAIL';\n"
        "$db->close();"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(f"IP cache seed failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}")


def _set_ip_attribution_rows(vm: SmokeVM, feed_a: str, feed_b: str, *, timeout: float = 60.0) -> None:
    """Give the fixture's existing IP alias two attribution-source rows."""
    row_a = {
        "header": "pfb_syslog_ip",
        "url": feed_a,
        "state": "Enabled",
        "format": "auto",
    }
    row_b = {
        "header": "pfb_syslog_ip_b",
        "url": feed_b,
        "state": "Enabled",
        "format": "auto",
    }
    snippet = (
        f"$lists = config_get_path({h._php_str(h.CFG_IP_V4_LISTS)}, array());\n"
        "$found = false;\n"
        "foreach ($lists as &$list) {\n"
        "if (($list['aliasname'] ?? '') === 'pfb_syslog_iptest') {\n"
        f"$list['row'] = array({h._php_kv_array(row_a)}, {h._php_kv_array(row_b)});\n"
        "$found = true;\n"
        "}\n"
        "}\n"
        "unset($list);\n"
        f"config_set_path({h._php_str(h.CFG_IP_V4_LISTS)}, $lists);\n"
        "write_config('pfBlockerNG smoke: IP attribution source rows');\n"
        "echo $found ? 'OK' : 'NOTFOUND';"
    )
    result = h.php_eval(vm, snippet, timeout=timeout)
    if result.returncode != 0 or "OK" not in result.stdout:
        raise RuntimeError(
            f"IP attribution row setup failed: rc={result.returncode} {result.stderr!r} {result.stdout!r}"
        )


def _filterlog_pid(vm: SmokeVM, *, timeout: float = 30.0) -> str:
    """Return the live filterlog daemon PID, failing loudly when it is absent."""
    result = vm.ssh(
        "/bin/sh",
        "-c",
        "/bin/ps -waxo pid,command | /usr/bin/awk '/[p]fblockerng.inc filterlog/{print $1; exit}'",
        timeout=timeout,
    )
    pid = result.stdout.strip()
    if result.returncode != 0 or not pid:
        raise RuntimeError(f"filterlog daemon PID absent: rc={result.returncode} {result.stderr!r} {result.stdout!r}")
    return pid


def _last_log_line(vm: SmokeVM, path: str, *tokens: str) -> str:
    """Return the newest line containing every token, or an empty string."""
    return next(
        (line for line in reversed(h.read_log_file(vm, path).splitlines()) if all(token in line for token in tokens)),
        "",
    )


# --------------------------------------------------------------------------- #
# Test 0: the <logging> mechanism is materialized (routing + rotation)
# --------------------------------------------------------------------------- #


def test_syslog_routing_and_rotation_registered(deployed_vm: SmokeVM) -> None:
    """ADR-38: the declarative <logging> block yields the routing drop-in + newsyslog entry.

    Given: pfBlockerNG deployed and reloaded (the fixture).
    Then:  pfSense core has generated BOTH the syslog.d routing drop-in (so events
           reach the dedicated file) AND the newsyslog.conf.d rotation entry (so the
           file is size-capped/rotated for us — no bespoke rotation needed).
    """
    vm = deployed_vm

    dropin = vm.ssh("/bin/cat", SYSLOG_DROPIN, timeout=15.0)
    assert dropin.returncode == 0, (
        f"syslog routing drop-in {SYSLOG_DROPIN} is absent — the <logging> block did not "
        f"materialize (sync should run system_syslogd_start).\n{syslog_export_state_snapshot(vm)}"
    )
    assert "pfblockerng" in dropin.stdout and "pfblockerng_syslog.log" in dropin.stdout, (
        f"drop-in does not route program=pfblockerng to the dedicated file: {dropin.stdout!r}"
    )

    newsyslog = vm.ssh("/bin/cat", NEWSYSLOG_ENTRY, timeout=15.0)
    assert newsyslog.returncode == 0 and "pfblockerng_syslog.log" in newsyslog.stdout, (
        f"newsyslog rotation entry {NEWSYSLOG_ENTRY} is absent — the dedicated file would grow "
        f"unbounded.\n  got: {newsyslog.stdout!r} (rc={newsyslog.returncode})"
    )


# --------------------------------------------------------------------------- #
# Test 1: ON ⇒ DNSBL event exported to the dedicated file (LIVE toggle)
# --------------------------------------------------------------------------- #


def test_syslog_on_dnsbl_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """OFF subject → OFF drain → ON barrier; subject must stay absent from syslog."""
    vm = deployed_vm
    domain_off: str = vm._pfb_dnsbl_domain  # type: ignore[attr-defined]
    drain_domain: str = vm._pfb_dnsbl_domain_on  # type: ignore[attr-defined]
    barrier_domain: str = vm._pfb_syslog_barrier  # type: ignore[attr-defined]
    civm_ip: str = vm._pfb_civm_ip  # type: ignore[attr-defined]

    # Given: syslog export OFF (per-test reset) — baseline whatever is already there.
    sys_leak_before = len(_system_log_export_leaks(vm))

    # While OFF, emit a later distinguishable DNSBL event. Seeing that drain row in
    # unified.log proves tail_pfb consumed the earlier subject before the gate flips ON.
    unified_baseline = len(_unified_dnsbl_lines(vm))
    dnsbl_off_before = h.count_log_marker(vm, DNSBL_LOG, domain_off)
    h.flush_unbound_name(vm, domain_off)
    ans_off = h.dns_probe_client(client_vm, domain_off, "A")
    assert h.is_vip(ans_off), f"DNSBL block shape unexpected before enabling syslog: expected VIP, got {ans_off}"
    drain_dnsbl_before = h.count_log_marker(vm, DNSBL_LOG, drain_domain)
    h.flush_unbound_name(vm, drain_domain)
    drain_answer = h.dns_probe_client(client_vm, drain_domain, "A")
    assert h.is_vip(drain_answer), f"DNSBL OFF-state drain should be VIP, got {drain_answer}"
    _wait_for_unified_dnsbl(
        vm,
        drain_domain,
        baseline_len=unified_baseline,
        dnsbl_baseline=drain_dnsbl_before,
    )

    dnsbl_off_after = h.count_log_marker(vm, DNSBL_LOG, domain_off)
    assert dnsbl_off_after > dnsbl_off_before, (
        f"CSV dnsbl.log was NOT written for the OFF-phase probe (before {dnsbl_off_before}, after "
        f"{dnsbl_off_after}) — the block itself must fire regardless of the syslog toggle"
    )
    # When: enable LIVE (no restart) + probe the distinct configured barrier domain.
    dnsbl_barrier_before = h.count_log_marker(vm, DNSBL_LOG, barrier_domain)
    _set_syslog_enabled(vm, on=True)
    barrier_baseline = len(_pfb_event_lines(vm))
    h.flush_unbound_name(vm, barrier_domain)
    ans = h.dns_probe_client(client_vm, barrier_domain, "A")

    # Then: DNSBL still blocks (additive).
    assert h.is_vip(ans), f"DNSBL block shape changed after enabling syslog: expected VIP, got {ans}"

    # Then: a NEW dedicated-file record (poll — tail/daemon latency). Match on
    # act=dnsbl + the queried name (qname=). NOTE: b_type is the MATCH type
    # ('DNSBL'/'TLD'/'Python'), NOT the sinkhole mode — there is no 'VIP' b_type.
    _wait_for_event(vm, baseline_len=barrier_baseline, want=("act=dnsbl", f"qname={barrier_domain}", f"qip={civm_ip}"))

    # This qname is unique to the module and queried only while export is OFF.
    # Search rotations too so newsyslog cannot erase the negative evidence.
    phase_lines = _pfb_event_history_lines(vm)
    assert any(f"qname={barrier_domain}" in event and f"qip={civm_ip}" in event for event in phase_lines), (
        f"dedicated syslog history missing already-observed barrier {barrier_domain}: {phase_lines!r}"
    )
    assert not any(f"qname={domain_off}" in event for event in phase_lines), (
        f"OFF-phase subject {domain_off} appeared in syslog after its unified row was consumed: "
        f"{phase_lines!r}\n{syslog_export_state_snapshot(vm)}"
    )

    # And: it did NOT leak into system.log.
    assert len(_system_log_export_leaks(vm)) == sys_leak_before, (
        f"export event leaked into {SYSTEM_LOG} — the !pfblockerng drop-in should route it to the "
        f"dedicated file ONLY.\n  leaks: {_system_log_export_leaks(vm)[-5:]!r}"
    )

    # And: CSV dnsbl.log also written for the ON-phase probe (additive).
    dnsbl_barrier_after = h.count_log_marker(vm, DNSBL_LOG, barrier_domain)
    assert dnsbl_barrier_after > dnsbl_barrier_before, (
        f"CSV dnsbl.log was NOT written after enabling syslog (before {dnsbl_barrier_before}, after "
        f"{dnsbl_barrier_after}) — export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 2: ON ⇒ IP Block event exported to the dedicated file (LIVE).
#
# The IP-block leg is exercised live via a FLOATING, LOGGED Deny_Outbound rule on
# WAN (_enable_ip_floating_logged_rule) blocking a WAN-subnet victim (TEST_IP_BLOCK_DST):
#   * a LAN-interface pfB rule was found to break ALL civm->pfSense traffic (the
#     LAN filter rebuild drops the permissive allow; civm DNS/ICMP then hit the
#     default block, rule 1000000103 — filterlog-confirmed);
#   * a NON-floating WAN Deny_Outbound is a block-IN rule (inc:8142), so it never
#     matches civm's forwarded traffic LEAVING via WAN;
#   * a non-WAN TEST-NET dst depends on the (flaky) SLIRP default gateway and
#     never traverses the WAN-out path;
#   * without global IP logging the rule blocks SILENTLY (no `log`, inc:8175), so
#     filter.log/the daemon never see it — enable_log is what makes it exportable.
# The floating `block out quick log` on WAN matches the forwarded SYN AND leaves the
# LAN allow intact (it matches only dst=<alias>); the WAN-subnet victim is
# directly connected so it routes out WAN with no default-gateway dependency.
# --------------------------------------------------------------------------- #


def test_syslog_on_ip_block_event_exported(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """ON ⇒ a pfblockerng record per IP Block event in the dedicated file.

    Given: a floating Deny_Outbound rule covering TEST_IP_BLOCK_RANGE; syslog export
           ON (seeded by THIS test — LIVE toggle, no restart, never inherited from a
           sibling, #1396); the filterlog daemon running; the civm client
           behind the firewall.
    When:  the civm client curls the blocked WAN IP (pass-through traffic pf blocks
           + logs on WAN-out — NOT pfSense's own traffic, which the rule misses).
    Then:  a new pfblockerng record appears in the dedicated file that references the
           victim dst IP (TEST_IP_BLOCK_DST) LITERALLY and carries an IP action token
           (act=block/pass/match) — not merely any new pfB event (#814: a resolved
           hostname in place of the literal dst would previously slip past this assert).
    And:   the CSV ip_block.log is also written (additive).
    """
    vm = deployed_vm

    # Seed our own ON state LIVE (no restart) — never inherited from a sibling (#1396).
    _set_syslog_enabled(vm, on=True)
    val = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    assert val == "on", f"seeded log_syslog did not take: expected 'on', got {val!r}"

    before = _pfb_event_lines(vm)
    ip_block_before = h.read_log_file(vm, IP_BLOCK_LOG)

    _trigger_ip_block(client_vm)

    try:
        _wait_for_event(vm, baseline_len=len(before), want=(TEST_IP_BLOCK_DST,), any_of=IP_ACT_TOKENS)
    except RuntimeError as exc:
        ps = vm.ssh("/bin/ps", "-wax", timeout=30)
        daemon_running = "pfblockerng.inc filterlog" in ps.stdout
        pfctl = vm.ssh("/sbin/pfctl", "-t", "pfB_pfb_syslog_iptest_v4", "-T", "show", timeout=30)
        alias_populated = TEST_IP_BLOCK_DST in pfctl.stdout
        # #814 near-miss diagnostic: the OLD (loose) match was "any new pfB act= event" —
        # any_of=IP_ACT_TOKENS with no want. If that loose condition WOULD have matched but the
        # tightened want=(TEST_IP_BLOCK_DST,) did not, the daemon IS exporting IP-block events,
        # just not ones that reference the victim dst literally (e.g. a resolved hostname in
        # its place) — the exact evidence needed to tell "nothing exported" apart from "exported,
        # but not the literal IP".
        new_lines = _pfb_event_lines(vm)[len(before) :]
        near_misses = [
            ln for ln in new_lines if any(tok in ln for tok in IP_ACT_TOKENS) and TEST_IP_BLOCK_DST not in ln
        ]
        near_miss_report = "\n    ".join(near_misses[-5:]) if near_misses else "(none)"
        # An unpopulated alias or a dead filterlog daemon are NOT benign preconditions to skip
        # past -- this un-xfailed leg (ADR-38 A2.4) exists specifically to catch those two
        # regression classes (a failed IP feed reload / a crashed export daemon), so both fold
        # into the same hard failure instead of turning a target regression into a green skip.
        if not alias_populated:
            precondition = (
                f"IP block alias pfB_pfb_syslog_iptest_v4 not populated with {TEST_IP_BLOCK_RANGE} "
                "— IP feed reload likely failed"
            )
        elif not daemon_running:
            precondition = "filterlog daemon not running — the pfBlockerNG export daemon died"
        elif near_misses:
            precondition = (
                f"a new pfB IP event fired but did not reference {TEST_IP_BLOCK_DST} literally — "
                "see the near-miss lines below (possibly a resolved hostname instead of the dst IP)"
            )
        else:
            precondition = "none — daemon running and alias populated"
        raise RuntimeError(
            f"salvage cap expired / stuck or environment: no new IP-block export record referencing "
            f"{TEST_IP_BLOCK_DST} after connection to it.\n"
            f"  expected a new line in {PFB_SYSLOG_LOG} with {TEST_IP_BLOCK_DST!r} and one of {list(IP_ACT_TOKENS)!r}\n"
            f"  actual:   no matching line found\n"
            f"  new pfB events that did NOT reference the victim dst (last {min(len(near_misses), 5)}):\n"
            f"    {near_miss_report}\n"
            f"  daemon_running={daemon_running} alias_populated={alias_populated}\n"
            f"  precondition broken: {precondition}\n"
            f"  ps: {ps.stdout[:400]!r}\n"
            f"  pfctl: {pfctl.stdout!r}\n"
            f"  {syslog_export_state_snapshot(vm)}"
        ) from exc

    ip_block_after = h.read_log_file(vm, IP_BLOCK_LOG)
    assert len(ip_block_after) > len(ip_block_before), (
        "CSV ip_block.log was NOT written after enabling syslog — export must be additive"
    )


# --------------------------------------------------------------------------- #
# Test 3: event-time IP attribution cache follows successful feed ownership moves.
# --------------------------------------------------------------------------- #


def test_ip_attribution_cache_invalidated_after_feed_ownership_change(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """A successful feed reparse invalidates cached event attribution without a rule reload.

    Given: one blocked host belongs to FeedA, a second host belongs to FeedB, and an
           event caches FeedA plus its evaluated CIDR for the blocked host.
    When:  a no-op pass, an unlock-only pass, then a genuine refetch move the two
           hosts between feeds while leaving the alias's final membership unchanged.
    Then:  the no-op and unlock-only passes preserve the cache, but the refetch drops
           the whole cache; the next event recomputes FeedB in CSV, unified, and syslog
           output while the historical FeedA CSV row remains unchanged.
    """
    vm = deployed_vm
    alias = "pfB_pfb_syslog_iptest_v4"
    feed_a_header = "pfb_syslog_ip_v4"
    feed_b_header = "pfb_syslog_ip_b_v4"
    feed_a_path = h.write_local_feed(vm, "pfb_syslog_ip.txt", f"{TEST_IP_BLOCK_RANGE}\n")
    control_ip = "198.51.100.240"
    control_range = f"{control_ip}/32"
    feed_b_path = h.write_local_feed(vm, "pfb_syslog_ip_b.txt", f"{control_range}\n")
    sentinel_host = "203.0.113.250"
    original_syslog = h.config_get(vm, CFG_GENERAL + "/log_syslog")
    token = "ipattrcache"
    marker = h.hook_marker_path(token, "post")

    try:
        _set_ip_attribution_rows(vm, feed_a_path, feed_b_path)
        _set_syslog_enabled(vm, on=True)
        h.set_update_hooks(vm, [h.env_dump_hook(token, "post")])
        h.force_ip_refetch(vm, feed_a_header)
        h.force_ip_refetch(vm, feed_b_header)
        h.clear_hook_markers(vm, token)
        h.reload(vm, "update")

        table = vm.ssh("/sbin/pfctl", "-t", alias, "-T", "show", timeout=30)
        assert table.returncode == 0, f"failed to read {alias}: rc={table.returncode} {table.stderr!r}"
        membership_before = {line.strip() for line in table.stdout.splitlines() if line.strip()}
        assert {TEST_IP_BLOCK_DST, control_ip} <= membership_before, (
            f"setup alias membership missing fixture hosts: expected {TEST_IP_BLOCK_DST!r} and "
            f"{control_ip!r}, got {sorted(membership_before)!r}"
        )

        # Missing-cache state: the first real event must recreate it naturally.
        vm.ssh("/bin/rm", "-f", IP_CACHE, timeout=30)
        assert _ip_cache_snapshot(vm) is None, "precondition: IP cache still exists after explicit removal"
        daemon_pid = _filterlog_pid(vm)

        events_before = len(_pfb_event_lines(vm))
        _trigger_ip_block(client_vm, port=18080)
        initial_syslog = _wait_for_event(
            vm,
            baseline_len=events_before,
            want=(TEST_IP_BLOCK_DST, "dport=18080"),
            any_of=IP_ACT_TOKENS,
        )
        assert f"feed={feed_a_header}" in initial_syslog, (
            f"initial event did not attribute {TEST_IP_BLOCK_DST} to FeedA {feed_a_header!r}: {initial_syslog!r}"
        )
        initial_csv = _last_log_line(vm, IP_BLOCK_LOG, TEST_IP_BLOCK_DST, ",18080,")
        initial_unified = _last_log_line(vm, UNIFIED_LOG, TEST_IP_BLOCK_DST, ",18080,")
        for label, line in (("IP CSV", initial_csv), ("unified", initial_unified)):
            assert feed_a_header in line and TEST_IP_BLOCK_DST in line, (
                f"initial {label} attribution should contain FeedA={feed_a_header!r} and "
                f"evaluated={TEST_IP_BLOCK_DST!r}, got {line!r}"
            )

        initial_cache = _ip_cache_snapshot(vm)
        assert initial_cache is not None, "first event did not recreate the missing IP cache"
        assert initial_cache[1].get(TEST_IP_BLOCK_DST) == (feed_a_header, TEST_IP_BLOCK_DST), (
            f"initial cached q0/q1 mismatch: {initial_cache!r}"
        )
        _seed_ip_cache_row(vm, sentinel_host, "SentinelFeed", f"{sentinel_host}/32")
        cached_before_noop = _ip_cache_snapshot(vm)
        assert cached_before_noop is not None and sentinel_host in cached_before_noop[1], (
            f"second host was not seeded into the shared cache: {cached_before_noop!r}"
        )

        # True reuse/no-op: both the inode and every row survive, and events still hit FeedA.
        h.clear_hook_markers(vm, token)
        h.reload(vm, "update")
        env_noop = h.read_hook_env(vm, marker)
        assert env_noop is not None, "post hook absent for no-op update"
        assert env_noop.get("PFB_IP_CHANGED") == "0" and env_noop.get("PFB_CHANGED_IP_ALIASES") == "", (
            f"expected a true no-op pass, got {env_noop!r}"
        )
        assert _ip_cache_snapshot(vm) == cached_before_noop, "no-op update changed the IP cache inode or rows"
        assert _filterlog_pid(vm) == daemon_pid, "no-op update restarted the filterlog daemon"

        events_before = len(_pfb_event_lines(vm))
        _trigger_ip_block(client_vm, port=18081)
        noop_syslog = _wait_for_event(
            vm,
            baseline_len=events_before,
            want=(TEST_IP_BLOCK_DST, "dport=18081"),
            any_of=IP_ACT_TOKENS,
        )
        assert f"feed={feed_a_header}" in noop_syslog, f"no-op cache hit lost FeedA attribution: {noop_syslog!r}"

        # Unlock-only re-block widens alias reloads, but must not invalidate attribution.
        unlock = h.php_eval(
            vm,
            f"file_put_contents('/tmp/ip_unlock', {h._php_str(TEST_IP_BLOCK_DST + ',' + alias + chr(10))}); echo 'OK';",
        )
        assert unlock.returncode == 0 and "OK" in unlock.stdout, (
            f"failed to create unlock fixture: rc={unlock.returncode} {unlock.stderr!r} {unlock.stdout!r}"
        )
        h.clear_hook_markers(vm, token)
        h.reload(vm, "update")
        env_unlock = h.read_hook_env(vm, marker)
        assert env_unlock is not None and env_unlock.get("PFB_IP_CHANGED") == "1", (
            f"unlock-only pass did not report its re-block: {env_unlock!r}"
        )
        assert _ip_cache_snapshot(vm) == cached_before_noop, "unlock-only re-block changed the IP cache"
        assert _filterlog_pid(vm) == daemon_pid, "unlock-only re-block restarted the filterlog daemon"

        events_before = len(_pfb_event_lines(vm))
        _trigger_ip_block(client_vm, port=18082)
        unlock_syslog = _wait_for_event(
            vm,
            baseline_len=events_before,
            want=(TEST_IP_BLOCK_DST, "dport=18082"),
            any_of=IP_ACT_TOKENS,
        )
        assert f"feed={feed_a_header}" in unlock_syslog, (
            f"unlock-only pass should retain cached FeedA attribution: {unlock_syslog!r}"
        )
        assert _ip_cache_snapshot(vm) == cached_before_noop, "cache-hit events changed the cached q0/q1 rows"

        # Genuine refetch: swap ownership while preserving the exact final alias union.
        h.write_local_feed(vm, "pfb_syslog_ip.txt", f"{control_range}\n")
        h.write_local_feed(vm, "pfb_syslog_ip_b.txt", f"{TEST_IP_BLOCK_RANGE}\n")
        h.force_ip_refetch(vm, feed_a_header)
        h.force_ip_refetch(vm, feed_b_header)
        h.clear_hook_markers(vm, token)
        h.reload(vm, "update")
        env_refresh = h.read_hook_env(vm, marker)
        assert env_refresh is not None, "post hook absent for ownership-change update"
        assert env_refresh.get("PFB_IP_CHANGED") == "0", (
            f"ownership-only feed move unexpectedly reloaded firewall rules: {env_refresh!r}"
        )
        assert env_refresh.get("PFB_CHANGED_IP_ALIASES") == "", (
            f"final alias union changed during ownership-only move: {env_refresh!r}"
        )
        assert _filterlog_pid(vm) == daemon_pid, "ownership-only content refresh restarted the filterlog daemon"

        table = vm.ssh("/sbin/pfctl", "-t", alias, "-T", "show", timeout=30)
        membership_after = {line.strip() for line in table.stdout.splitlines() if line.strip()}
        assert table.returncode == 0 and membership_after == membership_before, (
            f"ownership move changed pf enforcement: before={sorted(membership_before)!r} "
            f"after={sorted(membership_after)!r} rc={table.returncode}"
        )
        feed_a_output = h.read_log_file(vm, f"{h.PFB_DBDIR}/deny/{feed_a_header}.txt")
        feed_b_output = h.read_log_file(vm, f"{h.PFB_DBDIR}/deny/{feed_b_header}.txt")
        assert TEST_IP_BLOCK_DST not in feed_a_output and TEST_IP_BLOCK_DST in feed_b_output, (
            "refetched attribution sources did not move the host from FeedA to FeedB: "
            f"FeedA={feed_a_output!r} FeedB={feed_b_output!r}"
        )

        events_before = len(_pfb_event_lines(vm))
        _trigger_ip_block(client_vm, port=18083)
        refreshed_syslog = _wait_for_event(
            vm,
            baseline_len=events_before,
            want=(TEST_IP_BLOCK_DST, "dport=18083"),
            any_of=IP_ACT_TOKENS,
        )
        assert f"feed={feed_b_header}" in refreshed_syslog, (
            f"post-refresh event stayed stale instead of recomputing FeedB {feed_b_header!r}: "
            f"actual={refreshed_syslog!r} cached_before={cached_before_noop!r}"
        )
        assert f"feed={feed_a_header}" not in refreshed_syslog, (
            f"post-refresh syslog still contains removed FeedA attribution: {refreshed_syslog!r}"
        )

        refreshed_csv = _last_log_line(vm, IP_BLOCK_LOG, TEST_IP_BLOCK_DST, ",18083,")
        refreshed_unified = _last_log_line(vm, UNIFIED_LOG, TEST_IP_BLOCK_DST, ",18083,")
        for label, line in (("IP CSV", refreshed_csv), ("unified", refreshed_unified)):
            assert feed_b_header in line and TEST_IP_BLOCK_DST in line and feed_a_header not in line, (
                f"post-refresh {label} did not use recomputed FeedB/evaluated attribution: {line!r}"
            )
        assert initial_csv in h.read_log_file(vm, IP_BLOCK_LOG).splitlines(), (
            f"historical FeedA CSV row was rewritten or lost: {initial_csv!r}"
        )

        refreshed_cache = _ip_cache_snapshot(vm)
        assert refreshed_cache is not None, "post-refresh event did not recreate the IP cache"
        assert refreshed_cache[1].get(TEST_IP_BLOCK_DST) == (feed_b_header, TEST_IP_BLOCK_DST), (
            f"post-refresh cached q0/q1 mismatch: {refreshed_cache!r}"
        )
        assert sentinel_host not in refreshed_cache[1], (
            f"content refresh did not invalidate the whole shared cache: {refreshed_cache!r}"
        )
    finally:
        h.clear_update_hooks(vm)
        vm.ssh("/bin/rm", "-f", "/tmp/ip_unlock", timeout=30)
        h.write_local_feed(vm, "pfb_syslog_ip.txt", f"{TEST_IP_BLOCK_RANGE}\n")
        h.inject(
            vm,
            h.IpCase(
                aliasname="pfb_syslog_iptest",
                feed_url=feed_a_path,
                action="Deny_Outbound",
                family="v4",
                header="pfb_syslog_ip",
            ),
        )
        h.config_set(vm, CFG_GENERAL + "/log_syslog", original_syslog)
        h.force_ip_refetch(vm, feed_a_header)
        h.reload(vm, "update")
        vm.ssh(
            "/bin/rm",
            "-f",
            IP_CACHE,
            feed_b_path,
            f"{h.PFB_DBDIR}/deny/{feed_b_header}.txt",
            f"{h.PFB_DBDIR}/deny/{feed_b_header}.update",
            f"{h.PFB_DBDIR}/deny/{feed_b_header}.fail",
            timeout=30,
        )


# --------------------------------------------------------------------------- #
# Test 4: OFF ⇒ no new export records (LIVE toggle, before/after proof)
# --------------------------------------------------------------------------- #


def test_syslog_off_no_new_records(deployed_vm: SmokeVM, client_vm: SmokeVM) -> None:
    """ON seed → OFF subject/drain → ON barrier; OFF subject must stay absent."""
    vm = deployed_vm
    domain: str = vm._pfb_syslog_seed  # type: ignore[attr-defined]
    domain_off: str = vm._pfb_dnsbl_domain_on  # type: ignore[attr-defined]
    drain_domain: str = vm._pfb_syslog_drain  # type: ignore[attr-defined]
    barrier_domain: str = vm._pfb_syslog_barrier  # type: ignore[attr-defined]
    civm_ip: str = vm._pfb_civm_ip  # type: ignore[attr-defined]

    # Seed our own ON record (#1396): enable LIVE, probe, and prove ONE exported event —
    # the before-state for the OFF flip is created here, never inherited from a sibling.
    seed_baseline = len(_pfb_event_lines(vm))
    _set_syslog_enabled(vm, on=True)
    h.flush_unbound_name(vm, domain)
    ans = h.dns_probe_client(client_vm, domain, "A")
    assert h.is_vip(ans), f"DNSBL block should fire while seeding the ON record, got {ans}"
    _wait_for_event(vm, baseline_len=seed_baseline, want=("act=dnsbl", f"qname={domain}", f"qip={civm_ip}"))
    unified_baseline = len(_unified_dnsbl_lines(vm))
    dnsbl_csv_before = h.count_log_marker(vm, DNSBL_LOG, domain_off)

    # When: disable LIVE (no restart) + probe a distinct subject, then consume its unified row.
    _set_syslog_enabled(vm, on=False)
    h.flush_unbound_name(vm, domain_off)
    ans = h.dns_probe_client(client_vm, domain_off, "A")
    assert h.is_vip(ans), f"DNSBL block should still work when syslog is OFF, got {ans}"
    drain_dnsbl_before = h.count_log_marker(vm, DNSBL_LOG, drain_domain)
    h.flush_unbound_name(vm, drain_domain)
    drain_answer = h.dns_probe_client(client_vm, drain_domain, "A")
    assert h.is_vip(drain_answer), f"DNSBL OFF-state drain should be VIP, got {drain_answer}"
    _wait_for_unified_dnsbl(
        vm,
        drain_domain,
        baseline_len=unified_baseline,
        dnsbl_baseline=drain_dnsbl_before,
    )

    # And: CSV still written in the OFF state (additive path independent of the toggle).
    dnsbl_csv_after = h.count_log_marker(vm, DNSBL_LOG, domain_off)
    assert dnsbl_csv_after > dnsbl_csv_before, (
        f"CSV dnsbl.log was NOT written while syslog export is OFF (before {dnsbl_csv_before}, "
        f"after {dnsbl_csv_after}) — the CSV path must be independent of the syslog toggle"
    )

    # Re-enable and consume a third configured barrier export before asserting the OFF subject absence.
    _set_syslog_enabled(vm, on=True)
    barrier_baseline = len(_pfb_event_lines(vm))
    h.flush_unbound_name(vm, barrier_domain)
    barrier_answer = h.dns_probe_client(client_vm, barrier_domain, "A")
    assert h.is_vip(barrier_answer), f"DNSBL barrier should be VIP after re-enabling syslog, got {barrier_answer}"
    _wait_for_event(vm, baseline_len=barrier_baseline, want=("act=dnsbl", f"qname={barrier_domain}", f"qip={civm_ip}"))

    # This qname is unique to the module and queried only while export is OFF.
    # Search rotations too so newsyslog cannot erase the negative evidence.
    phase_lines = _pfb_event_history_lines(vm)
    assert any(f"qname={barrier_domain}" in event and f"qip={civm_ip}" in event for event in phase_lines), (
        f"dedicated syslog history missing already-observed barrier {barrier_domain}: {phase_lines!r}"
    )
    assert not any(f"qname={domain_off}" in event for event in phase_lines), (
        f"OFF-phase subject {domain_off} appeared in syslog after its unified row was consumed: "
        f"{phase_lines!r}\n{syslog_export_state_snapshot(vm)}"
    )
