#!/usr/bin/env python3
"""update_public_suffix_list.py -- refresh dnsbl_tld from the Public Suffix List.

src/usr/local/pkg/pfblockerng/dnsbl_tld is the flat, one-suffix-per-line master list
tld_analysis() (PHP) / _dnsbl_load_tld_wildcard_master() (Python) key registrable domains
against. This script refreshes it from the authoritative upstream source, ICANN
section only -- the PRIVATE section (blogspot.*, github.io, ...) and PSL wildcard
('*.') / exception ('!') lines are intentionally dropped (issue #1272): the
consumers want a plain public-suffix oracle, and neither format extension nor
private-registry entries are part of that contract.

Data source
-----------
https://publicsuffix.org/list/public_suffix_list.dat -- the ICANN section runs
between the '// ===BEGIN ICANN DOMAINS===' / '// ===END ICANN DOMAINS===' marker
lines; everything outside those markers (comments, PRIVATE section) is ignored.

Conversion
----------
Every non-ASCII label is punycode-encoded via the stdlib 'idna' codec (per-label,
so a mixed ascii+unicode suffix only converts its unicode label(s)); an
already-ASCII label (including 'xn--' punycode) passes through verbatim -- the
conversion is therefore idempotent. Labels are lowercased defensively (DNS is
case-insensitive). A malformed line (internal whitespace after stripping -- PSL
never ships one) is skipped rather than emitted.

Output format
-------------
A '#'-prefixed header (source URL + the upstream VERSION/COMMIT comment values,
or 'unknown' if either is absent) followed by one suffix per line, in PSL source
order (the file is NOT sorted). Both consumers already skip '' and '#'-prefixed
lines (see pfblockerng.inc's tld_analysis() / pfb_unbound.py's
_dnsbl_load_tld_wildcard_master()), so the header rides through harmlessly end-to-end.

Churn guard: the header's VERSION timestamp moves on every upstream commit even
when no suffix actually changed, so a plain run compares the GENERATED BODY
(non-'#' lines) against the existing file's body -- identical bodies leave the
file untouched (no weekly header-only diff); a real body change rewrites the
whole file (header + body).

Usage
-----
    python scripts/misc/update_public_suffix_list.py           # rewrite the file in place
    python scripts/misc/update_public_suffix_list.py --check   # exit 1 if out of date, no changes

Dev-host tooling: run from the repo root on a dev box (never the appliance).
"""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

PSL_URL = "https://publicsuffix.org/list/public_suffix_list.dat"

BEGIN_MARKER = "// ===BEGIN ICANN DOMAINS==="
END_MARKER = "// ===END ICANN DOMAINS==="

# Plausibility floor: the live ICANN section holds ~6,900 suffixes. A fetch that
# returns far fewer (an empty-but-200 body, a captive-portal/proxy interstitial, a
# truncated response) must NEVER overwrite dnsbl_tld -- a blanked/truncated master
# list silently breaks every TLD-Allow lookup. Refuse below this floor instead.
MIN_PLAUSIBLE_SUFFIXES = 5000

DEFAULT_TLD_FILE = Path(__file__).resolve().parent.parent.parent / "src/usr/local/pkg/pfblockerng/dnsbl_tld"

HEADER_TEMPLATE = (
    "# Public Suffix List (ICANN section only) - https://publicsuffix.org/list/public_suffix_list.dat\n"
    "# VERSION: {version}\n"
    "# COMMIT: {commit}\n"
    "# Regenerated by scripts/misc/update_public_suffix_list.py - do not edit by hand.\n"
)


# ── Pure logic (unit-tested, no network) ───────────────────────────────────


def normalise_lines(text: str) -> list[str]:
    """Split into lines (any newline convention), stripping surrounding whitespace."""
    return [line.strip() for line in text.splitlines()]


def extract_header(lines: list[str]) -> tuple[str, str]:
    """Pull the upstream VERSION/COMMIT comment values; 'unknown' if either is absent."""
    version = "unknown"
    commit = "unknown"
    for line in lines:
        if line.startswith("// VERSION:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("// COMMIT:"):
            commit = line.split(":", 1)[1].strip()
    return version, commit


def extract_icann_lines(lines: list[str]) -> list[str]:
    """Return the raw lines strictly between the ICANN BEGIN/END markers.

    Raises SystemExit if either marker is missing -- a captive-portal/HTML page or a
    truncated fetch must never be silently treated as an empty ICANN section.
    """
    try:
        begin = lines.index(BEGIN_MARKER)
    except ValueError:
        raise SystemExit(f"Refusing to rewrite: '{BEGIN_MARKER}' marker not found in the fetched PSL.") from None
    try:
        end = lines.index(END_MARKER, begin + 1)
    except ValueError:
        raise SystemExit(f"Refusing to rewrite: '{END_MARKER}' marker not found (truncated fetch?).") from None
    return lines[begin + 1 : end]


def _punycode_label(label: str) -> str:
    """Punycode-encode a label iff it holds non-ASCII; an ASCII label (including an
    already-punycode 'xn--' one) passes through verbatim -- makes conversion idempotent."""
    if label.isascii():
        return label.lower()
    return label.encode("idna").decode("ascii").lower()


def convert_suffix(line: str) -> str | None:
    """Convert one ICANN-section PSL line to a dnsbl_tld suffix, or None to skip it.

    Skips blank lines, '//' comments, '*.' wildcard rules, and '!' exception rules
    (owner decision, issue #1272 -- no parser/format extension for either), plus any
    malformed line carrying internal whitespace or a label the idna codec rejects
    (past the 63-octet DNS cap) -- PSL never ships either. A dot-less bare TLD
    passes through unchanged (issue #1068: consumers key it under its own full
    value).
    """
    if not line or line.startswith("//") or line.startswith("*.") or line.startswith("!"):
        return None
    if any(c.isspace() for c in line):
        return None
    try:
        return ".".join(_punycode_label(label) for label in line.split("."))
    except UnicodeError:
        # idna refuses a label past the 63-octet DNS cap -- malformed, skip it.
        return None


def build_body(icann_lines: list[str]) -> list[str]:
    """Convert every ICANN-section line to its dnsbl_tld suffix, dropping skips."""
    return [suffix for line in icann_lines if (suffix := convert_suffix(line)) is not None]


def require_plausible(body: list[str]) -> None:
    """Refuse to proceed if the parsed ICANN suffix count is implausibly small."""
    if len(body) < MIN_PLAUSIBLE_SUFFIXES:
        raise SystemExit(
            f"Refusing to rewrite: parsed only {len(body)} ICANN suffixes "
            f"(< {MIN_PLAUSIBLE_SUFFIXES}); a truncated/empty response must not overwrite dnsbl_tld."
        )


def existing_body(text: str) -> list[str]:
    """Non-'#' lines of an existing dnsbl_tld file -- the churn-guard comparison basis."""
    return [line for line in text.splitlines() if not line.startswith("#")]


def render_output(version: str, commit: str, body: list[str]) -> str:
    """Render the full dnsbl_tld file content: header then one suffix per line."""
    return HEADER_TEMPLATE.format(version=version, commit=commit) + "\n".join(body) + "\n"


# ── Network (excluded from unit tests) ─────────────────────────────────────


def fetch_psl(timeout: float = 15) -> str:
    """Fetch the live Public Suffix List."""
    with urllib.request.urlopen(PSL_URL, timeout=timeout) as resp:  # noqa: S310 (fixed https host)
        return resp.read().decode("utf-8")


# ── CLI ─────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if dnsbl_tld is out of date vs a fresh PSL fetch; changes nothing",
    )
    args = parser.parse_args(argv)

    lines = normalise_lines(fetch_psl())
    version, commit = extract_header(lines)
    body = build_body(extract_icann_lines(lines))
    require_plausible(body)

    old_text = DEFAULT_TLD_FILE.read_text(encoding="utf-8") if DEFAULT_TLD_FILE.exists() else ""
    if existing_body(old_text) == body:
        print("dnsbl_tld is up to date (body unchanged).")
        return 0

    if args.check:
        print(f"dnsbl_tld is OUT OF DATE ({len(body)} ICANN suffixes vs {len(existing_body(old_text))} shipped).")
        return 1

    DEFAULT_TLD_FILE.write_text(render_output(version, commit, body), encoding="utf-8")
    print(f"dnsbl_tld regenerated: {len(body)} ICANN suffixes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
