#!/usr/bin/env python3
"""update_hsts_preload_list.py -- refresh pfb_py_hsts.txt from the Chromium HSTS
preload list.

src/usr/local/pkg/pfblockerng/pfb_py_hsts.txt is the flat, one-name-per-line HSTS
exclusion oracle _load_hsts_db() (pfb_unbound.py) keys resolved domains against: a
blocked domain on this list resolves real (HSTS bypass) instead of being
null-blocked. This script refreshes it from Chromium's own preload source.

Data source
-----------
https://chromium.googlesource.com/chromium/src/+/main/net/http/transport_security_state_static.json
-- gitiles serves it base64-encoded via '?format=TEXT'. The decoded body is
JSON with '//'-prefixed comment lines (not valid JSON on its own -- those lines
are stripped before parsing). License: BSD-style, The Chromium Authors --
https://chromium.googlesource.com/chromium/src/+/main/LICENSE (redistribution
with attribution permitted; both URLs are carried in the output header).

Extraction
----------
Only entries with 'mode' == 'force-https' are kept -- 'entries' historically
also holds pinning-only rows with no 'mode'. 'include_subdomains' is ignored:
the consumer (_load_hsts_db()'s parent-suffix walk over hstsDB) already matches
subdomains for every listed name, so no expansion is needed here.

Conversion
----------
Mirrors update_public_suffix_list.py: every non-ASCII label is punycode-encoded
via the stdlib 'idna' codec (per-label); an already-ASCII label passes through
verbatim (idempotent). Names are lowercased. A malformed name (whitespace
anywhere) or one whose idna encoding fails (a label past the 63-octet DNS cap)
is skipped rather than emitted.

Output format
-------------
A '#'-prefixed header (source + license URLs, a SYNCED date, a regenerated-by
note) followed by one name per line, sorted (LC-C) and deduplicated. Both
loader sites in pfb_unbound.py already skip '' and '#'-prefixed lines, so the
header rides through harmlessly.

Churn guard: upstream carries no retrievable revision marker for this file, so
the header's SYNCED date is written ONLY when the parsed BODY (non-'#' lines)
actually changes vs the existing file -- a plain run compares bodies first;
identical bodies leave the file untouched (no run-to-run header-only diff).

Usage
-----
    python scripts/misc/update_hsts_preload_list.py           # rewrite the file in place
    python scripts/misc/update_hsts_preload_list.py --check   # exit 1 if out of date, no changes

Dev-host tooling: run from the repo root on a dev box (never the appliance).
"""

from __future__ import annotations

import argparse
import base64
import binascii
import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

SOURCE_URL = "https://chromium.googlesource.com/chromium/src/+/main/net/http/transport_security_state_static.json"
LICENSE_URL = "https://chromium.googlesource.com/chromium/src/+/main/LICENSE"
FETCH_URL = SOURCE_URL + "?format=TEXT"

# Plausibility floor: the live force-https set holds ~94,256 names (2026-07-13). A
# fetch that returns far fewer (an empty-but-200 body, a captive-portal/proxy
# interstitial, a truncated response) must NEVER overwrite pfb_py_hsts.txt --
# refuse below this floor instead.
MIN_PLAUSIBLE_ENTRIES = 50000

DEFAULT_HSTS_FILE = Path(__file__).resolve().parent.parent.parent / "src/usr/local/pkg/pfblockerng/pfb_py_hsts.txt"

HEADER_TEMPLATE = (
    f"# HSTS preload list (force-https entries) - {SOURCE_URL}\n"
    f"# License: BSD-style, The Chromium Authors - {LICENSE_URL}\n"
    "# SYNCED: {synced}\n"
    "# Regenerated by scripts/misc/update_hsts_preload_list.py - do not edit by hand.\n"
)


# ── Pure logic (unit-tested, no network) ───────────────────────────────────


def strip_json_comments(text: str) -> str:
    """Drop every '//'-prefixed comment line -- this JSON-with-comments file
    isn't valid JSON until they're removed."""
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("//"))


def parse_entries(text: str) -> list[dict[str, object]]:
    """Parse the comment-stripped body and return the raw 'entries' list.

    Raises SystemExit if the body isn't valid JSON, or has no 'entries' key --
    a captive-portal/HTML page or a truncated fetch must never be silently
    treated as an empty entry list.
    """
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise SystemExit(f"Refusing to rewrite: fetched body is not valid JSON after comment-stripping: {e}") from None
    if not isinstance(data, dict) or "entries" not in data:
        raise SystemExit("Refusing to rewrite: fetched JSON has no 'entries' key.")
    entries = data["entries"]
    if not isinstance(entries, list) or not all(isinstance(e, dict) for e in entries):
        raise SystemExit("Refusing to rewrite: 'entries' is not a list of objects (upstream schema changed?).")
    return entries


def extract_names(entries: list[dict[str, object]]) -> list[str]:
    """Raw names of force-https entries only (pinning-only rows have no 'mode').

    A force-https row without a string 'name' means the upstream schema moved --
    refuse loudly rather than crash with a KeyError.
    """
    names = []
    for e in entries:
        if e.get("mode") != "force-https":
            continue
        name = e.get("name")
        if not isinstance(name, str):
            raise SystemExit(f"Refusing to rewrite: force-https entry without a string 'name': {e!r:.100}")
        names.append(name)
    return names


def _punycode_label(label: str) -> str:
    """Punycode-encode a label iff it holds non-ASCII; an ASCII label (including an
    already-punycode 'xn--' one) passes through verbatim -- makes conversion idempotent."""
    if label.isascii():
        return label.lower()
    return label.encode("idna").decode("ascii").lower()


def normalise_name(name: str) -> str | None:
    """Convert one HSTS entry name to its stored form, or None to skip it.

    Skips a name carrying whitespace anywhere (leading/trailing/internal --
    Chromium never ships one) and a label the idna codec rejects (past the
    63-octet DNS cap).
    """
    if not name or any(c.isspace() for c in name):
        return None
    try:
        return ".".join(_punycode_label(label) for label in name.split("."))
    except UnicodeError:
        # idna refuses a label past the 63-octet DNS cap -- malformed, skip it.
        return None


def build_body(entries: list[dict[str, object]]) -> list[str]:
    """Normalise every force-https entry name; sort LC-C, dedupe.

    include_subdomains is ignored -- _load_hsts_db()'s parent-suffix walk
    already matches subdomains for every listed name.
    """
    names = {n for name in extract_names(entries) if (n := normalise_name(name)) is not None}
    return sorted(names)


def require_plausible(body: list[str]) -> None:
    """Refuse to proceed if the parsed force-https entry count is implausibly small."""
    if len(body) < MIN_PLAUSIBLE_ENTRIES:
        raise SystemExit(
            f"Refusing to rewrite: parsed only {len(body)} force-https entries "
            f"(< {MIN_PLAUSIBLE_ENTRIES}); a truncated/empty response must not overwrite pfb_py_hsts.txt."
        )


def existing_body(text: str) -> list[str]:
    """Non-'#' lines of an existing pfb_py_hsts.txt file -- the churn-guard comparison basis."""
    return [line for line in text.splitlines() if not line.startswith("#")]


def render_output(synced: str, body: list[str]) -> str:
    """Render the full pfb_py_hsts.txt file content: header then one name per line."""
    return HEADER_TEMPLATE.format(synced=synced) + "\n".join(body) + "\n"


# ── Network (excluded from unit tests) ─────────────────────────────────────


def fetch_hsts_json(timeout: float = 15) -> str:
    """Fetch the live gitiles base64 payload."""
    with urllib.request.urlopen(FETCH_URL, timeout=timeout) as resp:  # noqa: S310 (fixed https host)
        return resp.read().decode("ascii")


def decode_body(raw_b64: str) -> str:
    """Base64-decode the gitiles '?format=TEXT' payload, then UTF-8 decode.

    validate=False matches gitiles' actual encoding (permissive: any embedded
    whitespace/newlines are simply discarded before decoding).
    """
    try:
        return base64.b64decode(raw_b64).decode("utf-8")
    except (binascii.Error, UnicodeDecodeError) as e:
        raise SystemExit(f"Refusing to rewrite: fetched body failed base64/utf-8 decode: {e}") from None


# ── CLI ─────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if pfb_py_hsts.txt is out of date vs a fresh fetch; changes nothing",
    )
    args = parser.parse_args(argv)

    text = decode_body(fetch_hsts_json())
    entries = parse_entries(strip_json_comments(text))
    body = build_body(entries)
    require_plausible(body)

    old_text = DEFAULT_HSTS_FILE.read_text(encoding="utf-8") if DEFAULT_HSTS_FILE.exists() else ""
    if existing_body(old_text) == body:
        print("pfb_py_hsts.txt is up to date (body unchanged).")
        return 0

    if args.check:
        print(
            f"pfb_py_hsts.txt is OUT OF DATE "
            f"({len(body)} force-https entries vs {len(existing_body(old_text))} shipped)."
        )
        return 1

    synced = datetime.now(timezone.utc).date().isoformat()
    DEFAULT_HSTS_FILE.write_text(render_output(synced, body), encoding="utf-8")
    print(f"pfb_py_hsts.txt regenerated: {len(body)} force-https entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
