#!/usr/bin/env python3
"""update_public_suffix_list.py -- refresh dnsbl_psl from the Public Suffix List.

src/usr/local/pkg/pfblockerng/dnsbl_psl is the SOLE shipped PSL artifact (issue
#1541): a self-describing authority carrying both the ICANN and PRIVATE
sections, with exact, wildcard ('*.') and exception ('!') rule syntax intact.
It is consumed by the pure PSL resolver (pfb_unbound.py's parse_psl_rules) to
derive each domain's registrable parent for DNSBL Wildcard Blocking. This
script refreshes it from the authoritative upstream source.

Data source
-----------
https://publicsuffix.org/list/public_suffix_list.dat -- the ICANN section runs
between the '// ===BEGIN ICANN DOMAINS===' / '// ===END ICANN DOMAINS==='
marker lines, and the PRIVATE section between the matching PRIVATE markers;
comments outside those markers are ignored.

Conversion
----------
Every non-ASCII label is punycode-encoded via the stdlib 'idna' codec (per-label,
so a mixed ascii+unicode suffix only converts its unicode label(s)); an
already-ASCII label (including 'xn--' punycode) passes through verbatim -- the
conversion is therefore idempotent. Labels are lowercased defensively (DNS is
case-insensitive). A malformed line is skipped rather than emitted: internal
whitespace, an RFC 3454 Table B.1 "commonly mapped to nothing" character
(zero-width space, BOM, variation selectors, ...) after stripping, a category-Cc
control character (NUL, DEL, ...), a category-Cn (unassigned) codepoint, or any
label past the 63-octet DNS cap, ASCII or not -- PSL never ships any of these.
A non-comment line that is not valid PSL rule syntax (malformed wildcard/
exception marker, stray metacharacter, ...) raises instead of being silently
skipped -- a malformed fetch must never be published.

Output format
-------------
A '#'-prefixed header (source URL + the upstream VERSION/COMMIT comment values,
or 'unknown' if either is absent) followed by the normalized ICANN section
between its BEGIN/END markers and the normalized PRIVATE section between its
own markers, each preserving exact, wildcard, and exception rule syntax.

Churn guard: the header's VERSION timestamp moves on every upstream commit even
when no suffix actually changed, so a plain run compares the GENERATED BODY
(non-'#', non-blank lines) against the existing file's body -- an identical
body leaves the file untouched (no weekly header-only diff); a real body
change rewrites the whole file (header + body).

Usage
-----
    python scripts/misc/update_public_suffix_list.py           # rewrite the file in place
    python scripts/misc/update_public_suffix_list.py --check   # exit 1 if out of date, no changes

Dev-host tooling: run from the repo root on a dev box (never the appliance).
"""

from __future__ import annotations

import argparse
import os
import stringprep
import sys
import tempfile
import unicodedata
import urllib.request
from pathlib import Path

PSL_URL = "https://publicsuffix.org/list/public_suffix_list.dat"

BEGIN_MARKER = "// ===BEGIN ICANN DOMAINS==="
END_MARKER = "// ===END ICANN DOMAINS==="
PRIVATE_BEGIN_MARKER = "// ===BEGIN PRIVATE DOMAINS==="
PRIVATE_END_MARKER = "// ===END PRIVATE DOMAINS==="

# Plausibility floors: the live ICANN section holds ~6,900 rules and the PRIVATE
# section several thousand more. A fetch that returns far fewer (an
# empty-but-200 body, a captive-portal/proxy interstitial, a truncated
# response) must NEVER overwrite dnsbl_psl -- a blanked/truncated authority
# silently breaks every DNSBL Wildcard Blocking lookup. Refuse below these
# floors instead.
MIN_PLAUSIBLE_SUFFIXES = 5000
MIN_PLAUSIBLE_PRIVATE_SUFFIXES = 1000

DEFAULT_PSL_FILE = Path(__file__).resolve().parent.parent.parent / "src/usr/local/pkg/pfblockerng/dnsbl_psl"

HEADER_TEMPLATE = (
    "# Public Suffix List (ICANN and PRIVATE sections) - https://publicsuffix.org/list/public_suffix_list.dat\n"
    "# VERSION: {version}\n"
    "# COMMIT: {commit}\n"
    "# Regenerated by scripts/misc/update_public_suffix_list.py - do not edit by hand.\n"
)


# ── Pure logic (unit-tested, no network) ───────────────────────────────────


def normalise_lines(text: str) -> list[str]:
    """Split into lines (any newline convention), stripping surrounding whitespace."""
    return [line.strip() for line in text.splitlines()]


def extract_header(lines: list[str]) -> tuple[str, str]:
    """Pull the upstream VERSION/COMMIT comment values; 'unknown' if either is absent."""
    version = "unknown"
    commit = "unknown"
    for line in lines:
        if line.startswith("// VERSION:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("// COMMIT:"):
            commit = line.split(":", 1)[1].strip()
    return version, commit


def extract_psl_sections(lines: list[str]) -> tuple[list[str], list[str]]:
    """Return ICANN and PRIVATE rule lines, requiring the four PSL markers."""
    markers = (BEGIN_MARKER, END_MARKER, PRIVATE_BEGIN_MARKER, PRIVATE_END_MARKER)
    positions: list[int] = []
    for marker in markers:
        found = [index for index, line in enumerate(lines) if line == marker]
        if len(found) != 1:
            raise SystemExit(f"Refusing to rewrite: expected exactly one '{marker}' marker.")
        positions.append(found[0])
    begin, end, private_begin, private_end = positions
    if not begin < end < private_begin < private_end:
        raise SystemExit("Refusing to rewrite: PSL section markers are out of order.")
    return lines[begin + 1 : end], lines[private_begin + 1 : private_end]


def _has_blank_or_ignorable_char(text: str) -> bool:
    """True if text carries a blank (str.isspace()), an RFC 3454 Table B.1
    "commonly mapped to nothing" character (zero-width space, BOM, word joiner,
    variation selectors, ...) -- the exact predicate the stdlib idna codec's
    nameprep step uses internally (stringprep.in_table_b1) to silently strip these
    before punycode-encoding a label -- a category-Cc control character (NUL,
    DEL, ...): an ASCII-range Cc char takes the isascii() passthrough branch in
    _punycode_label untouched, so it would otherwise be emitted verbatim instead
    of being skipped (issue #1455) -- or a category-Cn (unassigned) codepoint: the
    idna codec accepts one without error and silently punycode-encodes it (issue
    #1463; probed: U+0378 encodes cleanly). category(c) == "Cn" tracks the
    interpreter's own (live) Unicode data, so it rejects only codepoints
    unassigned as of THIS run; the alternative, stringprep.in_table_a1, is frozen
    to the Unicode 3.2 baseline and would reject every codepoint assigned since
    (e.g. U+0526, U+08A0) -- a massive false-positive class, so it was rejected
    for this guard. A category-'Cf'-only check misses several Table B.1 members
    that are category Mn/Pd (issue #1306 follow-up), letting idna's encoder
    silently coalesce them away instead of the line being skipped."""
    return any(c.isspace() or stringprep.in_table_b1(c) or unicodedata.category(c) in ("Cc", "Cn") for c in text)


def _punycode_label(label: str) -> str:
    """Punycode-encode a label iff it holds non-ASCII; an ASCII label (including an
    already-punycode 'xn--' one) passes through verbatim -- makes conversion idempotent.

    Raises UnicodeError for either shape past the 63-octet DNS label cap, so both
    paths are skipped identically by the caller's 'except UnicodeError' (issue #1306:
    an ASCII label used to bypass the cap entirely via the isascii() short-circuit).
    """
    if not label:
        raise UnicodeError("empty DNS label")
    if label.isascii():
        converted = label.lower()
    else:
        converted = label.encode("idna").decode("ascii").lower()
    if converted.startswith("xn--"):
        canonical = converted.encode("ascii").decode("idna").encode("idna").decode("ascii").lower()
        if canonical != converted:
            raise UnicodeError(f"non-canonical IDNA label: {label!r}")
    if len(converted) > 63:
        raise UnicodeError(f"DNS label exceeds the 63-octet cap: {len(converted)} octets")
    if (
        converted[0] == "-"
        or converted[-1] == "-"
        or any(char not in "abcdefghijklmnopqrstuvwxyz0123456789-" for char in converted)
    ):
        raise UnicodeError(f"invalid DNS label: {label!r}")
    return converted


def convert_suffix(line: str) -> str | None:
    """Convert one PSL rule TOKEN (no '*.'/'!' prefix -- see convert_psl_rule) to
    its normalized DNS suffix form, or None to skip it.

    Skips blank lines and '//' comments, plus any malformed line carrying
    whitespace/ignorable characters (see _has_blank_or_ignorable_char) or a label
    the idna codec rejects (past the 63-octet DNS cap, ASCII or not -- issue
    #1306) -- PSL never ships either. A dot-less bare TLD passes through
    unchanged (issue #1068: consumers key it under its own full value).
    """
    if not line or line.startswith("//") or line.startswith("*.") or line.startswith("!"):
        return None
    if _has_blank_or_ignorable_char(line):
        return None
    try:
        converted = ".".join(_punycode_label(label) for label in line.split("."))
        if len(converted.encode("ascii")) > 253:
            raise UnicodeError("DNS name exceeds the 253-octet cap")
        return converted
    except UnicodeError:
        # idna (or our own length check) refuses a label past the 63-octet DNS cap --
        # malformed, skip it.
        return None


def convert_psl_rule(line: str) -> str | None:
    """Normalize one PSL exact, wildcard, or exception rule.

    Blank/comment lines are ignored. Per the PSL spec (and matching the runtime
    parser), the rule is the token up to the first whitespace -- the remainder
    is ignored. A malformed token raises ``ValueError`` so a malformed fetch
    cannot be published.
    """
    line = line.strip()
    if not line or line.startswith("//"):
        return None
    token = line.split(None, 1)[0]
    prefix = ""
    if token[:1] in ("*", "!"):
        prefix, token = token[0], token[1:]
    if prefix == "*":
        if not token.startswith("."):
            raise ValueError(f"malformed wildcard rule: {line!r}")
        token = token[1:]
    elif token.startswith("."):
        raise ValueError(f"malformed PSL rule: {line!r}")
    if not token or any(char in token for char in "!*"):
        raise ValueError(f"malformed PSL rule: {line!r}")
    converted = convert_suffix(token)
    if converted is None:
        raise ValueError(f"malformed PSL rule: {line!r}")
    return prefix + ("." if prefix == "*" else "") + converted


def build_psl_section(lines: list[str]) -> list[str]:
    """Normalize PSL rules while retaining exact, wildcard, and exception syntax."""
    rules = [rule for line in lines if (rule := convert_psl_rule(line)) is not None]
    wildcard_families = {rule[2:] for rule in rules if rule.startswith("*.")}
    for rule in rules:
        if rule.startswith("!"):
            labels = rule[1:].split(".")
            if len(labels) < 2 or ".".join(labels[1:]) not in wildcard_families:
                raise ValueError(f"orphan PSL exception without wildcard family: {rule!r}")
    return rules


def require_plausible(body: list[str]) -> None:
    """Refuse to proceed if the parsed ICANN rule count is implausibly small."""
    if len(body) < MIN_PLAUSIBLE_SUFFIXES:
        raise SystemExit(
            f"Refusing to rewrite: parsed only {len(body)} ICANN rules "
            f"(< {MIN_PLAUSIBLE_SUFFIXES}); a truncated/empty response must not overwrite dnsbl_psl."
        )


def require_private_plausible(body: list[str]) -> None:
    if len(body) < MIN_PLAUSIBLE_PRIVATE_SUFFIXES:
        raise SystemExit(
            f"Refusing to rewrite: parsed only {len(body)} PRIVATE suffixes "
            f"(< {MIN_PLAUSIBLE_PRIVATE_SUFFIXES}); a truncated/empty response must not overwrite dnsbl_psl."
        )


def render_psl_output(version: str, commit: str, icann: list[str], private: list[str]) -> str:
    """Render the self-describing authority consumed by the pure PSL resolver."""
    header = HEADER_TEMPLATE.format(version=version, commit=commit)
    return (
        header
        + BEGIN_MARKER
        + "\n"
        + "\n".join(icann)
        + "\n"
        + END_MARKER
        + "\n"
        + PRIVATE_BEGIN_MARKER
        + "\n"
        + "\n".join(private)
        + "\n"
        + PRIVATE_END_MARKER
        + "\n"
    )


def existing_psl_body(text: str) -> list[str]:
    """Return authority body lines, excluding generated comments."""
    return [line for line in text.splitlines() if line and not line.startswith("#")]


# ── Network (excluded from unit tests) ─────────────────────────────────────


def fetch_psl(timeout: float = 15) -> str:
    """Fetch the live Public Suffix List."""
    with urllib.request.urlopen(PSL_URL, timeout=timeout) as resp:  # noqa: S310 (fixed https host)
        return resp.read().decode("utf-8")


# ── CLI ─────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if dnsbl_psl is out of date; changes nothing",
    )
    args = parser.parse_args(argv)

    try:
        fetched = fetch_psl()
    except UnicodeDecodeError as exc:
        raise SystemExit(f"Refusing to rewrite: fetched PSL is not valid UTF-8 ({exc}).") from exc
    lines = normalise_lines(fetched)
    version, commit = extract_header(lines)
    icann_lines, private_lines = extract_psl_sections(lines)
    try:
        psl_icann = build_psl_section(icann_lines)
        psl_private = build_psl_section(private_lines)
    except ValueError as exc:
        raise SystemExit(f"Refusing to rewrite: malformed PSL rule in the fetched list ({exc}).") from exc
    require_plausible(psl_icann)
    require_private_plausible(psl_private)

    old_psl = DEFAULT_PSL_FILE.read_text(encoding="utf-8") if DEFAULT_PSL_FILE.exists() else ""
    authority_body = (
        [BEGIN_MARKER] + psl_icann + [END_MARKER, PRIVATE_BEGIN_MARKER] + psl_private + [PRIVATE_END_MARKER]
    )
    psl_changed = existing_psl_body(old_psl) != authority_body
    if args.check:
        if psl_changed:
            print(f"dnsbl_psl is OUT OF DATE ({len(psl_icann)} ICANN/{len(psl_private)} PRIVATE rules).")
        else:
            print("dnsbl_psl is up to date (body unchanged).")
        return 1 if psl_changed else 0

    if psl_changed:
        _atomic_write(DEFAULT_PSL_FILE, render_psl_output(version, commit, psl_icann, psl_private))
        print(f"dnsbl_psl regenerated: {len(psl_icann)} ICANN/{len(psl_private)} PRIVATE rules.")
    else:
        print("dnsbl_psl is up to date (body unchanged).")
    return 0


def _atomic_write(path: Path, text: str) -> None:
    """Publish one generated file through a same-directory flushed replacement."""
    temporary: str | None = None
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as handle:
            temporary = handle.name
            os.fchmod(handle.fileno(), mode)
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        if temporary is not None:
            try:
                os.unlink(temporary)
            except FileNotFoundError:
                pass
        raise


if __name__ == "__main__":
    sys.exit(main())
