<?php
/**
 * pfSense certs stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   certs.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function ca_chain_array(& $cert) {}

/** @return mixed */
function ca_chain(& $cert) {}

/** @return mixed */
function ca_import(& $ca, $str, $key = "", $serial = "") {}

/** @return mixed */
function ca_create(& $ca, $keylen, $lifetime, $dn, $digest_alg = "sha256", $keytype = "RSA", $ecname = "prime256v1") {}

/** @return mixed */
function ca_inter_create(& $ca, $keylen, $lifetime, $dn, $caref, $digest_alg = "sha256", $keytype = "RSA", $ecname = "prime256v1") {}

/** @return mixed */
function cert_import(& $cert, $crt_str, $key_str) {}

/** @return mixed */
function cert_create(& $cert, $caref, $keylen, $lifetime, $dn, $type = "user", $digest_alg = "sha256", $keytype = "RSA", $ecname = "prime256v1") {}

/** @return mixed */
function csr_generate(& $cert, $keylen, $dn, $type = "user", $digest_alg = "sha256", $keytype = "RSA", $ecname = "prime256v1") {}

/** @return mixed */
function csr_sign($csr, & $ca, $duration, $type, $altnames, $digest_alg = "sha256") {}

/** @return mixed */
function csr_complete(& $cert, $str_crt) {}

/** @return mixed */
function csr_get_subject($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_subject($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_subject_array($crt) {}

/** @return mixed */
function cert_get_subject_hash($crt) {}

/** @return mixed */
function cert_get_sans($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_issuer($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_publickey($str_crt, $decode = true, $type = "crt") {}

/** @return mixed */
function cert_get_purpose($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_ocspstaple($str_crt, $decode = true) {}

/** @return mixed */
function cert_format_date($validTS, $validTS_time_t, $outputstring = true) {}

/** @return mixed */
function cert_get_dates($str_crt, $decode = true, $outputstring = true) {}

/** @return mixed */
function cert_get_serial($str_crt, $decode = true) {}

/** @return mixed */
function cert_get_sigtype($str_crt, $decode = true) {}

/** @return mixed */
function is_openvpn_server_ca($caref) {}

/** @return mixed */
function is_openvpn_client_ca($caref) {}

/** @return mixed */
function is_ipsec_peer_ca($caref) {}

/** @return mixed */
function is_ldap_peer_ca($caref) {}

/** @return mixed */
function ca_in_use($caref) {}

/** @return mixed */
function is_user_cert($certref) {}

/** @return mixed */
function is_openvpn_server_cert($certref) {}

/** @return mixed */
function is_openvpn_client_cert($certref) {}

/** @return mixed */
function is_ipsec_cert($certref) {}

/** @return mixed */
function is_webgui_cert($certref) {}

/** @return mixed */
function is_package_cert($certref) {}

/** @return mixed */
function is_captiveportal_cert($certref) {}

/** @return mixed */
function is_unbound_cert($certref) {}

/** @return mixed */
function cert_in_use($certref) {}

/** @return mixed */
function cert_usedby_description($refid, $certificates_used_by_packages) {}

/** @return mixed */
function cert_get_max_lifetime() {}

/** @return mixed */
function crl_get_max_lifetime() {}

/** @return mixed */
function crl_create(& $crl, $caref, $name, $serial = 0, $lifetime = 3650) {}

/** @return mixed */
function crl_update(& $crl) {}

/** @return mixed */
function cert_revoke($cert, & $crl, $reason = OCSP_REVOKED_STATUS_UNSPECIFIED) {}

/** @return mixed */
function cert_unrevoke($cert, & $crl) {}

/** @return mixed */
function cert_compare($cert1, $cert2) {}

/** @return mixed */
function crl_get_entry_serial($entry) {}

/** @return mixed */
function cert_validate_serial($serial, $returnvalue = false, $allowlarge = false) {}

/** @return mixed */
function cert_generate_serial() {}

/** @return mixed */
function ca_has_serial($caref, $serial) {}

/** @return mixed */
function cert_get_random_serial($caref = '') {}

/** @return mixed */
function ca_get_next_serial(& $ca) {}

/** @return mixed */
function crl_contains_cert($crl, $cert) {}

/** @return mixed */
function is_cert_revoked($cert, $crlref = "") {}

/** @return mixed */
function is_openvpn_server_crl($crlref) {}

/** @return mixed */
function is_package_crl($crlref) {}

/** @return mixed */
function crl_in_use($crlref) {}

/** @return mixed */
function is_crl_internal($crl) {}

/** @return mixed */
function cert_get_cn($crt, $isref = false) {}

/** @return mixed */
function cert_escape_x509_chars($str, $reverse = false) {}

/** @return mixed */
function cert_add_altname_type($str) {}

/** @return mixed */
function cert_type_config_section($type) {}

/** @return mixed */
function is_cert_locally_renewable($cert) {}

/** @return mixed */
function cert_renew(& $cert, $reusekey = true, $strictsecurity = false, $reuseserial = false) {}

/** @return mixed */
function cert_get_all_services($refid) {}

/** @return mixed */
function ca_get_all_services($refid) {}

/** @return mixed */
function cert_restart_services($services) {}

/** @return mixed */
function cert_get_lifetime($cert, $untilexpire = false) {}

/** @return mixed */
function cert_analyze_lifetime($expiredays) {}

/** @return mixed */
function cert_print_dates($cert) {}

/** @return mixed */
function cert_print_infoblock($cert) {}

/** @return mixed */
function cert_notify_expiring() {}

/** @return mixed */
function ca_setup_trust_store() {}

/** @return mixed */
function ca_setup_capath($ca, $basedir, $crl = "", $refresh = false) {}

/** @return mixed */
function cert_get_pkey_curve($pkey, $decode = true) {}

/** @return mixed */
function cert_build_curve_list() {}

/** @return mixed */
function cert_check_pkey_compatibility($pkey, $consumer) {}

/** @return mixed */
function cert_build_list($type = 'cert', $consumer = '', $selectsource = false, $addnone = false) {}

/** @return mixed */
function cert_pkcs12_export($cert, $encryption = 'high', $passphrase = '', $add_ca = true, $delivery = 'download') {}

/** @return mixed */
function is_weak_digest($digest_alg) {}

/** @return mixed */
function cert_has_weak_digest($str_crt, $decode = true) {}

/** @return mixed */
function cert_chain_has_weak_digest($cert) {}

/** @return mixed */
function cert_check_digest_compatibility($type, $cert, $consumer) {}

/** @return mixed */
function cert_create_selfsigned($descr = '', $hostname = '', $log = true) {}
