<?php
/**
 * pfSense configuration API stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/config.lib.inc
 */

// @codingStandardsIgnoreFile

/**
 * Return a value from the live $config array by dot-separated path.
 *
 * @param  string $path    Dot-separated key path, e.g. 'system.hostname'.
 * @param  mixed  $default Value returned when the path does not exist.
 * @return mixed
 */
function config_get_path(string $path, mixed $default = null): mixed {}

/**
 * Write a value into the live $config array at the given dot-separated path.
 */
function config_set_path(string $path, mixed $value): void {}

/**
 * Delete a key from the live $config array at the given dot-separated path.
 */
function config_del_path(string $path): void {}

/**
 * Return true if the config key at $path exists and is not disabled.
 * When $key is given, checks $path/$key instead.
 */
function config_path_enabled(string $path, string $key = ''): bool {}

/**
 * Flush the in-memory $config to disk (config.xml) and optionally create a backup.
 *
 * @param  string $desc   Human-readable change description stored in the revision log.
 * @param  bool   $backup Whether to create a config backup before writing.
 * @return array<string, mixed>|null
 */
function write_config(string $desc = '', bool $backup = true): ?array {}

/**
 * Read config.xml from disk into the in-memory $config, bypassing the cache.
 *
 * @return array<string, mixed>
 */
function config_read_file(bool $lock = false): array {}

/**
 * Return a value from an arbitrary nested array by dot-separated path.
 *
 * @param  array<string, mixed> $array   Source array.
 * @param  string               $path    Dot-separated path.
 * @param  mixed                $default Fallback when path is absent.
 * @return mixed
 */
function array_get_path(array $array, string $path, mixed $default = null): mixed {}

/**
 * Set a value in an arbitrary nested array by dot-separated path.
 *
 * @param array<string, mixed> $array Target array (modified in-place).
 * @param string               $path  Dot-separated path.
 * @param mixed                $value Value to set.
 */
function array_set_path(array &$array, string $path, mixed $value): void {}

/**
 * Delete a key from an arbitrary nested array by dot-separated path.
 *
 * @param array<string, mixed> $array Target array (modified in-place).
 * @param string               $path  Dot-separated path.
 */
function array_del_path(array &$array, string $path): void {}

/**
 * Ensure the nested key structure at $path exists in $config, initialising
 * any missing levels as empty arrays.
 *
 * @param list<string> $path Sequence of key names, e.g. ['installedpackages', 'pfblockerng'].
 */
function init_config_arr(array $path): void {}

/**
 * Return true if the value at $path in an arbitrary array is truthy/enabled.
 *
 * @param array<string, mixed> $array Source array.
 * @param string               $path  Dot-separated path.
 */
function array_path_enabled(array $array, string $path): bool {}
