<?php
/**
 * pfSense config stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   config.lib.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function encrypted_configxml() {}

/** @return mixed */
function parse_config($parse = false) {}

/** @return mixed */
function generate_config_cache($config) {}

/** @return mixed */
function discover_last_backup() {}

/** @return mixed */
function restore_backup($file) {}

/** @return mixed */
function clear_tagdata($tag, $data) {}

/** @return mixed */
function restore_xmldatafile($type='voucher', $conf = false) {}

/** @return mixed */
function restore_rrddata($conf = false) {}

/** @return mixed */
function restore_sshdata($conf = false) {}

/** @return mixed */
function parse_config_bootup() {}

/** @return mixed */
function conf_mount_rw() {}

/** @return mixed */
function conf_mount_ro() {}

/** @return mixed */
function convert_config() {}

/** @return mixed */
function safe_write_file($file, $content, $force_binary = false) {}

/** @return mixed */
function write_config($desc="Unknown", $backup = true, $write_config_only = false) {}

/** @return mixed */
function reset_factory_defaults($lock = false, $reboot_required = true) {}

/** @return mixed */
function config_restore($conffile) {}

/** @return mixed */
function config_install($conffile) {}

/** @return mixed */
function disable_security_checks() {}

/** @return mixed */
function restore_security_checks() {}

/** @return mixed */
function security_checks_disabled() {}

/** @return mixed */
function config_validate($conffile) {}

/** @return mixed */
function cleanup_backupcache($lock = false) {}

/** @return mixed */
function get_backups() {}

/** @return mixed */
function backup_config() {}

/** @return mixed */
function backup_info($backup_info, $number) {}

/** @return mixed */
function set_device_perms() {}

/** @return mixed */
function get_config_user() {}

/** @return mixed */
function make_config_revision_entry($desc = null, $override_user = null) {}

/** @return mixed */
function pfSense_clear_globals() {}

/** @return mixed */
function config_init_path(string $path) {}

/** @return mixed */
function init_config_arr($keys) {}

/** @return mixed */
function config_get_path(string $path, $default = null) {}

/** @return mixed */
function config_set_path(string $path, $value, $default = null) {}

/** @return mixed */
function config_path_enabled(string $path, $enable_key = "enable") {}

/** @return mixed */
function config_del_path(string $path) {}
