<?php
/**
 * pfSense guiconfig stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   usr/local/www/guiconfig.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function pfSense_csrf_callback() {}

/** @return mixed */
function csrf_startup() {}

/** @return mixed */
function do_input_validation($postdata, $reqdfields, $reqdfieldsn, &$input_errors) {}

/** @return mixed */
function print_input_errors($input_errors) {}

/** @return mixed */
function verify_gzip_file($fname) {}

/** @return mixed */
function sprint_info_box($msg, $class="alert-warning", $btnname = "close", $btntext = "", $btnicon = "", $btnclass = "default") {}

/** @return mixed */
function print_info_box($msg, $class="alert-warning", $btnname = "close", $btntext = "", $btnicon = "", $btnclass = "default") {}

/** @return mixed */
function print_apply_box($msg) {}

/** @return mixed */
function print_apply_result_box($retval, $extra_text="") {}

/** @return mixed */
function print_callout($msg, $class = 'info', $heading = '') {}

/** @return mixed */
function get_std_save_message($retval) {}

/** @return mixed */
function pprint_address($adr, $specialnet_flags = []) {}

/** @return mixed */
function pprint_port($port) {}

/** @return mixed */
function insert_word_breaks_in_domain_name($domain_name) {}

/** @return mixed */
function firewall_check_for_advanced_options(&$item) {}

/** @return mixed */
function gentitle($title) {}

/** @return mixed */
function genhtmltitle($title, $links=true) {}

/** @return mixed */
function gen_customwidgettitle_div($widgettitle) {}

/** @return mixed */
function set_customwidgettitle(& $user_settings) {}

/** @return mixed */
function update_changedesc($update) {}

/** @return mixed */
function update_if_changed($varname, & $orig, $new) {}

/** @return mixed */
function display_widget_tabs(& $tab_array) {}

/** @return mixed */
function outputJavaScriptFileInline($javascript) {}

/** @return mixed */
function outputCSSPrintFileInline($css) {}

/** @return mixed */
function outputCSSFileInline($css) {}

/** @return mixed */
function is_rfc2616_code($code) {}

/** @return mixed */
function print_rfc2616_select($tag, $current) {}

/** @return mixed */
function echo_array($array, $return_me = false) {}

/** @return mixed */
function display_top_tabs(& $tab_array, $no_drop_down = false, $type = 'pills', $usepost = "") {}

/** @return mixed */
function add_package_tabs($tabgroup, &$tab_array) {}

/** @return mixed */
function alias_info_popup($alias_id) {}

/** @return mixed */
function gateway_info_popup($showgw, $gateways_status = false) {}

/** @return mixed */
function rule_columns_with_alias($src, $srcport, $dst, $dstport, $target="", $targetport="") {}

/** @return mixed */
function form_output_row($name, $label, $content) {}

/** @return mixed */
function set_flash_message($class, $msg) {}

/** @return mixed */
function get_flash_message() {}

/** @return mixed */
function getGETPOSTsettingvalue($settingname, $default) {}

/** @return mixed */
function cleanup_crash_file_list() {}

/** @return mixed */
function system_has_crash_data() {}

/** @return mixed */
function system_has_php_errors() {}
