<?php
/**
 * pfSense web-GUI helper stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/guiconfig.inc
 */

// @codingStandardsIgnoreFile

/**
 * Return $string with HTML special characters escaped for safe inline output.
 * Wraps htmlspecialchars() with ENT_QUOTES and UTF-8.
 *
 * @param mixed $string Value to escape; non-string values are cast to string.
 */
function html_safe(mixed $string): string {}

/**
 * Decode HTML entities that were encoded by htmlspecialchars(), then decode
 * any remaining numeric/named HTML entities.
 */
function htmlspecialchars_decode_ent(string $str): string {}

/**
 * Render a Bootstrap navigation tab bar.
 *
 * @param list<array{text: string, url: string, active: bool}> $tab_array Tab definitions.
 * @param bool   $no_drop_down Disable the responsive dropdown for overflow tabs.
 * @param string $type         Bootstrap nav type: 'pills' (default) or 'tabs'.
 */
function display_top_tabs(array &$tab_array, bool $no_drop_down = false, string $type = 'pills'): void {}

/**
 * Render a Bootstrap alert box inside a pfSense page.
 *
 * @param string $msg   Alert text (may contain HTML).
 * @param string $class Bootstrap contextual class: 'success', 'danger', 'warning', 'info'.
 */
function print_info_box(string $msg, string $class = 'success'): void {}

/**
 * Render the standard 'Changes have been applied' confirmation alert box.
 */
function print_apply_box(string $msg): void {}
