<?php
/**
 * pfSense interfaces stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   interfaces.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function interfaces_bring_up($interface) {}

/** @return mixed */
function validate_ipv4_list($value) {}

/** @return mixed */
function get_interface_arr($flush = false) {}

/** @return mixed */
function does_interface_exist($interface, $flush = false) {}

/** @return mixed */
function does_vip_exist($vip) {}

/** @return mixed */
function interfaces_loopback_configure() {}

/** @return mixed */
function vlan_valid_tag($tag = NULL) {}

/** @return mixed */
function qinq_inuse($qinq = NULL, $inqtag = NULL) {}

/** @return mixed */
function qinq_interface($qinq = NULL, $inqtag = NULL) {}

/** @return mixed */
function interface_is_qinq($if = NULL) {}

/** @return mixed */
function vlan_inuse($vlan) {}

/** @return mixed */
function interface_is_vlan($if = NULL) {}

/** @return mixed */
function vlan_interface($vlan = NULL) {}

/** @return mixed */
function interface_set_macaddr($interface, $mac_addr) {}

/** @return mixed */
function interface_is_parent($if, $parent_check) {}

/** @return mixed */
function interface_has_clones($if) {}

/** @return mixed */
function interfaces_vlan_configure($parentif = "") {}

/** @return mixed */
function interface_vlan_configure(&$vlan, $flush = true) {}

/** @return mixed */
function interfaces_vlan_configure_mtu($parentif = "") {}

/** @return mixed */
function interface_qinq_configure(&$qinq, $flush = true) {}

/** @return mixed */
function interfaces_qinq_configure($ovpn=false) {}

/** @return mixed */
function interface_qinq2_configure(&$qinq, $macaddr) {}

/** @return mixed */
function interfaces_create_wireless_clones() {}

/** @return mixed */
function interfaces_bridge_configure($checkmember = 0, $realif = "") {}

/** @return mixed */
function interface_bridge_configure(&$bridge, $checkmember = 0, $flush = true) {}

/** @return mixed */
function interface_bridge_configure_stp($bridge) {}

/** @return mixed */
function interface_bridge_configure_advanced($bridge) {}

/** @return mixed */
function interface_bridge_configure_ip6linklocal($bridge) {}

/** @return mixed */
function interface_bridge_add_member($bridgeif, $interface, $flagsapplied = false) {}

/** @return mixed */
function interfaces_lagg_configure($realif = "") {}

/** @return mixed */
function interface_lagg_configure($lagg, $flush = true) {}

/** @return mixed */
function interface_gre_configure(&$gre, $grekey = "", $flush = true) {}

/** @return mixed */
function interface_is_type($if, $type) {}

/** @return mixed */
function is_greipsec($if) {}

/** @return mixed */
function interface_gif_configure(&$gif, $gifkey = "", $flush = true) {}

/** @return mixed */
function interfaces_tunnel_configure($checkparent = 0, $realif = "", $type = "") {}

/** @return mixed */
function interface_ipsec_vti_list_p1($ph1ent) {}

/** @return mixed */
function interface_ipsec_vti_list_all() {}

/** @return mixed */
function is_interface_ipsec_vti_assigned($phase2) {}

/** @return mixed */
function interface_ipsec_vti_configure($ph1ent, $gateways_status = false) {}

/** @return mixed */
function interfaces_ipsec_vti_configure($gateways_status = false) {}

/** @return mixed */
function interfaces_configure() {}

/** @return mixed */
function interface_reconfigure($interface = "wan", $reloadall = false) {}

/** @return mixed */
function interface_vip_bring_down($vip) {}

/** @return mixed */
function interface_bring_down($interface = "wan", $destroy = false, $ifacecfg = false) {}

/** @return mixed */
function interfaces_carp_set_maintenancemode($carp_maintenancemode) {}

/** @return mixed */
function interface_wait_tentative($interface, $timeout = 10) {}

/** @return mixed */
function interface_isppp_type($interface) {}

/** @return mixed */
function interfaces_ptpid_used($ptpid) {}

/** @return mixed */
function interfaces_ptpid_next() {}

/** @return mixed */
function getMPDCRONSettings($pppif) {}

/** @return mixed */
function handle_pppoe_reset($post_array) {}

/** @return mixed */
function restart_ppp_interfaces_using_interfaces($triggerinterfaces) {}

/** @return mixed */
function interface_ppps_configure($interface) {}

/** @return mixed */
function interfaces_sync_setup() {}

/** @return mixed */
function interface_proxyarp_configure($interface = "") {}

/** @return mixed */
function interface_vip_cleanup($interface, $inet = "all", $type = VIP_ALL) {}

/** @return mixed */
function interfaces_vips_configure($interface = "") {}

/** @return mixed */
function interface_ipalias_configure(&$vip) {}

/** @return mixed */
function interface_carp_configure(&$vip, $maintenancemode_only = false, $ipalias_reload = false) {}

/** @return mixed */
function interface_wireless_clone($realif, $wlcfg) {}

/** @return mixed */
function interface_sync_wireless_clones(&$ifcfg, $sync_changes = false) {}

/** @return mixed */
function interface_wireless_configure($if, &$wl, &$wlcfg) {}

/** @return mixed */
function kill_hostapd($interface) {}

/** @return mixed */
function kill_wpasupplicant($interface) {}

/** @return mixed */
function find_dhclient_process($interface) {}

/** @return mixed */
function kill_dhclient_process($interface) {}

/** @return mixed */
function find_dhcp6c_process() {}

/** @return mixed */
function kill_dhcp6client_process($force, $release = false) {}

/** @return mixed */
function reset_dhcp6client_process() {}

/** @return mixed */
function run_dhcp6client_process($interfaces, $debugOption, $noreleaseOption) {}

/** @return mixed */
function interface_virtual_create($interface, $gateways_status = false) {}

/** @return mixed */
function interface_vlan_mtu_configured($iface) {}

/** @return mixed */
function interface_mtu_wanted_for_pppoe($realif) {}

/** @return mixed */
function interface_configure($interface = "wan", $reloadall = false, $linkupevent = false) {}

/** @return mixed */
function interface_track6_configure($interface, $wancfg, $linkupevent = false) {}

/** @return mixed */
function interface_track6_6rd_configure($interface, $lancfg) {}

/** @return mixed */
function interface_track6_6to4_configure($interface, $lancfg) {}

/** @return mixed */
function interface_6rd_configure($interface, $wancfg) {}

/** @return mixed */
function interface_6to4_configure($interface, $wancfg) {}

/** @return mixed */
function interface_dhcpv6_configure($ifconf, $ifcfg, $destroy = false) {}

/** @return mixed */
function DHCP6_Config_File_Advanced($interface, $wancfg, $wanif) {}

/** @return mixed */
function DHCP6_Config_File_Override($wancfg, $wanif) {}

/** @return mixed */
function DHCP6_Config_File_Substitutions($wancfg, $wanif, $dhcp6cconf) {}

/** @return mixed */
function interface_dhcp_configure($interface) {}

/** @return mixed */
function DHCP_Config_File_Advanced($ifcfg, $realif) {}

/** @return mixed */
function DHCP_Config_Option_Split($option_string) {}

/** @return mixed */
function DHCP_Config_File_Override($ifcfg, $realif) {}

/** @return mixed */
function DHCP_Config_File_Substitutions($ifcfg, $realif, $dhclientconf) {}

/** @return mixed */
function interfaces_group_setup() {}

/** @return mixed */
function interface_group_setup(&$groupname /* The parameter is an array */) {}

/** @return mixed */
function is_interface_group($if) {}

/** @return mixed */
function interface_group_add_member($interface, $groupname) {}

/** @return mixed */
function convert_friendly_interface_to_real_interface_name($interface) {}

/** @return mixed */
function get_real_wan_interface($interface = "wan") {}

/** @return mixed */
function get_current_wan_address($interface = "wan") {}

/** @return mixed */
function convert_real_interface_to_friendly_interface_name($interface = "wan", $checkparent = false) {}

/** @return mixed */
function convert_friendly_interface_to_friendly_descr($interface) {}

/** @return mixed */
function convert_real_interface_to_friendly_descr($interface) {}

/** @return mixed */
function get_parent_interface($interface, $avoidrecurse = false) {}

/** @return mixed */
function get_parent_physical_interface($interface) {}

/** @return mixed */
function interface_is_wireless_clone($wlif) {}

/** @return mixed */
function interface_get_wireless_base($wlif) {}

/** @return mixed */
function interface_get_wireless_clone($wlif) {}

/** @return mixed */
function interface_list_wireless() {}

/** @return mixed */
function get_real_interface($interface = "wan", $family = "all", $realv6iface = false, $flush = false) {}

/** @return mixed */
function guess_interface_from_ip($ipaddress) {}

/** @return mixed */
function find_ip_interface($ip, $bits = null) {}

/** @return mixed */
function find_virtual_ip_alias($ip, $bits = null) {}

/** @return mixed */
function link_interface_to_track6($int, $action = "") {}

/** @return mixed */
function interface_find_child_cfgmtu($realiface) {}

/** @return mixed */
function link_interface_to_vlans($int, $action = "") {}

/** @return mixed */
function link_interface_to_qinqs($int, $action = "") {}

/** @return mixed */
function link_interface_to_vips($int, $action = "", $vhid = '') {}

/** @return mixed */
function link_interface_to_bridge($int) {}

/** @return mixed */
function link_interface_to_lagg($int) {}

/** @return mixed */
function link_interface_to_group($int) {}

/** @return mixed */
function link_interface_to_tunnelif($interface, $type, $remote = 'any') {}

/** @return mixed */
function link_interface_to_ppp_tunnelif($interface) {}

/** @return mixed */
function find_interface_ip($interface, $flush = false) {}

/** @return mixed */
function find_interface_ipv6($interface, $flush = false) {}

/** @return mixed */
function find_interface_ipv6_ll($interface, $flush = false, $usefirst = true) {}

/** @return mixed */
function find_interface_subnet($interface, $flush = false) {}

/** @return mixed */
function find_interface_subnetv6($interface, $flush = false) {}

/** @return mixed */
function ip_in_interface_alias_subnet($interface, $ipalias) {}

/** @return mixed */
function get_possible_listen_ips($include_ipv6_link_local=false) {}

/** @return mixed */
function get_possible_traffic_source_addresses($include_ipv6_link_local=false) {}

/** @return mixed */
function get_interface_ip($interface = "wan", $gateways_status = false) {}

/** @return mixed */
function get_interface_ipv6($interface = "wan", $flush = false, $linklocal_fallback = false, $gateways_status = false) {}

/** @return mixed */
function get_interface_linklocal($interface = "wan") {}

/** @return mixed */
function get_interface_track6ip($interface = "wan") {}

/** @return mixed */
function get_interface_subnet($interface = "wan") {}

/** @return mixed */
function get_interface_subnetv6($interface = "wan") {}

/** @return mixed */
function get_interfaces_with_gateway() {}

/** @return mixed */
function interface_has_gateway($friendly) {}

/** @return mixed */
function interface_has_gatewayv6($friendly) {}

/** @return mixed */
function is_altq_capable($int) {}

/** @return mixed */
function is_interface_wireless($interface) {}

/** @return mixed */
function get_wireless_modes($interface) {}

/** @return mixed */
function get_wireless_channels($interface) {}

/** @return mixed */
function get_wireless_ht_modes($interface) {}

/** @return mixed */
function get_wireless_ht_list($interface) {}

/** @return mixed */
function get_wireless_channel_info($interface) {}

/** @return mixed */
function set_interface_mtu($interface, $mtu) {}

/** @return mixed */
function get_interface_mtu($interface) {}

/** @return mixed */
function get_interface_mac($interface) {}

/** @return mixed */
function get_interface_vendor_mac($interface) {}

/** @return mixed */
function generate_random_mac_address() {}

/** @return mixed */
function interface_setup_pppoe_reset_file($pppif, $iface="") {}

/** @return mixed */
function get_interface_default_mtu($type = "ethernet") {}

/** @return mixed */
function get_vip_descr($ipaddress) {}

/** @return mixed */
function interfaces_staticarp_configure($if) {}

/** @return mixed */
function get_failover_interface($interface, $family = "all", $gateways_status = false) {}

/** @return mixed */
function interface_has_dhcp($interface, $family = 4) {}

/** @return mixed */
function remove_ifindex($ifname) {}

/** @return mixed */
function get_configured_vip_list_with_descr($family = 'all', $type = VIP_ALL) {}

/** @return mixed */
function return_gateway_groups_array_with_descr() {}

/** @return mixed */
function get_serial_ports($short=false) {}

/** @return mixed */
function get_interface_ports() {}

/** @return mixed */
function build_ppps_link_list() {}

/** @return mixed */
function create_interface_list($open = false) {}

/** @return mixed */
function is_pseudo_interface($inf, $tap=true) {}

/** @return mixed */
function is_stf_interface($inf) {}

/** @return mixed */
function restart_interface_services($interface, $ipv6type = "") {}

/** @return mixed */
function get_interface_addresses($interface) {}

function get_interface_addresses_all(string $interface): array {}
