<?php
/**
 * pfSense ipsec stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   ipsec.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function ipsec_enabled() {}

/** @return mixed */
function ipsec_ikeid_used($ikeid) {}

/** @return mixed */
function ipsec_ikeid_next() {}

/** @return mixed */
function ipsec_new_reqid() {}

/** @return mixed */
function ipsec_get_phase1($ikeid) {}

/** @return mixed */
function ipsec_get_p1_descr($ikeid) {}

/** @return mixed */
function ipsec_lookup_phase1($p2, &$p1_disabled) {}

/** @return mixed */
function ipsec_get_phase2($reqid) {}

/** @return mixed */
function ipsec_get_phase2_by_ikeid($ikeid) {}

/** @return mixed */
function ipsec_get_number_of_phase2($ikeid) {}

/** @return mixed */
function ipsec_map_config_by_id() {}

/** @return mixed */
function ipsec_conid($p1 = null, $p2 = null) {}

/** @return mixed */
function ipsec_id_by_conid($conid) {}

/** @return mixed */
function ipsec_get_phase1_src(& $ph1ent, $gateways_status = false) {}

/** @return mixed */
function ipsec_get_phase1_dst(& $ph1ent) {}

/** @return mixed */
function ipsec_idinfo_to_cidr(& $idinfo, $addrbits = false, $mode = "") {}

/** @return mixed */
function ipsec_idinfo_to_subnet(& $idinfo, $addrbits = false) {}

/** @return mixed */
function ipsec_idinfo_to_text(& $idinfo) {}

/** @return mixed */
function ipsec_list_sa() {}

/** @return mixed */
function ipsec_status() {}

/** @return mixed */
function ipsec_status_button($req, $act, $type, $conid, $uniqueid, $full) {}

/** @return mixed */
function ipsec_initiate($type = 'ike', $p1 = null, $p2 = null) {}

/** @return mixed */
function ipsec_initiate_by_conid($type, $conid) {}

/** @return mixed */
function ipsec_terminate($type = 'ike', $p1 = null, $p2 = null, $uniqueid = null) {}

/** @return mixed */
function ipsec_terminate_by_conid($type = 'ike', $conid = null, $uniqueid = null) {}

/** @return mixed */
function ipsec_dump_spd() {}

/** @return mixed */
function ipsec_dump_sad() {}

/** @return mixed */
function ipsec_dump_mobile() {}

/** @return mixed */
function ipsec_mobilekey_sort() {}

/** @return mixed */
function mobilekeycmp($a, $b) {}

/** @return mixed */
function ipsec_fixup_ip($ipaddr) {}

/** @return mixed */
function ipsec_find_id(& $ph1ent, $side = "local", $rgmap = array(), $gateways_status = false) {}

/** @return mixed */
function ipsec_fixup_id($type, $data) {}

/** @return mixed */
function ipsec_fixup_network($network) {}

/** @return mixed */
function ipsec_get_loglevels() {}

/** @return mixed */
function ipsec_vti($p1, $returnaddresses = false, $skipdisabled = true) {}

/** @return mixed */
function ipsec_reload_package_hook() {}

/** @return mixed */
function ipsec_convert_to_modp($index) {}

/** @return mixed */
function ipsec_force_reload($interface = "", $protocol = "") {}

/** @return mixed */
function ipsec_strongswan_confgen($confarr, $indent = "") {}

/** @return mixed */
function ipsec_create_dirs() {}

/** @return mixed */
function ipsec_setup_gwifs($gateways_status = false) {}

/** @return mixed */
function ipsec_logging_config() {}

/** @return mixed */
function ipsec_setup_strongswan() {}

/** @return mixed */
function ipsec_setup_pools() {}

/** @return mixed */
function ipsec_setup_userpools() {}

/** @return mixed */
function ipsec_setup_bypass($gateways_status) {}

/** @return mixed */
function ipsec_setup_routes($interface, $family, $sourcehost, $duplicates) {}

/** @return mixed */
function ipsec_setup_authentication(& $ph1ent, & $conn, $gateways_status = false) {}

/** @return mixed */
function ipsec_setup_proposal_algo($ealg_id, $keylen, $halgo, $prfalgo, $modp) {}

/** @return mixed */
function ipsec_setup_proposal_entry(& $ph2ent, & $algo_arr, $ealg_id, $keylen) {}

/** @return mixed */
function ipsec_get_ifname($p1, $reqid = 0) {}

/** @return mixed */
function ipsec_get_ifname_by_conf($p1 = array(), $p2 = array()) {}

/** @return mixed */
function ipsec_setup_vtireq(& $child, & $ipsec_vti_cleanup_ifs, $p1, $reqid = 0) {}

/** @return mixed */
function ipsec_setup_tunnels($gateways_status = false) {}

/** @return mixed */
function ipsec_setup_secrets($gateways_status = false) {}

/** @return mixed */
function ipsec_configure($restart = false, $filterdns_restart = false) {}

/** @return mixed */
function ipsec_gre_default_mtu() {}

/** @return mixed */
function ipsec_get_renewmax($entry) {}

/** @return mixed */
function ipsec_get_life_time($entry) {}

/** @return mixed */
function ipsec_get_rekey_time($entry) {}

/** @return mixed */
function ipsec_get_reauth_time($entry) {}

/** @return mixed */
function ipsec_get_over_time($entry) {}

/** @return mixed */
function ipsec_get_rand_time($entry) {}
