<?php
/**
 * pfSense logging, notification, and i18n stubs — IDE static analysis only (Intelephense).
 *
 * Hand-maintained — NOT regenerated by scripts/update-pfsense-stubs.py (see its
 * STUB_MODULES comment); edit this file directly for a file_notice()/gettext() fix.
 * References (mirror is frozen at RELENG_2_7_2 — no RELENG_2_8_0 tag/branch exists):
 * https://github.com/pfsense/pfsense/blob/RELENG_2_7_2/src/etc/inc/util.inc (log_error)
 * https://github.com/pfsense/pfsense/blob/RELENG_2_7_2/src/etc/inc/notices.inc (file_notice)
 */

// @codingStandardsIgnoreFile

// ── Syslog ────────────────────────────────────────────────────────────────────

// logger() is intentionally NOT stubbed here. pfBlockerNG ships a
// function_exists()-guarded fallback in pfblockerng_extra.inc (for pfSense CE
// <= 2.8.1, whose core lacks logger()/localize_text()), and PHPStan resolves
// that source declaration — with the correct signature logger(int $priority,
// mixed $message, ?string $prefix, ?int $facilities). A stub here would only
// duplicate it (and the old logger(string) signature was wrong).

/** Write $error to syslog at LOG_ERR level. */
function log_error(string $error): void {}

// ── GUI notifications ─────────────────────────────────────────────────────────

/**
 * Create a persistent notice in the pfSense notification system.
 *
 * @param string $id         Unique identifier used to de-duplicate notices.
 * @param string $notice     Notice text displayed in the GUI.
 * @param string $category   Category label (e.g. 'General', 'Packages').
 * @param string $url        Optional URL to link from the notice.
 * @param int    $priority   Notice severity: 0 = informational, 1 = warning, 2 = error.
 * @param bool   $local_only Suppress HA/XMLRPC sync of this notice.
 */
function file_notice(
    string $id,
    string $notice,
    string $category   = 'General',
    string $url        = '',
    int    $priority   = 1,
    bool   $local_only = false
): void {}

/**
 * Update the progress/status message shown during package operations
 * (visible in the pfSense package manager UI).
 */
function update_status(string $status): void {}

// ── Internationalisation ──────────────────────────────────────────────────────

/**
 * Return the translated version of $text using the active pfSense locale.
 * Falls back to returning $text unchanged when no translation is available.
 */
function gettext(string $text): string {}

/**
 * Return the translated version of $text from the given gettext $domain.
 */
function dgettext(string $domain, string $text): string {}
