<?php
/**
 * pfSense logging, notification, and i18n stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/util.inc
 */

// @codingStandardsIgnoreFile

// ── Syslog ────────────────────────────────────────────────────────────────────

/**
 * Write $message to the system logger (syslog) with the default facility.
 * Prefer log_error() for error-level messages.
 */
function logger(string $message): void {}

/** Write $error to syslog at LOG_ERR level. */
function log_error(string $error): void {}

// ── GUI notifications ─────────────────────────────────────────────────────────

/**
 * Create a persistent notice in the pfSense notification system.
 *
 * @param string $id         Unique identifier used to de-duplicate notices.
 * @param string $notice     Notice text displayed in the GUI.
 * @param string $category   Category label (e.g. 'General', 'Packages').
 * @param string $url        Optional URL to link from the notice.
 * @param int    $local_only 1 to suppress HA/XMLRPC sync of this notice.
 */
function file_notice(
    string $id,
    string $notice,
    string $category   = 'General',
    string $url        = '',
    int    $local_only = 0
): void {}

/**
 * Update the progress/status message shown during package operations
 * (visible in the pfSense package manager UI).
 */
function update_status(string $status): void {}

// ── Internationalisation ──────────────────────────────────────────────────────

/**
 * Return the translated version of $text using the active pfSense locale.
 * Falls back to returning $text unchanged when no translation is available.
 */
function gettext(string $text): string {}

/**
 * Return the translated version of $text from the given gettext $domain.
 */
function dgettext(string $domain, string $text): string {}
