<?php
/**
 * pfSense services stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   services.inc
 *   service-utils.inc
 *   pkg-utils.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function services_radvd_configure($blacklist = array()) {}

function kea_is_hexstring(string $string): bool {}

/** @return mixed */
function services_kea6_configure() {}

/** @return mixed */
function services_dhcpd_kill_all($family = 'all') {}

/** @return mixed */
function services_dhcpd_configure($family = "all") {}

/** @return mixed */
function services_kea4_configure() {}

/** @return mixed */
function services_dhcpdv4_configure() {}

/** @return mixed */
function dhcpdkey($dhcpifconf) {}

/** @return mixed */
function dhcpdzones($ddns_zones) {}

/** @return mixed */
function services_dhcpdv6_configure($blacklist = array()) {}

/** @return mixed */
function services_igmpproxy_configure($interface='') {}

/** @return mixed */
function services_dhcrelay_configure() {}

/** @return mixed */
function services_dhcrelay6_configure() {}

/** @return mixed */
function services_dyndns_configure_client($conf) {}

/** @return mixed */
function services_dyndns_configure($int = "") {}

/** @return mixed */
function dyndnsCheckIP($int) {}

/** @return mixed */
function services_dnsmasq_configure($restart_dhcp = true) {}

/** @return mixed */
function services_unbound_configure($restart_dhcp = true, $interface = '') {}

/** @return mixed */
function services_snmpd_configure($interface='') {}

/** @return mixed */
function services_dnsupdate_process($int = "", $updatehost = "", $forced = false) {}

/** @return mixed */
function configure_cron() {}

/** @return mixed */
function upnp_action ($action) {}

/** @return mixed */
function upnp_start() {}

/** @return mixed */
function install_cron_job($command, $active = false, $minute = "0", $hour = "*", $monthday = "*", $month = "*", $weekday = "*", $who = "root", $write_config = true) {}

/** @return mixed */
function write_rcfile($params) {}

/** @return mixed */
function start_service($name, $after_sync = false) {}

/** @return mixed */
function stop_service($name) {}

/** @return mixed */
function restart_service($name) {}

/** @return mixed */
function is_pid_running($pidfile) {}

/** @return mixed */
function is_dhcp_running($interface) {}

/** @return mixed */
function restart_service_if_running($service) {}

/** @return mixed */
function is_service_enabled($service_name) {}

/** @return mixed */
function is_service_running($service, $ps = "") {}

/** @return mixed */
function get_services() {}

/** @return mixed */
function find_service_by_name($name) {}

/** @return mixed */
function find_service_by_openvpn_vpnid($vpnid) {}

/** @return mixed */
function find_service_by_cp_zone($zone) {}

/** @return mixed */
function service_description_compare($a, $b) {}

/** @return mixed */
function service_name_compare($a, $b) {}

/** @return mixed */
function service_dispname_compare($a, $b) {}

/** @return mixed */
function get_pkg_descr($package_name) {}

/** @return mixed */
function get_service_status($service) {}

/** @return mixed */
function get_service_status_icon($service, $withtext = true, $smallicon = false, $withthumbs = false, $title = "service_state") {}

/** @return mixed */
function get_service_control_links($service, $addname = false) {}

/** @return mixed */
function service_control_start($name, $extras) {}

/** @return mixed */
function service_control_stop($name, $extras) {}

/** @return mixed */
function service_control_restart($name, $extras) {}

/** @return mixed */
function pkg_debug($msg) {}

/** @return mixed */
function pkg_valid_name($pkgname) {}

/** @return mixed */
function pkg_remove_prefix(&$pkg_name) {}

/** @return mixed */
function pkg_update($force = false) {}

/** @return mixed */
function pkg_env($extra_env = array()) {}

/** @return mixed */
function pkg_call($params, $mute = false, $extra_env = array()) {}

/** @return mixed */
function pkg_exec($params, &$stdout, &$stderr, $extra_env = array()) {}

/** @return mixed */
function pkg_version_compare($v1, $v2) {}

/** @return mixed */
function is_pkg_installed($pkg_name) {}

/** @return mixed */
function pkg_install($pkg_name, $force = false) {}

/** @return mixed */
function pkg_delete($pkg_name) {}

/** @return mixed */
function is_package_installed($package_name) {}

/** @return mixed */
function get_package_id($package_name) {}

/** @return mixed */
function get_package_internal_name($package_data) {}

/** @return mixed */
function get_pkg_info($pkgs = 'all', $remote_repo_usage_disabled = false, $installed_pkgs_only = false) {}

/** @return mixed */
function register_all_installed_packages() {}

/** @return mixed */
function resync_all_package_configs($show_message = false) {}

/** @return mixed */
function uninstall_package($package_name) {}

/** @return mixed */
function reinstall_package($package_name) {}

/** @return mixed */
function sync_package($package_name) {}

/** @return mixed */
function read_package_config($package_name) {}

/** @return mixed */
function read_package_configurationfile($package_name) {}

/** @return mixed */
function get_after_install_info($package_name) {}

/** @return mixed */
function eval_once($toeval) {}

/** @return mixed */
function install_package_xml($package_name) {}

/** @return mixed */
function delete_package_xml($package_name, $when = "post-deinstall") {}

/** @return mixed */
function package_reinstall_all() {}

/** @return mixed */
function stop_packages() {}

/** @return mixed */
function get_meta_pkg_name() {}

/** @return mixed */
function get_base_pkg_name() {}

/** @return mixed */
function get_system_pkg_version($baseonly = false, $use_cache = true, $updates_only = true, $update_cache = false) {}

/** @return mixed */
function pkg_list_repos() {}

/** @return mixed */
function pkg_get_default_repo() {}

/** @return mixed */
function pkg_build_repo_list() {}

/** @return mixed */
function pkg_get_repo_name($path) {}

/** @return mixed */
function pkg_get_repo_help() {}

/** @return mixed */
function pkg_switch_repo($repo_path, $repo_name) {}

/** @return mixed */
function update_repos() {}
