<?php
/**
 * pfSense service-management stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/services.inc
 *            https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/service-utils.inc
 *            https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/pkg-utils.inc
 */

// @codingStandardsIgnoreFile

// ── Service lifecycle ─────────────────────────────────────────────────────────

/**
 * Start a named pfSense service (rc script or daemon).
 *
 * @param string $name          Service name as registered in /etc/rc.d or pkg.
 * @param string $after_service Optional: start this service after $name.
 */
function start_service(string $name, string $after_service = ''): void {}

/** Stop a named pfSense service. */
function stop_service(string $name): void {}

/** Restart a named pfSense service. */
function restart_service(string $name): void {}

/**
 * Return true if the named service is currently running.
 *
 * @param string               $service Service name.
 * @param list<string>         $ps      Optional pre-fetched process list to search.
 */
function is_service_running(string $service, array $ps = []): bool {}

/** Return true if the service is enabled in the pfSense configuration. */
function is_service_enabled(string $service): bool {}

/**
 * Return a human-readable status string for the given service descriptor.
 *
 * @param array<string, string> $service Service descriptor array.
 */
function get_service_status(array $service): string {}

/** Return the PID of the named service, or an empty string if not running. */
function get_service_pid(string $servicename): string {}

// ── Cron ──────────────────────────────────────────────────────────────────────

/**
 * Add or remove a cron job entry in the pfSense cron configuration.
 *
 * @param string $command  Shell command to execute.
 * @param bool   $active   True to add/update the job, false to remove it.
 * @param string $minute   Cron minute field (default '0').
 * @param string $hour     Cron hour field.
 * @param string $mday     Cron day-of-month field.
 * @param string $month    Cron month field.
 * @param string $wday     Cron day-of-week field.
 * @param string $who      Unix user to run the command as (default 'root').
 * @param bool   $grouping Whether to group duplicate cron entries.
 */
function install_cron_job(
    string $command,
    bool   $active   = false,
    string $minute   = '0',
    string $hour     = '*',
    string $mday     = '*',
    string $month    = '*',
    string $wday     = '*',
    string $who      = 'root',
    bool   $grouping = true
): void {}
