<?php
/**
 * pfSense system and filter function stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/functions.inc
 *            https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/filter.inc
 */

// @codingStandardsIgnoreFile

/** Return a stable unique identifier string for this pfSense installation. */
function system_get_uniqueid(): string {}

/**
 * Return true if the system is still in the early boot phase.
 * Use this to skip tasks that require a fully-initialised system.
 */
function is_platform_booting(): bool {}

/** Alias of is_platform_booting() kept for backwards compatibility. */
function platform_booting(): bool {}

/**
 * Return true if the current PHP process is running as a non-interactive
 * backend worker (e.g. invoked by pfSense's rc scripts or the PHP shell).
 */
function is_backend(): bool {}

/** Return true if WireGuard is enabled in the pfSense configuration. */
function is_wg_enabled(): bool {}

/**
 * Reload the firewall filter rules (pf) to match the current configuration.
 * Equivalent to issuing a 'filter reload' event to the backend.
 */
function filter_configure(): void {}
