<?php
/**
 * pfSense system stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   functions.inc
 *   filter.inc
 *   system.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function filter_antilockout_tracker() {}

/** @return mixed */
function filter_bogons_tracker() {}

/** @return mixed */
function filter_rfc1918_tracker() {}

/** @return mixed */
function filter_rule_tracker() {}

/** @return mixed */
function filter_captiveportal_tracker() {}

/** @return mixed */
function filter_negaterule_tracker() {}

/** @return mixed */
function user_rule_descr_maxlen() {}

/** @return mixed */
function fix_rule_label($descr) {}

/** @return mixed */
function is_bogonsv6_used($force = false) {}

/** @return mixed */
function filter_pflog_start() {}

/** @return mixed */
function filter_configure() {}

/** @return mixed */
function filter_delete_states_for_down_gateways() {}

/** @return mixed */
function filter_configure_sync($delete_states_if_needed = true) {}

/** @return mixed */
function filter_generate_scrubing() {}

/** @return mixed */
function filter_generate_nested_alias($name) {}

/** @return mixed */
function filter_generate_nested_alias_recurse($name, $alias, &$aliasnesting, &$aliasaddrnesting, &$use_filterdns = false) {}

/** @return mixed */
function filter_expand_alias($alias_name) {}

/** @return mixed */
function filter_expand_alias_array($alias_name) {}

/** @return mixed */
function filter_generate_aliases() {}

/** @return mixed */
function filter_generate_gateways() {}

/** @return mixed */
function filter_get_vpns_list() {}

/** @return mixed */
function filter_get_direct_networks_list($returnsubnetsonly = true) {}

/** @return mixed */
function filter_generate_optcfg_array() {}

/** @return mixed */
function filter_flush_state_table() {}

/** @return mixed */
function filter_get_reflection_interfaces($natif = "") {}

/** @return mixed */
function filter_generate_reflection_nat($rule, &$route_table, $nat_ifs, $protocol, $target, $target_ip, $target_subnet = "") {}

/** @return mixed */
function filter_generate_reflection_proxy($rule, $nordr, $rdr_ifs, $srcaddr, $dstaddr_port, &$starting_localhost_port, &$reflection_rules) {}

/** @return mixed */
function filter_nat_rules_automatic_tonathosts($with_descr = false) {}

/** @return mixed */
function filter_nat_rules_outbound_automatic($src) {}

/** @return mixed */
function filter_nat_rules_generate_if ($if, $descr = "", $ipprotocol = "", $src = "any", $srcport = "", $dst = "any", $dstport = "", $natip = "", $natport = "", $nonat = false, $staticnatport = false, $proto = "", $poolopts = "") {}

/** @return mixed */
function xinetd_service_entry($entry_array) {}

/** @return mixed */
function filter_nat_rules_generate() {}

/** @return mixed */
function filter_generate_user_rule_arr($rule) {}

/** @return mixed */
function filter_generate_port($rule, $target = "source", $isnat = false) {}

/** @return mixed */
function filter_address_add_vips_subnets(&$subnets, $if, $not) {}

/** @return mixed */
function filter_generate_address(& $rule, $target = "source", $isnat = false) {}

/** @return mixed */
function filter_generate_user_rule($rule, & $extralabels = null) {}

/** @return mixed */
function filter_rules_generate() {}

/** @return mixed */
function filter_rules_spoofcheck_generate($ifname, $ifcfg, $log) {}

/** @return mixed */
function filter_tdr_install_cron($should_install) {}

/** @return mixed */
function filter_get_time_based_rule_status($schedule) {}

/** @return mixed */
function filter_tdr_day($schedule) {}

/** @return mixed */
function filter_tdr_hour($schedule) {}

/** @return mixed */
function filter_tdr_position($schedule) {}

/** @return mixed */
function filter_tdr_month($schedule) {}

/** @return mixed */
function filter_setup_logging_interfaces() {}

/** @return mixed */
function filter_process_carp_rules($log) {}

/** @return mixed */
function filter_generate_ipsec_rules($log = array()) {}

/** @return mixed */
function discover_pkg_rules($ruletype) {}

/** @return mixed */
function filter_get_antilockout_ports($wantarray = false) {}

function get_interface_ruleindex(string $interface, ?int $rule_index = null): array {}

/** @return mixed */
function display_separator($separators, $nrules, $columns_in_table) {}

/** @return mixed */
function separator_rows($separators) {}

function shift_separators(array &$separators, ?int $index, bool $shiftup = false): void {}

/** @return mixed */
function filter_get_interface_list() {}

/** @return mixed */
function filter_get_host_id() {}

/** @return mixed */
function system_hwpstate_active() {}

/** @return mixed */
function system_hwpstate_disabled() {}

/** @return mixed */
function system_has_hwpstate() {}

/** @return mixed */
function system_hwpstate_setepp() {}

/** @return mixed */
function activate_powerd() {}

/** @return mixed */
function get_default_sysctl_value($id) {}

/** @return mixed */
function get_sysctl_descr($sysctl) {}

/** @return mixed */
function system_get_sysctls() {}

/** @return mixed */
function activate_sysctls() {}

/** @return mixed */
function system_resolvconf_generate($dynupdate = false) {}

/** @return mixed */
function get_searchdomains() {}

/** @return mixed */
function get_nameservers() {}

/** @return mixed */
function get_dynamic_nameservers($iface = '') {}

/** @return mixed */
function system_hosts_local_entries() {}

/** @return mixed */
function system_hosts_override_entries($dnscfg) {}

/** @return mixed */
function system_hosts_dhcpd_entries() {}

/** @return mixed */
function system_hosts_entries($dnscfg) {}

/** @return mixed */
function system_hosts_generate() {}

/** @return mixed */
function system_dhcpleases_configure() {}

/** @return mixed */
function system_clear_all_kea4leases() {}

/** @return mixed */
function system_del_kea4lease(string $ip) {}

/** @return mixed */
function system_clear_all_kea6leases() {}

/** @return mixed */
function system_del_kea6lease(string $ip) {}

/** @return mixed */
function system_get_kea6leases() {}

/** @return mixed */
function system_get_kea4leases() {}

/** @return mixed */
function system_get_dhcpleases($dnsavailable=null) {}

/** @return mixed */
function system_hostname_configure() {}

/** @return mixed */
function system_routing_configure($interface = "") {}

/** @return mixed */
function system_staticroutes_configure($interface = "", $update_dns = false) {}

/** @return mixed */
function delete_static_route($id, $delete = false) {}

/** @return mixed */
function system_routing_enable() {}

/** @return mixed */
function system_webgui_start() {}

/** @return mixed */
function get_dns_nameservers($add_v6_brackets = false, $hostns=true) {}

/** @return mixed */
function system_generate_nginx_config($filename, $cert, $key, $ca, $pid_file, $port = 80, $document_root = "/usr/local/www/", $cert_location = "cert.crt", $key_location = "cert.key", $captive_portal = false, $hsts = true) {}

/** @return mixed */
function system_get_timezone_list() {}

/** @return mixed */
function system_timezone_configure() {}

/** @return mixed */
function check_gps_speed($device) {}

/** @return mixed */
function system_ntp_poll_values() {}

/** @return mixed */
function system_ntp_fixup_poll_value($type, $configvalue, $default) {}

/** @return mixed */
function system_ntp_setup_gps($serialport) {}

/** @return mixed */
function system_ntp_setup_rawspeed($serialport, $baud) {}

/** @return mixed */
function system_ntp_setup_pps($serialport) {}

/** @return mixed */
function system_ntp_configure() {}

/** @return mixed */
function system_halt() {}

/** @return mixed */
function system_reboot() {}

/** @return mixed */
function system_reboot_sync($reroot=false) {}

/** @return mixed */
function system_reboot_cleanup() {}

/** @return mixed */
function system_do_shell_commands($early = 0) {}

/** @return mixed */
function system_dmesg_save() {}

/** @return mixed */
function system_set_harddisk_standby() {}

/** @return mixed */
function system_setup_sysctl() {}

/** @return mixed */
function system_disable_arp_wrong_if() {}

/** @return mixed */
function system_enable_arp_wrong_if() {}

/** @return mixed */
function enable_watchdog() {}

/** @return mixed */
function system_check_reset_button() {}

/** @return mixed */
function system_get_serial() {}

/** @return mixed */
function system_get_uniqueid() {}

/** @return mixed */
function system_identify_specific_platform() {}

/** @return mixed */
function system_get_dmesg_boot() {}

/** @return mixed */
function system_get_arp_table($resolve_hostnames = false) {}

/** @return mixed */
function _getHostName($mac, $ip) {}

/** @return mixed */
function check_dnsavailable($proto='inet') {}
