<?php
/**
 * pfSense util stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE 2.7.2
 * (tag RELENG_2_7_2).
 *
 * Source files:
 *   util.inc
 *   pfsense-utils.inc
 *   globals.inc
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

/** @return mixed */
function killbypid($pidfile, $waitfor = 0) {}

/** @return mixed */
function isvalidpid($pidfile) {}

/** @return mixed */
function is_process_running($process) {}

/** @return mixed */
function isvalidproc($proc) {}

/** @return mixed */
function sigkillbypid($pidfile, $sig, $waitfor = 0) {}

/** @return mixed */
function sigkillbyname($procname, $sig) {}

/** @return mixed */
function killbyname($procname) {}

/** @return mixed */
function is_subsystem_dirty($subsystem = "") {}

/** @return mixed */
function mark_subsystem_dirty($subsystem = "") {}

/** @return mixed */
function clear_subsystem_dirty($subsystem = "") {}

/** @return mixed */
function clear_filter_subsystems_dirty() {}

/** @return mixed */
function lock($lock, $op = LOCK_SH) {}

/** @return mixed */
function try_lock($lock, $timeout = 5) {}

/** @return mixed */
function unlock($cfglckkey = 0) {}

/** @return mixed */
function unlock_force($lock) {}

/** @return mixed */
function send_event($cmd) {}

/** @return mixed */
function send_multiple_events($cmds) {}

function is_module_available(string $module_name, string ...$add_dirs): bool {}

function is_module_loaded(string $module_name): bool {}

/** @return mixed */
function is_numericint($arg) {}

/** @return mixed */
function gen_subnet($ipaddr, $bits) {}

/** @return mixed */
function gen_subnetv4($ipaddr, $bits) {}

/** @return mixed */
function gen_subnetv6($ipaddr, $bits) {}

/** @return mixed */
function gen_subnet_max($ipaddr, $bits) {}

/** @return mixed */
function gen_subnetv4_max($ipaddr, $bits) {}

/** @return mixed */
function gen_subnetv6_max($ipaddr, $bits) {}

/** @return mixed */
function gen_subnet_mask_long($bits) {}

/** @return mixed */
function gen_subnet_mask($bits) {}

/** @return mixed */
function gen_subnet_mask_v6($bits) {}

/** @return mixed */
function long2ip32($ip) {}

/** @return mixed */
function ip2long32($ip) {}

/** @return mixed */
function ip2ulong($ip) {}

/** @return mixed */
function ip6_to_bin($ip) {}

/** @return mixed */
function bin_to_ip6($bin) {}

/** @return mixed */
function bin_to_compressed_ip6($bin) {}

/** @return mixed */
function text_to_compressed_ip6($text) {}

/** @return mixed */
function ip_range_size_v4($startip, $endip) {}

/** @return mixed */
function find_smallest_cidr_v4($number) {}

/** @return mixed */
function ip_before($ip, $offset = 1) {}

/** @return mixed */
function ip_after($ip, $offset = 1) {}

/** @return mixed */
function ip_less_than($ip1, $ip2) {}

/** @return mixed */
function ip_greater_than($ip1, $ip2) {}

/** @return mixed */
function ipcmp($a, $b) {}

/** @return mixed */
function ip_range_to_address_array($startip, $endip, $max_size = 5000) {}

/** @return mixed */
function ip_range_to_subnet_array($ip1, $ip2) {}

/** @return mixed */
function is_iprange($range) {}

/** @return mixed */
function is_ipaddr($ipaddr) {}

/** @return mixed */
function is_ipaddrv6($ipaddr) {}

/** @return mixed */
function is_ipaddrv6_v4map($ipaddr) {}

/** @return mixed */
function is_ipaddrv4($ipaddr) {}

/** @return mixed */
function is_mcast($ipaddr) {}

/** @return mixed */
function is_mcastv4($ipaddr) {}

/** @return mixed */
function is_mcastv6($ipaddr) {}

/** @return mixed */
function is_linklocal($ipaddr) {}

/** @return mixed */
function get_ll_scope($addr) {}

/** @return mixed */
function is_literalipaddrv6($ipaddr) {}

/** @return mixed */
function is_ipaddrwithport($ipport) {}

/** @return mixed */
function is_hostnamewithport($hostport) {}

/** @return mixed */
function is_ipaddroralias($ipaddr) {}

/** @return mixed */
function is_subnet($subnet) {}

/** @return mixed */
function is_v4($ip_or_subnet) {}

/** @return mixed */
function is_v6($ip_or_subnet) {}

function is_v6gua(string $ip_or_subnet): bool {}

/** @return mixed */
function is_subnetv4($subnet) {}

/** @return mixed */
function is_subnetv6($subnet) {}

/** @return mixed */
function is_subnetoralias($subnet) {}

/** @return mixed */
function subnet_size($subnet, $exact=false) {}

/** @return mixed */
function subnet_size_by_netmask($iptype, $bits, $exact=false) {}

/** @return mixed */
function subnetv4_expand($subnet) {}

/** @return mixed */
function check_subnets_overlap($subnet1, $bits1, $subnet2, $bits2) {}

/** @return mixed */
function check_subnetsv4_overlap($subnet1, $bits1, $subnet2, $bits2) {}

/** @return mixed */
function check_subnetsv6_overlap($subnet1, $bits1, $subnet2, $bits2) {}

/** @return mixed */
function get_v6_ptr_zones($subnet, $bits) {}

/** @return mixed */
function ip_in_subnet($addr, $subnet) {}

/** @return mixed */
function is_unqualified_hostname($hostname) {}

/** @return mixed */
function is_hostname($hostname, $allow_wildcard=false) {}

/** @return mixed */
function is_domain($domain, $allow_wildcard=false, $trailing_dot=true) {}

/** @return mixed */
function is_macaddr($macaddr, $partial=false) {}

/** @return mixed */
function is_validaliasname($name, $return_message = false, $object = "alias") {}

/** @return mixed */
function invalidaliasnamemsg($name, $object = "alias") {}

/** @return mixed */
function is_intrange($range, $min, $max) {}

/** @return mixed */
function is_port($port) {}

/** @return mixed */
function is_port_in_use($port, $proto = "tcp", $ip_version = 4) {}

/** @return mixed */
function is_portrange($portrange) {}

/** @return mixed */
function is_port_or_range($port) {}

/** @return mixed */
function is_portalias($port) {}

/** @return mixed */
function is_port_or_alias($port) {}

/** @return mixed */
function is_port_or_range_or_alias($port) {}

/** @return mixed */
function group_ports($ports, $kflc = false) {}

/** @return mixed */
function is_valid_shaperbw($val) {}

/** @return mixed */
function is_inrange_v4($test, $start, $end) {}

/** @return mixed */
function is_inrange_v6($test, $start, $end) {}

/** @return mixed */
function is_inrange($test, $start, $end) {}

function is_ethertype(string $ethertype): bool {}

/** @return mixed */
function build_vip_list($fif, $family = "all") {}

/** @return mixed */
function get_configured_vip_list($family = 'all', $type = VIP_ALL) {}

/** @return mixed */
function get_configured_vip($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_interface($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_ipv4($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_ipv6($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_subnetv4($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_subnetv6($vipinterface = '') {}

/** @return mixed */
function get_configured_vip_detail($vipinterface = '', $family = 'inet', $what = 'ip') {}

/** @return mixed */
function compare_interface_friendly_names($a, $b) {}

function get_configured_interface_list(bool $with_disabled = false): array {}

function get_configured_interface_list_by_realif(bool $with_disabled = false): array {}

function get_configured_interface_with_descr(bool $with_disabled = false): array {}

/** @return mixed */
function get_configured_ip_addresses() {}

/** @return mixed */
function get_configured_ipv6_addresses($linklocal_fallback = false) {}

/** @return mixed */
function get_interface_list($mode = "active", $keyby = "physical", $vfaces = false) {}

/** @return mixed */
function get_lagg_interface_list() {}

/** @return mixed */
function log_auth($error) {}

/** @return mixed */
function exec_command($command) {}

/** @return mixed */
function mwexec($command, $nologentry = false, $clearsigmask = false, $background = false) {}

/** @return mixed */
function mwexec_bg($command, $clearsigmask = false) {}

/** @return mixed */
function unlink_if_exists($fn) {}

/** @return mixed */
function alias_make_table() {}

/** @return mixed */
function is_alias($name) {}

/** @return mixed */
function alias_get_type($name) {}

/** @return mixed */
function alias_expand($name) {}

/** @return mixed */
function alias_expand_urltable($name) {}

/** @return mixed */
function arp_get_mac_by_ip($ip, $do_ping = true) {}

/** @return mixed */
function xml_safe_fieldname($fieldname) {}

/** @return mixed */
function mac_format($clientmac) {}

/** @return mixed */
function resolve_retry($hostname, $protocol = 'inet') {}

/** @return mixed */
function format_bytes($bytes) {}

function format_number(int $num, int $precision = 3): string {}

/** @return mixed */
function unformat_number($formated_num) {}

/** @return mixed */
function update_filter_reload_status($text, $new=false) {}

/** @return mixed */
function return_dir_as_array($dir, $filter_regex = '') {}

/** @return mixed */
function run_plugins($directory) {}

/** @return mixed */
function safe_mkdir($path, $mode = 0755) {}

/** @return mixed */
function get_sysctl($names) {}

/** @return mixed */
function get_single_sysctl($name) {}

/** @return mixed */
function set_sysctl($values) {}

/** @return mixed */
function set_single_sysctl($name, $value) {}

/** @return mixed */
function get_memory() {}

/** @return mixed */
function get_php_default_memory($ARCH) {}

/** @return mixed */
function get_php_max_memory() {}

/** @return mixed */
function mute_kernel_msgs() {}

/** @return mixed */
function unmute_kernel_msgs() {}

/** @return mixed */
function start_devd() {}

/** @return mixed */
function is_interface_vlan_mismatch() {}

/** @return mixed */
function is_interface_mismatch() {}

/** @return mixed */
function carp_sync_client() {}

/** @return mixed */
function isAjax() {}

/** @return mixed */
function timeout($timer = 9) {}

/** @return mixed */
function msort($array, $id = "id", $sort_ascending = true) {}

/** @return mixed */
function is_URL($url, $httponly = false) {}

/** @return mixed */
function is_file_included($file = "") {}

/** @return mixed */
function array_replace_values_recursive($data, $match, $replace) {}

/** @return mixed */
function array_merge_recursive_unique($array0, $array1) {}

/** @return mixed */
function explode_assoc($delimiter, $string) {}

/** @return mixed */
function replace_element_in_list($text, $delimiter, $element, $replacement) {}

/** @return mixed */
function route_table() {}

function is_dynamic_route(string $target, string $ipprotocol = ''): bool {}

/** @return mixed */
function route_get($target, $ipprotocol = '', $useroute = false) {}

/** @return mixed */
function route_get_default($ipprotocol) {}

/** @return mixed */
function route_del($target, $ipprotocol = '') {}

/** @return mixed */
function route_add_or_change($target, $gw, $iface = '', $args = '', $ipprotocol = '') {}

/** @return mixed */
function set_ipv6routes_mtu($interface, $mtu) {}

/** @return mixed */
function alias_to_subnets_recursive($name, $returnhostnames = false) {}

/** @return mixed */
function get_staticroutes($returnsubnetsonly = false, $returnhostnames = false, $returnenabledroutesonly = false) {}

/** @return mixed */
function get_alias_list($type = null) {}

/** @return mixed */
function get_sorted_aliases() {}

/** @return mixed */
function array_exclude($needle, $haystack) {}

/** @return mixed */
function prefer_ipv4_or_ipv6() {}

/** @return mixed */
function post_redirect($page, $params) {}

/** @return mixed */
function get_smart_drive_list() {}

/** @return mixed */
function validateipaddr(&$addr, $type, $label, &$err_msg, $alias=false) {}

/** @return mixed */
function format_duid($duidtype, $duidpt1, $duidpt2=null) {}

/** @return mixed */
function is_duid($dhcp6duid) {}

/** @return mixed */
function write_dhcp6_duid($duidstring) {}

/** @return mixed */
function get_duid_from_file() {}

/** @return mixed */
function unixnewlines($text) {}

/** @return mixed */
function array_remove_duplicate($array, $field) {}

/** @return mixed */
function array_get_path(array &$arr, string $path, $default = null) {}

/** @return mixed */
function array_init_path(mixed &$arr, ?string $path) {}

/** @return mixed */
function array_set_path(array &$arr, string $path, $value, $default = null) {}

/** @return mixed */
function array_path_enabled(array &$arr, string $path, $enable_key = "enable") {}

/** @return mixed */
function array_del_path(array &$arr, string $path) {}

/** @return mixed */
function dhcpd_date_adjust_gmt($dt) {}

/** @return mixed */
function is_supported_image($image_filename) {}

/** @return mixed */
function get_lagg_ports ($laggport) {}

/** @return mixed */
function cisco_to_cidr($addr) {}

/** @return mixed */
function cisco_extract_index($prule) {}

/** @return mixed */
function parse_cisco_acl_rule($rule, $devname, $dir, $proto) {}

/** @return mixed */
function parse_cisco_acl($attribs, $dev) {}

/** @return mixed */
function alias_idn_to_utf8($alias) {}

/** @return mixed */
function alias_idn_to_ascii($alias) {}

/** @return mixed */
function address_to_pconfig($adr, &$padr, &$pmask, &$pnot, &$pbeginport, &$pendport) {}

/** @return mixed */
function pconfig_to_address(&$adr, $padr, $pmask, $pnot = false, $pbeginport = 0, $pendport = 0, $addmask = false, $specialnet_flags = []) {}

function get_specialnet(?string $net = '', array $flags = [], ?string $if = ''): bool|array {}

/** @return mixed */
function is_interface_ipaddr($interface) {}

/** @return mixed */
function is_interface_ipaddrv6($interface) {}

/** @return mixed */
function escape_filter_regex($filtertext) {}

/** @return mixed */
function is_pattern_balanced_char($pattern, $open, $close) {}

/** @return mixed */
function is_pattern_balanced($pattern) {}

/** @return mixed */
function cleanup_regex_pattern($filtertext) {}

/** @return mixed */
function ip6_to_asn1($addr) {}

/** @return mixed */
function interfaces_interrupts() {}

/** @return mixed */
function dummynet_load_module($max_qlimit) {}

/** @return mixed */
function get_interface_vip_ips($interface) {}

/** @return mixed */
function dhcp_is_backend($dhcpbackend) {}

/** @return mixed */
function dhcp_get_backend() {}

/** @return mixed */
function display_isc_warning() {}

/** @return mixed */
function have_natpfruleint_access($if) {}

/** @return mixed */
function have_ruleint_access($if) {}

/** @return mixed */
function does_url_exist($url) {}

/** @return mixed */
function is_private_ip($iptocheck) {}

/** @return mixed */
function get_tmp_file() {}

/** @return mixed */
function get_dns_servers() {}

/** @return mixed */
function pfSenseHeader($text) {}

/** @return mixed */
function get_css_files() {}

/** @return mixed */
function gen_webguicss_field(&$section, $value) {}

/** @return mixed */
function validate_webguicss_field(&$input_errors, $value) {}

/** @return mixed */
function gen_webguifixedmenu_field(&$section, $value) {}

/** @return mixed */
function validate_webguifixedmenu_field(&$input_errors, $value) {}

/** @return mixed */
function gen_webguihostnamemenu_field(&$section, $value) {}

/** @return mixed */
function validate_webguihostnamemenu_field(&$input_errors, $value) {}

/** @return mixed */
function gen_dashboardcolumns_field(&$section, $value) {}

/** @return mixed */
function validate_dashboardcolumns_field(&$input_errors, $value) {}

/** @return mixed */
function gen_interfacessort_field(&$section, $value) {}

/** @return mixed */
function gen_associatedpanels_fields(&$section, $value1, $value2, $value3, $value4) {}

/** @return mixed */
function gen_webguileftcolumnhyper_field(&$section, $value) {}

/** @return mixed */
function gen_disablealiaspopupdetail_field(&$section, $value) {}

/** @return mixed */
function gen_pagenamefirst_field(&$section, $value) {}

/** @return mixed */
function gen_user_settings_fields(&$section, $pconfig) {}

/** @return mixed */
function gen_requirestatefilter_field(&$section, $value) {}

/** @return mixed */
function gen_requirefirewallinterface_field(&$section, $value) {}

/** @return mixed */
function gen_created_updated_fields(&$form, $created, $updated, $tracker = 0) {}

/** @return mixed */
function hardware_offloading_applyflags($iface) {}

/** @return mixed */
function enable_hardware_offloading($interface) {}

/** @return mixed */
function is_alias_inuse($alias) {}

/** @return mixed */
function is_schedule_inuse($schedule) {}

/** @return mixed */
function setup_microcode() {}

/** @return mixed */
function get_carp_status() {}

/** @return mixed */
function enable_carp(bool $enable=true) {}

/** @return mixed */
function convert_ip_to_network_format($ip, $subnet) {}

/** @return mixed */
function get_carp_interface_status($carpid) {}

/** @return mixed */
function get_carp_bind_status($interface) {}

/** @return mixed */
function captiveportal_ha_is_node_in_backup_mode($cpzone) {}

/** @return mixed */
function WakeOnLan($addr, $mac) {}

/** @return mixed */
function reverse_strrchr($haystack, $needle) {}

/** @return mixed */
function backup_config_section($section_name) {}

/** @return mixed */
function restore_config_section($section_name, $new_contents) {}

/** @return mixed */
function merge_config_section($section_name, $new_contents) {}

/** @return mixed */
function rmdir_recursive($path, $follow_links=false) {}

/** @return mixed */
function host_firmware_version() {}

/** @return mixed */
function get_disk_info() {}

/** @return mixed */
function strncpy(&$dst, $src, $length) {}

/** @return mixed */
function reload_interfaces_sync() {}

/** @return mixed */
function reload_all() {}

/** @return mixed */
function reload_interfaces() {}

/** @return mixed */
function reload_all_sync() {}

/** @return mixed */
function load_loader_conf($loader_conf = NULL, $local = false) {}

/** @return mixed */
function setup_loader_settings($path = "", $upgrade = false) {}

/** @return mixed */
function console_configure($when = "save", $path = "") {}

/** @return mixed */
function is_serial_enabled() {}

/** @return mixed */
function reload_ttys() {}

/** @return mixed */
function print_value_list($list, $count = 10, $separator = ",") {}

/** @return mixed */
function is_dhcp_server_enabled() {}

/** @return mixed */
function is_dhcpv6_server_enabled() {}

/** @return mixed */
function is_radvd_enabled() {}

/** @return mixed */
function is_pppoe_server_enabled() {}

/** @return mixed */
function convert_seconds_to_dhms($sec, $showhoursonly = false) {}

/** @return mixed */
function get_ppp_uptime($port) {}

/** @return mixed */
function get_interface_info($ifdescr) {}

/** @return mixed */
function get_cpu_speed() {}

/** @return mixed */
function get_uptime_sec() {}

/** @return mixed */
function resolve_host_addresses($host, $recordtypes = array(DNS_A, DNS_AAAA, DNS_CNAME), $index = true) {}

/** @return mixed */
function add_hostname_to_watch($hostname) {}

/** @return mixed */
function is_fqdn($fqdn) {}

/** @return mixed */
function pfsense_default_state_size() {}

/** @return mixed */
function pfsense_current_tables_size() {}

/** @return mixed */
function pfsense_current_table_entries_size() {}

/** @return mixed */
function compare_hostname_to_dnscache($hostname) {}

/** @return mixed */
function load_crypto() {}

/** @return mixed */
function load_thermal_hardware() {}

/** @return mixed */
function isvm() {}

/** @return mixed */
function get_freebsd_version() {}

/** @return mixed */
function download_file($url, $destination, $verify_ssl = true, $connect_timeout = 5, $timeout = 0) {}

/** @return mixed */
function download_file_with_progress_bar($url, $destination, $verify_ssl = true, $readbody = 'read_body', $connect_timeout = 5, $timeout = 0) {}

/** @return mixed */
function read_header($ch, $string) {}

/** @return mixed */
function read_body($ch, $string) {}

/** @return mixed */
function update_output_window($text) {}

/** @return mixed */
function update_progress_bar($percent, $first_time) {}

/** @return mixed */
function update_alias_name($new_alias_name, $orig_alias_name) {}

/** @return mixed */
function update_alias_names_upon_change($section, $field, $new_alias_name, $origname) {}

/** @return mixed */
function parse_aliases_file($filename, $type = "url", $max_items = -1, $kflc = false) {}

/** @return mixed */
function update_alias_url_data() {}

/** @return mixed */
function process_alias_tgz($temp_filename) {}

/** @return mixed */
function version_compare_dates($a, $b) {}

/** @return mixed */
function version_get_string_value($a) {}

/** @return mixed */
function version_compare_string($a, $b) {}

/** @return mixed */
function version_compare_numeric($a, $b) {}

/** @return mixed */
function pfs_version_compare($cur_time, $cur_text, $remote) {}

/** @return mixed */
function process_alias_urltable($name, $type, $url, $freq, $forceupdate=false, $validateonly=false) {}

/** @return mixed */
function get_include_contents($filename) {}

/** @return mixed */
function xml2array($contents, $get_attributes = 1, $priority = 'tag') {}

/** @return mixed */
function get_country_name($country_code = "ALL") {}

/** @return mixed */
function get_cert_country_codes() {}

/** @return mixed */
function filter_rules_sort() {}

/** @return mixed */
function filter_rules_compare($a, $b) {}

/** @return mixed */
function generate_ipv6_from_mac($mac) {}

/** @return mixed */
function load_mac_manufacturer_table() {}

/** @return mixed */
function is_ipaddr_configured($ipaddr, $ignore_if = "", $check_localip = false, $check_subnets = false, $cidrprefix = "") {}

/** @return mixed */
function where_is_ipaddr_configured($ipaddr, $ignore_if = "", $check_localip = false, $check_subnets = false, $cidrprefix = "") {}

/** @return mixed */
function pfSense_handle_custom_code($src_dir) {}

/** @return mixed */
function set_language() {}

/** @return mixed */
function get_locale_list() {}

/** @return mixed */
function return_hex_ipv4($ipv4) {}

/** @return mixed */
function convert_ipv6_to_128bit($ipv6) {}

/** @return mixed */
function convert_128bit_to_ipv6($ip6bin) {}

/** @return mixed */
function calculate_ipv6_delegation_length($if) {}

/** @return mixed */
function merge_ipv6_delegated_prefix($prefix, $suffix, $len = 64) {}

/** @return mixed */
function dhcpv6_pd_str_help($pdlen) {}

/** @return mixed */
function huawei_rssi_to_string($rssi) {}

/** @return mixed */
function huawei_mode_to_string($mode, $submode) {}

/** @return mixed */
function huawei_service_to_string($state) {}

/** @return mixed */
function huawei_simstate_to_string($state) {}

/** @return mixed */
function zte_rssi_to_string($rssi) {}

/** @return mixed */
function zte_mode_to_string($mode, $submode) {}

/** @return mixed */
function zte_service_to_string($service) {}

/** @return mixed */
function zte_simstate_to_string($state) {}

/** @return mixed */
function get_configured_pppoe_server_interfaces() {}

/** @return mixed */
function get_pppoes_child_interfaces($ifpattern) {}

/** @return mixed */
function pkg_call_plugins($plugin_type, $plugin_params) {}

/** @return mixed */
function addrtolower($ip) {}

/** @return mixed */
function compare_by_name($a, $b) {}

/** @return mixed */
function send_user_download($type, $content, $userfilename = "", $contenttype = "application/octet-stream") {}

/** @return mixed */
function is_url_hostname_resolvable($url) {}

function get_pf_reserved(?string $name = '', bool $check_ifname = true): bool|array {}

/** @return mixed */
function get_pf_timeouts () {}

/** @return mixed */
function set_curlproxy(&$ch) {}

function g_has(string $key, bool $isset = false): bool {}

function g_get(string $key, mixed $default = null): mixed {}

function g_set(string $key, mixed $value, bool $force = false): mixed {}

function g_unset(string $key): void {}

function is_platform_booting(): bool {}

function is_cli_sapi(): bool {}

function platform_booting(bool $only_on_console = false): bool {}

function can_include(string $filename): bool {}

function get_ipprotocols(?string $type = ''): array {}
