<?php
/**
 * pfSense utility function stubs — IDE static analysis only (Intelephense).
 *
 * Auto-generated by scripts/update-pfsense-stubs.py; do not edit manually.
 * Reference: https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/util.inc
 *            https://github.com/pfsense/pfsense/blob/RELENG_2_8_0/src/etc/inc/pfsense-utils.inc
 */

// @codingStandardsIgnoreFile

// ── IP / Network validation ───────────────────────────────────────────────────

/** Return true if $ipaddr is a valid IPv4 or IPv6 address. */
function is_ipaddr(mixed $ipaddr): bool {}

/** Return true if $ipaddr is a valid IPv4 address. */
function is_ipaddrv4(mixed $ipaddr): bool {}

/** Return true if $ipaddr is a valid IPv6 address. */
function is_ipaddrv6(mixed $ipaddr): bool {}

/** Return true if $subnet is a valid IPv4 or IPv6 CIDR subnet. */
function is_subnet(mixed $subnet): bool {}

/** Return true if $subnet is a valid IPv4 CIDR subnet. */
function is_subnetv4(mixed $subnet): bool {}

/** Return true if $subnet is a valid IPv6 CIDR subnet. */
function is_subnetv6(mixed $subnet): bool {}

/** Return true if $ipaddr falls within an RFC-1918 private range. */
function is_private_ip(string $ipaddr): bool {}

/**
 * Return true if $ipaddr is configured on any interface (or a specific one).
 *
 * @param string      $ipaddr       Address to check.
 * @param string|null $ifcheck      Limit check to this interface; null = all.
 * @param bool        $incl_localip Include loopback/localhost addresses.
 * @param bool        $incl_subnets Match if $ipaddr falls within a subnet.
 * @param string|null $cidr         Override CIDR prefix length for subnet checks.
 */
function is_ipaddr_configured(
    string $ipaddr,
    ?string $ifcheck = null,
    bool $incl_localip = false,
    bool $incl_subnets = false,
    ?string $cidr = null
): bool {}

// ── Hostname / domain validation ─────────────────────────────────────────────

/**
 * Return true if $hostname is a valid DNS hostname.
 *
 * @param bool $allow_wildcard Allow a leading '*.' wildcard label.
 */
function is_hostname(string $hostname, bool $allow_wildcard = false): bool {}

/** Return true if $domain is a valid DNS domain name. */
function is_domain(string $domain): bool {}

// ── Port validation ───────────────────────────────────────────────────────────

/** Return true if $port is a valid TCP/UDP port number (1–65535). */
function is_port(mixed $port): bool {}

/** Return true if $portrange is a valid port range, e.g. '80:443'. */
function is_portrange(string $portrange): bool {}

// ── Interface helpers ─────────────────────────────────────────────────────────

/**
 * Return the primary IPv4 address of a pfSense interface.
 *
 * @param  string|null $interface Interface identifier (e.g. 'wan', 'lan'). Null defaults to WAN.
 * @return string|null
 */
function get_interface_ip(?string $interface = 'wan'): ?string {}

/**
 * Return the primary IPv6 address of a pfSense interface.
 *
 * @param  string|null $interface Interface identifier.
 * @return string|null
 */
function get_interface_ipv6(?string $interface = 'wan'): ?string {}

// ── Process / command execution ───────────────────────────────────────────────

/**
 * Execute $command and return its exit code.
 *
 * @param  bool $nologging Suppress logging of the command.
 */
function mwexec(string $command, bool $nologging = false): int {}

/**
 * Execute $command in the background (fire-and-forget).
 *
 * @param bool $nologging Suppress logging.
 */
function mwexec_bg(string $command, bool $nologging = false): void {}

/**
 * Execute $command and return its stdout as a trimmed string.
 */
function exec_command(string $command): string {}

/**
 * Return true if a process matching $process name is currently running.
 */
function is_process_running(string $process): bool {}

/**
 * Send SIGTERM (or $signal) to all processes matching $procname.
 *
 * @param  string $signal Signal name, e.g. 'TERM', 'HUP', 'KILL'.
 */
function killbyname(string $procname, string $signal = 'TERM'): bool {}

/**
 * Dispatch an event to the pfSense backend (e.g. 'filter reload').
 */
function send_event(string $cmd): void {}

// ── File system helpers ───────────────────────────────────────────────────────

/**
 * Create $path (and any missing parents) with mode $mode.
 *
 * @param  int  $mode Unix permission bits (default 0755).
 */
function safe_mkdir(string $path, int $mode = 0755): bool {}

/** Delete $fn if it exists; silently succeed if it does not. */
function unlink_if_exists(string $fn): void {}

// ── pfSense global array helpers ──────────────────────────────────────────────

/** Return the value of key $key from the pfSense global $g array. */
function g_get(string $key): mixed {}

/** Set key $key in the pfSense global $g array. */
function g_set(string $key, mixed $value): void {}

/** Remove key $key from the pfSense global $g array. */
function g_unset(string $key): void {}
