#!/bin/sh
# build-webassets.sh — rebuild the vendored Prism + code-input static assets
# (issue #1669) from tools/webassets/ into src/usr/local/www/pfblockerng/vendor/prism/.
#
# Node/npm are DEV+CI-ONLY: this script never runs on the pfSense appliance --
# only its emitted .js/.css output under src/ is loaded there. pfBlockerNG is a
# NO_BUILD FreeBSD port (make package / build-pkg-portable.py / deploy.sh copy
# src/ verbatim), so the committed vendor/ tree IS the build artifact; this
# script is how it is regenerated, and CI's drift guard (scripts/
# check_webassets_vendor.py) re-runs it and diffs the result against what's
# committed.
#
# Usage:
#   ./scripts/build-webassets.sh
#
# The script must be run from anywhere inside the pfBlockerNG repository.

set -eu

REPO_ROOT="$(CDPATH='' cd "$(dirname "$0")/.." && pwd)"
TOOLS_DIR="${REPO_ROOT}/tools/webassets"
VENDOR_DIR="${REPO_ROOT}/src/usr/local/www/pfblockerng/vendor/prism"

echo "==> Installing tools/webassets/ (npm ci)"
(cd "$TOOLS_DIR" && npm ci --no-audit --no-fund)

ESBUILD="${TOOLS_DIR}/node_modules/.bin/esbuild"
NODE_MODULES="${TOOLS_DIR}/node_modules"

mkdir -p "$VENDOR_DIR"

# Deterministic minified IIFE bundles -- no banners/timestamps, stable across
# runs (esbuild's own minifier output is content-addressed; verified by CI
# re-running this script and diffing against the committed tree).
echo "==> Bundling prism-regex.min.js"
"$ESBUILD" "${TOOLS_DIR}/prism-regex.js" --bundle --minify --format=iife \
    --outfile="${VENDOR_DIR}/prism-regex.min.js"

echo "==> Bundling prism-code.min.js"
"$ESBUILD" "${TOOLS_DIR}/prism-code.js" --bundle --minify --format=iife \
    --outfile="${VENDOR_DIR}/prism-code.min.js"

echo "==> Copying code-input's prebuilt standalone bundle"
cp "${NODE_MODULES}/@webcoder49/code-input/code-input.min.js" "${VENDOR_DIR}/code-input.min.js"
cp "${NODE_MODULES}/@webcoder49/code-input/code-input.min.css" "${VENDOR_DIR}/code-input.min.css"

echo "==> Copying Prism's default theme CSS"
cp "${NODE_MODULES}/prismjs/themes/prism.min.css" "${VENDOR_DIR}/prism.min.css"

PRISM_VERSION="$(node -e "console.log(require('${NODE_MODULES}/prismjs/package.json').version)")"
CODE_INPUT_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@webcoder49/code-input/package.json').version)")"

echo "==> Writing LICENSES.md (prismjs ${PRISM_VERSION}, code-input ${CODE_INPUT_VERSION})"
cat > "${VENDOR_DIR}/LICENSES.md" <<EOF
# Vendored asset licenses

Regenerated by \`scripts/build-webassets.sh\` (issue #1669) -- do not hand-edit.

## Prism

- Version: ${PRISM_VERSION}
- License: MIT
- Source: <https://github.com/PrismJS/prism>

$(cat "${NODE_MODULES}/prismjs/LICENSE")

## code-input

- Version: ${CODE_INPUT_VERSION}
- License: MIT
- Source: <https://github.com/WebCoder49/code-input>

$(cat "${NODE_MODULES}/@webcoder49/code-input/LICENSE")
EOF

echo "==> Writing MANIFEST.sha256"
MANIFEST="${VENDOR_DIR}/MANIFEST.sha256"
: > "$MANIFEST"
for f in prism-regex.min.js prism-code.min.js prism.min.css code-input.min.js code-input.min.css LICENSES.md; do
    digest="$(node -e "
const crypto = require('crypto');
const fs = require('fs');
process.stdout.write(crypto.createHash('sha256').update(fs.readFileSync(process.argv[1])).digest('hex'));
" "${VENDOR_DIR}/${f}")"
    printf '%s  %s\n' "$digest" "$f" >> "$MANIFEST"
done

echo "==> Done. Vendor tree: ${VENDOR_DIR}"
