#!/bin/sh
# build-webassets.sh — rebuild the vendored CodeMirror 6 regex-list editor bundle
# (issue #1669) from tools/webassets/ into
# src/usr/local/www/pfblockerng/vendor/codemirror/.
#
# Node/npm are DEV+CI-ONLY: this script never runs on the pfSense appliance --
# only its emitted .js output under src/ is loaded there. pfBlockerNG is a
# NO_BUILD FreeBSD port (make package / build-pkg-portable.py / deploy.sh copy
# src/ verbatim), so the committed vendor/ tree IS the build artifact; this
# script is how it is regenerated, and CI's drift guard (scripts/
# check_webassets_vendor.py) re-runs it and diffs the result against what's
# committed.
#
# Usage:
#   ./scripts/build-webassets.sh
#
# The script must be run from anywhere inside the pfBlockerNG repository.

set -eu

REPO_ROOT="$(CDPATH='' cd "$(dirname "$0")/.." && pwd)"
TOOLS_DIR="${REPO_ROOT}/tools/webassets"
VENDOR_DIR="${REPO_ROOT}/src/usr/local/www/pfblockerng/vendor/codemirror"

echo "==> Installing tools/webassets/ (npm ci)"
(cd "$TOOLS_DIR" && npm ci --no-audit --no-fund)

# Upstream defects we carry a fix for until the release that lands them (issue #1870:
# the mobile caret rescue in @codemirror/view moves the HORIZONTAL scroll position by
# the gutter's width on every keystroke with the on-screen keyboard open). npm ci wipes
# node_modules above, so these apply to a pristine tree every run; a patch that stops
# applying after a dependency bump fails the build here rather than silently reverting
# the fix in the shipped bundle. -F 0 is what makes that strict: patch(1)'s default
# fuzz factor would let a hunk whose context has drifted apply at a guessed location
# and still exit 0. -f keeps it non-interactive, so a mismatch fails instead of
# prompting. Both are portable to BSD patch(1); --fuzz=0 would not be.
if [ -d "${TOOLS_DIR}/patches" ]; then
    for _patch in "${TOOLS_DIR}"/patches/*.patch; do
        [ -f "$_patch" ] || continue
        echo "==> Applying $(basename "$_patch")"
        patch -f -F 0 -p1 -d "$TOOLS_DIR" -i "$_patch"
    done
fi

ESBUILD="${TOOLS_DIR}/node_modules/.bin/esbuild"
NODE_MODULES="${TOOLS_DIR}/node_modules"

echo "==> Generating the Lezer grammar parsers"
(cd "${TOOLS_DIR}/lezer-regexp" && npm run generate)
(cd "${TOOLS_DIR}/lezer-pfb-regex-list" && npm run generate)

mkdir -p "$VENDOR_DIR"

# Deterministic minified IIFE bundle -- no banners/timestamps, stable across
# runs (esbuild's own minifier output is content-addressed; verified by CI
# re-running this script and diffing against the committed tree).
echo "==> Bundling cm-regex.min.js"
"$ESBUILD" "${TOOLS_DIR}/cm-regex.js" --bundle --minify --format=iife --global-name=pfbCM \
    --outfile="${VENDOR_DIR}/cm-regex.min.js"

# issue #1669 -- a SEPARATE bundle from cm-regex.min.js (owner
# decision: keep the regex-list bundle small), python + shell modes only.
echo "==> Bundling cm-hooks.min.js"
"$ESBUILD" "${TOOLS_DIR}/cm-hooks.js" --bundle --minify --format=iife --global-name=pfbHooksCM \
    --outfile="${VENDOR_DIR}/cm-hooks.min.js"

CM_STATE_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/state/package.json').version)")"
CM_VIEW_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/view/package.json').version)")"
CM_LANGUAGE_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/language/package.json').version)")"
CM_COMMANDS_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/commands/package.json').version)")"
CM_LANG_PYTHON_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/lang-python/package.json').version)")"
CM_LEGACY_MODES_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/legacy-modes/package.json').version)")"
CM_LINT_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@codemirror/lint/package.json').version)")"
LEZER_COMMON_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@lezer/common/package.json').version)")"
LEZER_HIGHLIGHT_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@lezer/highlight/package.json').version)")"
LEZER_LR_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@lezer/lr/package.json').version)")"
LEZER_PYTHON_VERSION="$(node -e "console.log(require('${NODE_MODULES}/@lezer/python/package.json').version)")"

echo "==> Writing LICENSES.md"
cat > "${VENDOR_DIR}/LICENSES.md" <<EOF
# Vendored asset licenses

Regenerated by \`scripts/build-webassets.sh\` (issue #1669) -- do not hand-edit.

## CodeMirror 6

- Packages: @codemirror/state ${CM_STATE_VERSION}, @codemirror/view ${CM_VIEW_VERSION},
  @codemirror/language ${CM_LANGUAGE_VERSION}, @codemirror/commands ${CM_COMMANDS_VERSION},
  @codemirror/lang-python ${CM_LANG_PYTHON_VERSION} (cm-hooks.min.js, Python mode),
  @codemirror/legacy-modes ${CM_LEGACY_MODES_VERSION} (cm-hooks.min.js, shell mode --
  no official @codemirror/lang-shell package exists),
  @codemirror/lint ${CM_LINT_VERSION} (both bundles, issue #1732 advisory lint wiring)
- License: MIT
- Source: <https://github.com/codemirror/dev>

$(cat "${NODE_MODULES}/@codemirror/state/LICENSE")

## Lezer

- Packages: @lezer/common ${LEZER_COMMON_VERSION}, @lezer/highlight ${LEZER_HIGHLIGHT_VERSION},
  @lezer/lr ${LEZER_LR_VERSION}, @lezer/python ${LEZER_PYTHON_VERSION} (cm-hooks.min.js,
  via @codemirror/lang-python)
- License: MIT
- Source: <https://github.com/lezer-parser>

$(cat "${NODE_MODULES}/@lezer/common/LICENSE")

## In-repo grammars

\`tools/webassets/lezer-regexp/\` (Python \`re\` dialect) and
\`tools/webassets/lezer-pfb-regex-list/\` (the pfBlockerNG list-format outer grammar) are
project code, not vendored third-party assets -- they follow pfBlockerNG's own license,
not this file.
EOF

echo "==> Writing MANIFEST.sha256"
MANIFEST="${VENDOR_DIR}/MANIFEST.sha256"
# "true >" not ": >" -- ":" is a POSIX special builtin, so a redirection error on it (e.g.
# a crash-leftover directory at $MANIFEST) exits the whole strict-POSIX shell instead of
# just failing this one command (issue #1172; tests/shell/pfblockerng_truncate_survival_spec.sh).
true > "$MANIFEST"
for f in cm-regex.min.js cm-hooks.min.js LICENSES.md; do
    digest="$(node -e "
const crypto = require('crypto');
const fs = require('fs');
process.stdout.write(crypto.createHash('sha256').update(fs.readFileSync(process.argv[1])).digest('hex'));
" "${VENDOR_DIR}/${f}")"
    printf '%s  %s\n' "$digest" "$f" >> "$MANIFEST"
done

echo "==> Done. Vendor tree: ${VENDOR_DIR}"
