#!/bin/sh
# scripts/module-durations.sh — build a per-module test-duration table from
# pytest `--durations=0` log output (issue #816), so the live-VM smoke suite
# can shard by measured LOAD instead of blind round-robin (scripts/shard-modules.sh
# consumes the table produced here; that consumer is a separate step).
#
# Usage: module-durations.sh <pytest-log>...
#
# Feed ALL shard logs of exactly ONE full `-m smoke` run (e.g. every leg of a
# single CI dispatch) -- feeding the same run's logs twice, or mixing logs
# from two different runs, double-counts/skews the table. Regenerate:
#   scripts/module-durations.sh shard0.log shard1.log ... > tests/smoke/module-durations.txt
#
# A pytest duration line looks like (CI adds a log-line prefix before the
# timestamp; the payload is matched anywhere in the line, not anchored at
# start):
#   ...	2026-07-04T08:16:37.4994425Z 95.01s call     tests/smoke/test_x.py::test_y
#
# All three phases (setup/call/teardown) are summed per module BASENAME
# (`tests/smoke/test_x.py` -> `test_x.py`); pytest hides durations < 0.005s,
# negligible for sharding. Output: a short generated-by header (no
# timestamps/run-ids, so re-running on the same input is byte-identical),
# then one `<module> <seconds>` line per module (%.2f), sorted under
# `LC_ALL=C` for determinism (ADR-26). The committed table lives at
# tests/smoke/module-durations.txt.
#
# Errors loudly (non-zero exit, one-line stderr message) on: no args; an
# unreadable input file; or zero duration lines found across all inputs.

set -eu

usage() {
	printf 'usage: module-durations.sh <pytest-log>...\n' >&2
	exit 1
}

[ "$#" -ge 1 ] || usage

for f in "$@"; do
	[ -r "$f" ] || {
		printf 'module-durations: cannot read input file: %s\n' "$f" >&2
		exit 1
	}
done

# One-pass awk: for each duration line, sum the phase seconds into a
# per-module-basename table. A nodeid can itself contain further `::`
# (class-based tests, e.g. test_x.py::TestFoo::test_bar), so split the
# matched token on `::` and keep only the first piece (the module path) --
# never rely on the LAST `::` (a greedy `[^ \t]+::` would match through it).
durations="$(awk '
	match($0, /[0-9]+\.[0-9]+s[ \t]+(setup|call|teardown)[ \t]+[^ \t]+/) {
		line = substr($0, RSTART, RLENGTH)
		split(line, parts, /[ \t]+/)
		dur = parts[1]
		sub(/s$/, "", dur)
		split(parts[3], pieces, "::")
		modpath = pieces[1]
		sub(/^.*\//, "", modpath)
		sum[modpath] += dur
		found = 1
	}
	END {
		if (!found) exit 2
		for (m in sum) printf "%s %.2f\n", m, sum[m]
	}
' "$@")" || {
	status=$?
	if [ "$status" -eq 2 ]; then
		printf 'module-durations: no duration lines found in input\n' >&2
	fi
	exit 1
}

printf '# Generated by scripts/module-durations.sh from a full "-m smoke" run (issue #816).\n'
printf '# Feed every shard log of ONE run -- feeding the same run twice double-counts.\n'
printf '# Regenerate: scripts/module-durations.sh <log>... > tests/smoke/module-durations.txt\n'
printf '%s\n' "$durations" | LC_ALL=C sort
