#!/bin/sh
# scripts/module-durations.sh — build a per-module test-duration table from
# pytest `--durations=0` log output (issue #816), so the live-VM smoke suite
# can shard by measured LOAD instead of blind round-robin (scripts/shard-modules.sh
# consumes the table produced here; that consumer is a separate step).
#
# Usage: module-durations.sh <pytest-log>...
#
# Feed the DISJOINT shard logs of ONE leg-version's full `-m smoke` coverage
# (e.g. the CE shard logs of a single dispatch). A second leg that re-runs the
# whole suite (the Plus leg) is NOT disjoint -- including it double-counts
# every test, and CE-vs-Plus timings skew non-uniformly. Feeding the same
# run's logs twice, or mixing runs, skews the table the same way. Regenerate:
#   scripts/module-durations.sh shard0.log shard1.log ... > tests/smoke/module-durations.txt
#
# A pytest duration line looks like (CI adds a log-line prefix before the
# timestamp; the payload is matched anywhere in the line, not anchored at
# start):
#   ...	2026-07-04T08:16:37.4994425Z 95.01s call     tests/smoke/test_x.py::test_y
#
# All three phases (setup/call/teardown) are summed, at TWO granularities,
# from the same lines (issue #855): per module BASENAME (`tests/smoke/test_x.py`
# -> `test_x.py`), AND per individual test (`test_x.py::test_y`, keeping
# everything after the module filename verbatim -- including a class-based
# nodeid's extra `::` segment, e.g. `test_x.py::TestFoo::test_bar`). Output is
# ONE table with both row kinds: a short generated-by header (no
# timestamps/run-ids, so re-running on the same input is byte-identical),
# then `<module> <seconds>` lines (module sums) interleaved with
# `<module>::<test> <seconds>` lines (per-test sums), all sorted under
# `LC_ALL=C` (ADR-26) -- which incidentally clusters each module's own sum
# line directly ahead of its per-test lines (`' '` < `':'`). pytest hides
# durations < 0.005s, negligible for sharding. The committed table lives at
# tests/smoke/module-durations.txt; scripts/shard-modules.sh reads the
# per-test rows to split an oversized module at test granularity (issue #855).
#
# Errors loudly (non-zero exit, one-line stderr message) on: no args; an
# unreadable input file; or zero duration lines found across all inputs.

set -eu

usage() {
	printf 'usage: module-durations.sh <pytest-log>...\n' >&2
	exit 1
}

[ "$#" -ge 1 ] || usage

for f in "$@"; do
	if [ ! -f "$f" ] || [ ! -r "$f" ]; then
		printf 'module-durations: cannot read input file: %s\n' "$f" >&2
		exit 1
	fi
done

# One-pass awk: for each duration line, sum the phase seconds into a
# per-module-basename table AND a per-(module,test) table. A nodeid can
# itself contain further `::` (class-based tests, e.g.
# test_x.py::TestFoo::test_bar), so split on the FIRST `::` only (`index`/
# `substr`, not `split`) and keep the remainder verbatim as the test id --
# never rely on the LAST `::` (a greedy `[^ \t]+::` would match through it).
# The match itself is anchored to the phase keyword's trailing whitespace,
# NOT the next whitespace-delimited token: a parametrized nodeid can carry
# its OWN space (e.g. test_x.py::test_foo[hello world]), and capturing only
# "the next token" would silently truncate it there, corrupting the row
# (issue #861 nitpick) -- the nodeid is instead everything from that point to
# end of line, trimmed of trailing whitespace.
durations="$(LC_ALL=C awk '
	match($0, /[0-9]+\.[0-9]+s[ \t]+(setup|call|teardown)[ \t]+/) {
		hdr = substr($0, RSTART, RLENGTH)
		dur = hdr
		sub(/s[ \t].*/, "", dur)
		nodeid = substr($0, RSTART + RLENGTH)
		sub(/[ \t]+$/, "", nodeid)
		sep = index(nodeid, "::")
		modpath = (sep > 0) ? substr(nodeid, 1, sep - 1) : nodeid
		sub(/^.*\//, "", modpath)
		sum[modpath] += dur
		if (sep > 0) {
			testid = substr(nodeid, sep + 2)
			tsum[modpath, testid] += dur
		}
		found = 1
	}
	END {
		if (!found) exit 2
		for (m in sum) printf "%s %.2f\n", m, sum[m]
		for (combined in tsum) {
			split(combined, kk, SUBSEP)
			printf "%s::%s %.2f\n", kk[1], kk[2], tsum[combined]
		}
	}
' "$@")" || {
	status=$?
	if [ "$status" -eq 2 ]; then
		# awk itself also exits 2 on a fatal error (its own stderr message is
		# already on the terminal then), so this wording covers the common
		# case (clean parse, zero matches) without hiding a crash.
		printf 'module-durations: no duration lines found in input\n' >&2
	else
		printf 'module-durations: awk parse failed (exit %s)\n' "$status" >&2
	fi
	exit 1
}

printf '# Generated by scripts/module-durations.sh from a full "-m smoke" run (issue #816).\n'
printf '# Feed the DISJOINT shard logs of ONE leg-version (CE shards of one dispatch); a Plus leg or a repeat log double-counts.\n'
printf '# Regenerate: scripts/module-durations.sh <log>... > tests/smoke/module-durations.txt\n'
printf '%s\n' "$durations" | LC_ALL=C sort
