#!/usr/bin/env python3
"""
update-pfsense-stubs.py — regenerate PHP stubs from pfSense CE source.

Downloads the pfSense CE source files for a given release tag, extracts every
top-level function declaration, and writes stub PHP files to stubs/pfsense/.
The stubs let Intelephense resolve pfSense functions without needing the
pfSense source tree locally.

Usage:
    python scripts/update-pfsense-stubs.py [--version X.Y.Z] [--output DIR] [--dry-run]

The default version is the minimum pfSense CE release supported by this package.
Run this script whenever the minimum supported pfSense CE version is bumped or
when pfSense API functions used by pfBlockerNG change signature.

Note: globals.php is manually maintained and is never overwritten by this script.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

PFSENSE_REPO = "pfsense/pfsense"
RAW_URL = "https://raw.githubusercontent.com/{repo}/{tag}/src/etc/inc/{file}"

# Default: minimum pfSense CE version supported by this package.
# Update this constant when bumping the minimum supported version.
MIN_PFSENSE_VERSION = "2.8.0"

# Map output stub filename → pfSense include files to parse for that module.
STUB_MODULES: dict[str, list[str]] = {
    "config.php":    ["config.lib.inc"],
    "util.php":      ["util.inc", "pfsense-utils.inc"],
    "services.php":  ["services.inc", "service-utils.inc", "pkg-utils.inc"],
    "system.php":    ["functions.inc", "filter.inc"],
    "guiconfig.php": ["guiconfig.inc"],
    # logging.php is derived from util.inc (already covered above); the hand-
    # crafted version covers the gettext/file_notice subset used by pfBlockerNG.
}

STUB_HEADER_TEMPLATE = """\
<?php
/**
 * pfSense {module} stubs — IDE static analysis only (Intelephense).
 *
 * AUTO-GENERATED by scripts/update-pfsense-stubs.py from pfSense CE {version}
 * (tag {tag}).
 *
 * Source files:
{source_list}
 *
 * Do NOT edit manually — re-run the script after a pfSense version bump.
 * These files are in stubs/ which is excluded from release archives.
 */

// @codingStandardsIgnoreFile

"""


# ── Version → tag conversion ──────────────────────────────────────────────────

def version_to_tag(version: str) -> str:
    """Convert dotted version to a pfSense RELENG tag: '2.8.0' → 'RELENG_2_8_0'."""
    return "RELENG_" + version.replace(".", "_")


# ── Source fetching ───────────────────────────────────────────────────────────

def fetch_source(tag: str, filename: str) -> str | None:
    """Fetch a raw pfSense source file from GitHub. Returns None on failure."""
    url = RAW_URL.format(repo=PFSENSE_REPO, tag=tag, file=filename)
    try:
        with urllib.request.urlopen(url, timeout=20) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        print(f"    WARNING: {filename}: HTTP {exc.code} — {url}", file=sys.stderr)
    except Exception as exc:
        print(f"    WARNING: {filename}: {exc}", file=sys.stderr)
    return None


# ── Function extraction ───────────────────────────────────────────────────────

# Matches the start of a standalone (non-method) function declaration.
# Excludes access-modifier prefixes (public/protected/private/abstract/static)
# which indicate a class method.
_FUNC_START_RE = re.compile(
    r'^(?![ \t]*(?:public|protected|private|abstract|static)\s)'
    r'[ \t]*function[ \t]+(\w+)[ \t]*\(',
    re.MULTILINE,
)

# Matches an optional return-type annotation followed by the opening brace.
# Handles nullable (?T), union (A|B), intersection (A&B), and namespaced types.
_RETURN_TYPE_RE = re.compile(
    r'\s*(?::\s*([\?\\a-zA-Z0-9_|&\[\]]+(?:\|[\?\\a-zA-Z0-9_|&\[\]]+)*))?\s*\{'
)


def _collect_params(source: str, open_paren: int) -> int | None:
    """
    Walk forward from the opening '(' at *open_paren*, tracking nesting depth,
    and return the index of the matching ')'.  Returns None if not found within
    a reasonable look-ahead window (handles malformed source gracefully).
    """
    depth = 0
    for i in range(open_paren, min(open_paren + 8192, len(source))):
        ch = source[i]
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                return i
    return None


def extract_functions(source: str) -> list[str]:
    """
    Extract top-level PHP function declarations from *source* and return them
    as stub strings (empty bodies, return types preserved where present).
    """
    stubs: list[str] = []

    for m in _FUNC_START_RE.finditer(source):
        fn_start = m.start()

        # Locate the opening '(' — guaranteed by the regex.
        open_paren = source.index('(', fn_start)
        close_paren = _collect_params(source, open_paren)
        if close_paren is None:
            continue

        # Look for optional return type and the opening '{'.
        after_params = source[close_paren + 1 : close_paren + 512]
        ret_match = _RETURN_TYPE_RE.match(after_params)
        if ret_match is None:
            # No '{' found — probably an interface/abstract declaration or
            # a function call that fooled the heuristic; skip.
            continue

        ret_type: str | None = ret_match.group(1)

        # Build and normalise the signature (collapse internal whitespace).
        raw_sig = source[fn_start : close_paren + 1]
        sig = re.sub(r'\s+', ' ', raw_sig).strip()

        if ret_type:
            stubs.append(f"{sig}: {ret_type} {{}}")
        else:
            stubs.append(f"/** @return mixed */\n{sig} {{}}")

    return stubs


# ── Stub file writer ──────────────────────────────────────────────────────────

def write_stub_file(
    path: Path,
    module: str,
    version: str,
    tag: str,
    source_files: list[str],
    functions: list[str],
    dry_run: bool,
) -> None:
    source_list = "\n".join(f" *   {f}" for f in source_files)
    header = STUB_HEADER_TEMPLATE.format(
        module=module.removesuffix(".php"),
        version=version,
        tag=tag,
        source_list=source_list,
    )
    content = header + "\n\n".join(functions) + "\n"

    if dry_run:
        print(f"    [dry-run] would write {path} ({len(functions)} stubs)")
        return

    path.write_text(content, encoding="utf-8")
    print(f"    Wrote {path.name} ({len(functions)} stubs)")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        default=MIN_PFSENSE_VERSION,
        metavar="X.Y.Z",
        help=f"pfSense CE version to fetch (default: {MIN_PFSENSE_VERSION}, the minimum supported version)",
    )
    parser.add_argument(
        "--output",
        default="stubs/pfsense",
        metavar="DIR",
        help="Output directory for generated stubs (default: stubs/pfsense)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse sources and report what would be written; make no changes",
    )
    args = parser.parse_args()

    tag = version_to_tag(args.version)
    out_dir = Path(args.output)

    print(f"pfSense CE {args.version}  →  tag {tag}")
    print(f"Output directory: {out_dir}/")
    print()

    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    # globals.php is manually maintained — never overwrite.
    globals_path = out_dir / "globals.php"
    if globals_path.exists():
        print("  globals.php — skipped (manually maintained; edit by hand)")
    else:
        print("  globals.php — not found; create it or run without --output to use the default")
    print()

    total_stubs = 0
    errors = 0

    for stub_file, source_files in STUB_MODULES.items():
        print(f"  {stub_file}")
        all_functions: list[str] = []

        for src_file in source_files:
            print(f"    fetching {src_file} ...", end=" ", flush=True)
            source = fetch_source(tag, src_file)
            if source is None:
                errors += 1
                continue
            funcs = extract_functions(source)
            print(f"{len(funcs)} functions")
            all_functions.extend(funcs)

        if not all_functions:
            print(f"    WARNING: no functions extracted; {stub_file} will be empty")

        write_stub_file(
            path=out_dir / stub_file,
            module=stub_file,
            version=args.version,
            tag=tag,
            source_files=source_files,
            functions=all_functions,
            dry_run=args.dry_run,
        )
        total_stubs += len(all_functions)
        print()

    print(f"Done — {total_stubs} total stubs across {len(STUB_MODULES)} files", end="")
    if errors:
        print(f", {errors} source file(s) could not be fetched (see warnings above)", end="")
    print(".")

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
