#!/usr/bin/env python3
"""
update-unicode-data.py — regenerate the shipped TR39 Scripts/Script_Extensions
range tables from a pinned Unicode version.

ADR-08 (cross-script IDN homoglyph protection) decides whether an ``xn--`` label
mixes mutually-confusable scripts. That needs each code point's **Script** and
**Script_Extensions** property, and ``unicodedata`` (stdlib) exposes neither. So
this dev tool downloads a PINNED Unicode version's ``Scripts.txt`` +
``ScriptExtensions.txt`` (+ ``PropertyValueAliases.txt`` to expand the
abbreviated script codes used by ScriptExtensions) and emits a COMPACT,
binary-searchable range table as a shipped Python data module
(``src/usr/local/pkg/pfblockerng/pfb_unicode_scripts.py``).

Pattern mirrors ``scripts/update-pfsense-stubs.py``: download a pinned source ->
emit data. The emitted module is small (ranges, not per-code-point) and is
imported by the pure analyzer in ``pfb_idn_analyzer.py``.

Usage:
    python scripts/update-unicode-data.py [--version X.Y.Z] [--output FILE] [--dry-run]

The Unicode version is pinned (UNICODE_VERSION). Re-running with the same version
reproduces the committed data module byte-for-byte (the emission is fully sorted
and deterministic). Bump UNICODE_VERSION (and re-run) when the table is refreshed;
record the version in README/CLAUDE.md per ADR-08.
"""

from __future__ import annotations

import argparse
import re
import urllib.error
import urllib.request
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

# The PINNED Unicode version. Matches the dev box's stdlib ``unicodedata``
# (UCD 15.1.0) and the ADR-08 corpus/spec ``ucd_version`` — so the shipped tables,
# the Phase-1 corpus and the Phase-2 oracle all agree on the same UCD release.
UNICODE_VERSION = "15.1.0"

UCD_BASE_URL = "https://www.unicode.org/Public/{version}/ucd/{file}"

# The data module emitted under the package dir (shipped in the release archive).
DEFAULT_OUTPUT = "src/usr/local/pkg/pfblockerng/pfb_unicode_scripts.py"

# Scripts that carry no script identity for confusable analysis — UTS#39 treats
# Common/Inherited as transparent (they contribute no script to the resolved set).
# ``Unknown`` (unassigned / no script) is likewise not a letter-script. They are
# dropped at emit time so the shipped tables never carry a transparent range.
_TRANSPARENT = frozenset({"Common", "Inherited", "Unknown"})

_MODULE_HEADER = """\
# pfb_unicode_scripts.py
# pfBlockerNG - shipped Unicode Script / Script_Extensions range tables (ADR-08).
#
# AUTO-GENERATED by scripts/update-unicode-data.py from Unicode {version}
# (Scripts.txt + ScriptExtensions.txt + PropertyValueAliases.txt). DO NOT EDIT BY
# HAND — re-run the generator to refresh, and bump UNICODE_VERSION there.
#
# Compact, binary-searchable range tables for the TR39 mixed-script analyzer
# (pfb_idn_analyzer.py). Common / Inherited / Unknown ranges are DROPPED at
# generation time: UTS#39 treats them as transparent (no script identity), so a
# code point absent from both tables contributes no script to the resolved set.
#
# Layout (parallel sorted arrays, looked up with bisect):
#   SCRIPT_RANGE_STARTS[i] .. SCRIPT_RANGE_ENDS[i]  -> SCRIPT_RANGE_NAMES[i]
#     the plain Script property (one script name per range), and
#   SCRIPTX_RANGE_STARTS[i] .. SCRIPTX_RANGE_ENDS[i] -> SCRIPTX_RANGE_NAMES[i]
#     the Script_Extensions property (a tuple of script names per range; takes
#     precedence over the plain Script when a code point has it).
# This file ships in the release archive (under src/); it is NOT a dev-only stub.

from __future__ import annotations

UNICODE_VERSION = "{version}"

"""


# ── Source fetching ───────────────────────────────────────────────────────────


def fetch_ucd(version: str, file: str) -> str:
    """Fetch a raw UCD data file from unicode.org for *version*. Raises on failure."""
    url = UCD_BASE_URL.format(version=version, file=file)
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="strict")
    except urllib.error.HTTPError as exc:
        raise SystemExit(f"ERROR: {file}: HTTP {exc.code} — {url}") from exc
    except Exception as exc:  # noqa: BLE001 - report any fetch failure and stop
        raise SystemExit(f"ERROR: {file}: {exc} — {url}") from exc


# ── Parsing ───────────────────────────────────────────────────────────────────

# A UCD data line: "0041..005A ; Latin # ..." or "0024 ; Common # ...".
_DATA_LINE_RE = re.compile(r"^\s*([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([^#]+?)\s*(?:#.*)?$")

# A PropertyValueAliases "sc" line: "sc ; Latn ; Latin".
_PVA_SC_RE = re.compile(r"^sc\s*;\s*(\w+)\s*;\s*(\w+)")


def parse_alias_map(pva_text: str) -> dict[str, str]:
    """Build {abbreviation -> long Script name} from PropertyValueAliases.txt.

    ScriptExtensions.txt lists scripts by their 4-letter abbreviation (``Latn``,
    ``Cyrl``, …); the analyzer + the rest of the UCD use the long name (``Latin``,
    ``Cyrillic``). The long name is mapped to itself too, so a value already long
    resolves cleanly.
    """
    aliases: dict[str, str] = {}
    for line in pva_text.splitlines():
        m = _PVA_SC_RE.match(line.strip())
        if m:
            abbr, long = m.group(1), m.group(2)
            aliases[abbr] = long
            aliases[long] = long
    return aliases


def parse_scripts(text: str) -> list[tuple[int, int, str]]:
    """Parse Scripts.txt -> sorted [(start, end, script_long_name)], transparent dropped."""
    out: list[tuple[int, int, str]] = []
    for line in text.splitlines():
        m = _DATA_LINE_RE.match(line)
        if not m:
            continue
        start = int(m.group(1), 16)
        end = int(m.group(2), 16) if m.group(2) else start
        script = m.group(3).strip()
        if script in _TRANSPARENT:
            continue
        out.append((start, end, script))
    out.sort(key=lambda r: r[0])
    return _merge_scalar(out)


def parse_script_extensions(text: str, aliases: dict[str, str]) -> list[tuple[int, int, tuple[str, ...]]]:
    """Parse ScriptExtensions.txt -> sorted [(start, end, (script_long_names,...))].

    Each value is a space-separated set of script abbreviations; expand them to
    long names via *aliases*, drop the transparent ones, and keep the range only
    when at least one real script survives (else the code point is transparent and
    should fall through to nothing, never to the plain Script).
    """
    out: list[tuple[int, int, tuple[str, ...]]] = []
    for line in text.splitlines():
        m = _DATA_LINE_RE.match(line)
        if not m:
            continue
        start = int(m.group(1), 16)
        end = int(m.group(2), 16) if m.group(2) else start
        abbrs = m.group(3).split()
        names = sorted({aliases.get(a, a) for a in abbrs} - _TRANSPARENT)
        if not names:
            continue
        out.append((start, end, tuple(names)))
    out.sort(key=lambda r: r[0])
    return _merge_tuple(out)


def _merge_scalar(
    ranges: list[tuple[int, int, str]],
) -> list[tuple[int, int, str]]:
    """Coalesce adjacent/overlapping ranges sharing the same value (smaller table)."""
    merged: list[tuple[int, int, str]] = []
    for start, end, value in ranges:
        if merged and merged[-1][2] == value and start <= merged[-1][1] + 1:
            p_start, _p_end, _ = merged[-1]
            merged[-1] = (p_start, max(_p_end, end), value)
        else:
            merged.append((start, end, value))
    return merged


def _merge_tuple(
    ranges: list[tuple[int, int, tuple[str, ...]]],
) -> list[tuple[int, int, tuple[str, ...]]]:
    """Coalesce adjacent/overlapping ranges sharing the same script-name tuple."""
    merged: list[tuple[int, int, tuple[str, ...]]] = []
    for start, end, value in ranges:
        if merged and merged[-1][2] == value and start <= merged[-1][1] + 1:
            p_start, _p_end, _ = merged[-1]
            merged[-1] = (p_start, max(_p_end, end), value)
        else:
            merged.append((start, end, value))
    return merged


# ── Emission ──────────────────────────────────────────────────────────────────


def _wrap_literals(name: str, literals: list[str]) -> str:
    """Emit ``name = (...)`` with ONE literal per indented row + a trailing comma.

    A magic trailing comma after a one-per-line layout is exactly what ruff-format
    emits for a long collection, so the module passes ``ruff format --check`` and
    re-running the generator reproduces it byte-for-byte. No row can exceed the
    120-col limit (one short literal per line).
    """
    out = [f"{name} = (\n"]
    out.extend(f"    {lit},\n" for lit in literals)
    out.append(")\n")
    return "".join(out)


def _quote(script: str) -> str:
    """Double-quote a UCD script long-name (matching ruff-format's quote style).

    UCD script long-names are ``[A-Za-z0-9_]`` only; assert that so an unexpected
    character can never break the emitted module's quoting.
    """
    if not re.fullmatch(r"[A-Za-z0-9_]+", script):
        raise SystemExit(f"ERROR: unexpected script name {script!r} (cannot safely quote)")
    return f'"{script}"'


def _emit_int_array(name: str, values: list[int]) -> str:
    return _wrap_literals(name, [f"0x{v:X}" for v in values])


def _emit_str_array(name: str, values: list[str]) -> str:
    return _wrap_literals(name, [_quote(v) for v in values])


_LINE_LIMIT = 120
_ROW_INDENT = "    "  # 4-space row indent inside the outer ( ... ).


def _tuple_literal(v: tuple[str, ...]) -> str:
    """One Script_Extensions tuple as a row literal, matching ruff-format exactly.

    A tuple whose inline form fits the 120-col limit (with the row indent + trailing
    comma) stays inline; a wider one explodes to one element per line at an 8-space
    indent with a magic trailing comma (ruff's layout for an over-long collection).
    A single-element tuple keeps the Python-mandatory trailing comma (``("Latin",)``).
    """
    quoted = [_quote(s) for s in v]
    inline = f"({quoted[0]},)" if len(v) == 1 else "(" + ", ".join(quoted) + ")"
    # +1 for the trailing comma _wrap_literals appends after the row literal.
    if len(_ROW_INDENT) + len(inline) + 1 <= _LINE_LIMIT:
        return inline
    body = "".join(f"        {q},\n" for q in quoted)
    return f"(\n{body}{_ROW_INDENT})"


def _emit_tuple_array(name: str, values: list[tuple[str, ...]]) -> str:
    return _wrap_literals(name, [_tuple_literal(v) for v in values])


def build_module(
    version: str,
    scripts: list[tuple[int, int, str]],
    scriptx: list[tuple[int, int, tuple[str, ...]]],
) -> str:
    parts = [_MODULE_HEADER.format(version=version)]

    parts.append("# Plain Script property: parallel sorted range arrays.\n")
    parts.append(_emit_int_array("SCRIPT_RANGE_STARTS", [r[0] for r in scripts]))
    parts.append(_emit_int_array("SCRIPT_RANGE_ENDS", [r[1] for r in scripts]))
    parts.append(_emit_str_array("SCRIPT_RANGE_NAMES", [r[2] for r in scripts]))
    parts.append("\n")

    parts.append("# Script_Extensions property: parallel sorted range arrays.\n")
    parts.append(_emit_int_array("SCRIPTX_RANGE_STARTS", [r[0] for r in scriptx]))
    parts.append(_emit_int_array("SCRIPTX_RANGE_ENDS", [r[1] for r in scriptx]))
    parts.append(_emit_tuple_array("SCRIPTX_RANGE_NAMES", [r[2] for r in scriptx]))

    return "".join(parts)


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        default=UNICODE_VERSION,
        metavar="X.Y.Z",
        help=f"Unicode version to fetch (default: {UNICODE_VERSION}, pinned)",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        metavar="FILE",
        help=f"Output data module (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Fetch + parse and report sizes; write nothing",
    )
    args = parser.parse_args()

    print(f"Unicode {args.version}")
    print("  fetching PropertyValueAliases.txt ...", end=" ", flush=True)
    pva = fetch_ucd(args.version, "PropertyValueAliases.txt")
    aliases = parse_alias_map(pva)
    print(f"{len(aliases)} script aliases")

    print("  fetching Scripts.txt ...", end=" ", flush=True)
    scripts = parse_scripts(fetch_ucd(args.version, "Scripts.txt"))
    print(f"{len(scripts)} ranges (transparent dropped)")

    print("  fetching ScriptExtensions.txt ...", end=" ", flush=True)
    scriptx = parse_script_extensions(fetch_ucd(args.version, "ScriptExtensions.txt"), aliases)
    print(f"{len(scriptx)} ranges")

    module = build_module(args.version, scripts, scriptx)

    if args.dry_run:
        print(f"  [dry-run] module would be {len(module)} bytes")
        return

    out_path = Path(args.output)
    out_path.write_text(module, encoding="utf-8")
    print(f"  wrote {out_path} ({len(module)} bytes)")


if __name__ == "__main__":
    main()
