"""Tier-A HTTP render-smoke sweep over every pfBlockerNG page (ADR-14 Phase 2).

Marker ``ui_render`` -- collected only by the smoke/ui workflow
(``pytest tests/smoke -m ui_render --override-ini="addopts="``); the whole
``tests/smoke`` tree is ``--ignore``d in the default ``python -m pytest`` run, so
this never affects the default suite.

Every authenticated pfBlockerNG webConfigurator page (:data:`PAGE_TABLE`) is
GET via the reused Phase-1 :class:`~tests.smoke.ui.webui.WebUI` session and run
through the real oracle (:func:`~tests.smoke.ui.render_oracle.evaluate_render`):
HTTP 200 + no PHP diagnostic in the body + a page-specific marker present, AND
(sweep-level) the on-box ``php_error.log`` gained no new line during the sweep
(:class:`~tests.smoke.ui.render_oracle.PhpErrorLogGuard`). A bare 200 never
passes -- proven by ``test_render_oracle.py`` feeding the oracle a broken body.

Hermeticity (ADR §2 "Hermetic where it claims to be"): every page in the table
renders from local config alone -- none triggers a feed download to produce its
chrome. Pages whose *content* would need a network fetch (the GeoIP/Reputation
per-continent views generated by ``pfblockerng.php``, and the DNSBL-VIP sinkhole
pages served by a separate lighttpd) are recorded in :data:`EXCLUDED_FROM_TIER_A`
with the reason and the access note for Phase 5, NOT silently dropped.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import pytest

from .. import helpers
from .render_oracle import PhpErrorLogGuard, evaluate_render

if TYPE_CHECKING:
    from collections.abc import Iterator

    from ..conftest import SmokeVM
    from .webui import WebUI

pytestmark = pytest.mark.ui_render


@dataclass(frozen=True)
class Page:
    """One Tier-A page: a webConfigurator path + the markers that prove it rendered.

    ``markers`` are stable strings drawn from the page's real ``$pgtitle``
    breadcrumb crumb and/or a ``Form_Section`` panel title (rendered verbatim
    into the HTML). ``hermetic`` is documentary -- every entry here is hermetic;
    a non-hermetic page lives in :data:`EXCLUDED_FROM_TIER_A` instead.
    """

    name: str
    path: str
    markers: tuple[str, ...]
    hermetic: bool = True


# The authenticated main-webConfigurator pages under src/usr/local/www/pfblockerng/.
# Markers verified against each file's $pgtitle / Form_Section('...') title.
#
# Multi-mode pages are probed in EACH mode they expose via a query parameter, so
# both branches of the page's mode switch are exercised (CLAUDE.md branch
# coverage): pfblockerng_category.php and _category_edit.php render an IP view by
# default and a DNSBL view under ?type=dnsbl; both are listed.
PAGE_TABLE: tuple[Page, ...] = (
    # "Aggregated Aliases" is the ADR-11 pfb_agg_types multi-select label (rendered
    # verbatim) — a third marker so the gate also proves that field renders on the page.
    Page("general", "/pfblockerng/pfblockerng_general.php", ("pfBlockerNG", "General Settings", "Aggregated Aliases")),
    Page("ip", "/pfblockerng/pfblockerng_ip.php", ("IP Configuration", "ASN configuration")),
    Page("dnsbl", "/pfblockerng/pfblockerng_dnsbl.php", ("DNSBL Webserver Configuration", "DNSBL Configuration")),
    # feeds.php is split into IPv4/IPv6/DNSBL ?type sub-tabs (ADR-16 Phase 3). Each type
    # is probed; the type-specific marker is the active type's "Feed Settings" alias-name
    # StaticText label ("IPv4 Alias name(s):" etc.), which renders ONLY for the active
    # type -- so it distinguishes the three views (the panel title is shared by all). The
    # coverage guard strips "?", so all three collapse to the one base path.
    Page(
        "feeds_ipv4",
        "/pfblockerng/pfblockerng_feeds.php?type=ipv4",
        ("Pre-defined Alias/Group/Feeds", "IPv4 Alias name(s):"),
    ),
    Page(
        "feeds_ipv6",
        "/pfblockerng/pfblockerng_feeds.php?type=ipv6",
        ("Pre-defined Alias/Group/Feeds", "IPv6 Alias name(s):"),
    ),
    Page(
        "feeds_dnsbl",
        "/pfblockerng/pfblockerng_feeds.php?type=dnsbl",
        ("Pre-defined Alias/Group/Feeds", "DNSBL Alias name(s):"),
    ),
    Page("alerts", "/pfblockerng/pfblockerng_alerts.php", ("Alert Settings",)),
    Page("log", "/pfblockerng/pfblockerng_log.php", ("Log/File Browser selections",)),
    Page("sync", "/pfblockerng/pfblockerng_sync.php", ("XMLRPC Sync Settings",)),
    Page("safesearch", "/pfblockerng/pfblockerng_safesearch.php", ("SafeSearch settings", "DNSBL SafeSearch")),
    Page("update", "/pfblockerng/pfblockerng_update.php", ("Update Settings",)),
    # blacklist.php is always the DNSBL Category view; the long info line is a stable literal.
    Page(
        "blacklist",
        "/pfblockerng/pfblockerng_blacklist.php",
        ("DNSBL Category Feeds are processed first", "DNSBL Category"),
    ),
    # category.php: default IP view (?type=ipv4) AND the DNSBL view (?type=dnsbl).
    Page("category_ip", "/pfblockerng/pfblockerng_category.php?type=ipv4", ("Summary", "pfBlockerNG")),
    Page("category_dnsbl", "/pfblockerng/pfblockerng_category.php?type=dnsbl", ("Summary", "DNSBL")),
    # category_edit.php: default IP view AND the DNSBL view; Form_Section('Advanced Tuneables') is unique to it.
    Page("category_edit_ip", "/pfblockerng/pfblockerng_category_edit.php?type=ipv4", ("Advanced Tuneables",)),
    Page("category_edit_dnsbl", "/pfblockerng/pfblockerng_category_edit.php?type=dnsbl", ("Advanced Tuneables",)),
    # threats.php REQUIRES a host/domain/port param -- with none it print_info_box()es and exit()s
    # before rendering $pgtitle. A syntactically-valid param renders the lookup page chrome; the
    # threat links it draws are <a href> only (no server-side network call), so it stays hermetic.
    # All THREE positive views ($title is 'Source IP'/'Domain'/'Port' -> the "Threat <title> Lookup"
    # breadcrumb + "Threat <title>:" panel) are probed (CLAUDE.md branch coverage); the reject /
    # no-request branches are covered by test_threats_rejects_malformed_lookup below. The {domain}
    # placeholder is filled per run with helpers.unique_domain() (uuid-*.com) -- the smoke-domain
    # rule (never a fixed/RFC-6761 name); host/port use a documentation IP (TEST-NET-3) + a valid
    # port (no network coupling either way).
    Page("threats_domain", "/pfblockerng/pfblockerng_threats.php?domain={domain}", ("Threat Domain", "Source IP")),
    Page(
        "threats_host", "/pfblockerng/pfblockerng_threats.php?host=203.0.113.5", ("Threat Source IP", "Threat Lookups")
    ),
    Page("threats_port", "/pfblockerng/pfblockerng_threats.php?port=8443", ("Threat Port",)),
    # ADR-12 Update Hooks (pre/post update-command list). $pgtitle + the section titles are stable.
    Page("hooks", "/pfblockerng/pfblockerng_hooks.php", ("Update Hooks", "Hook Entries")),
    # The dashboard widget (auth-gated; $nocsrf=true). A direct GET renders the alias-table panel
    # whose hidden inputs (id="pfblockerngack") are a stable marker; the AJAX getNew* paths need a
    # query param, so the plain GET exercises the full-render branch.
    Page("widget", "/widgets/widgets/pfblockerng.widget.php", ('id="pfblockerngack"', "Alias")),
)


@dataclass(frozen=True)
class ExcludedPage:
    """A pfBlockerNG page deliberately kept OUT of the hermetic Tier-A sweep.

    Recorded (ADR §2 "don't silently drop") with why it is non-hermetic / not
    reachable via the authenticated webConfigurator session, and how Phase 5/CI
    should reach it instead.
    """

    name: str
    path: str
    reason: str
    access_note: str
    markers: tuple[str, ...] = field(default_factory=tuple)


# Pages NOT in the hermetic Tier-A sweep, with the reason + the Phase-5 access note.
EXCLUDED_FROM_TIER_A: tuple[ExcludedPage, ...] = (
    ExcludedPage(
        name="geoip_continent_views",
        path="/pfblockerng/pfblockerng_<Continent>.php (+ pfblockerng_reputation.php)",
        reason=(
            "pfblockerng.php is a CLI dispatcher + a TEMPLATE: it generates the per-continent "
            "(Top Spammers/Africa/.../Proxy_and_Satellite) and Reputation PHP pages via "
            "file_put_contents only AFTER a MaxMind GeoIP update -- which needs a network download "
            "and a MaxMind key. Those files do not exist on a fresh box, so they cannot render "
            "hermetically."
        ),
        access_note=(
            "Phase 5 (egress-allowed Tier-B leg): run a GeoIP update so the continent pages are "
            "generated, then render-smoke them. A direct GET of pfblockerng.php itself runs the "
            "template path, not a settings page, so it is not a Tier-A target."
        ),
    ),
    ExcludedPage(
        name="dnsbl_vip_sinkhole_pages",
        path="/index.php and /dnsbl_default.php under www/ (DNSBL VIP webserver)",
        reason=(
            "www/index.php + dnsbl_default.php are served by the DNSBL sinkhole lighttpd on the "
            "DNSBL VIP (ports 8081/8443), NOT the main webConfigurator: no guiconfig auth, and "
            "index.php exit()s unless HTTP_HOST is a valid hostname and REQUEST_URI=='/' (otherwise "
            "it returns a 1x1 GIF). dnsbl_default.php is a template INCLUDED by dnsbl_active.php, "
            "never served standalone. The authenticated session on :8080 cannot reach them."
        ),
        access_note=(
            "Phase 5: fetch the VIP sinkhole directly -- http://<DNSBL_VIP>:8081/ with a Host header "
            "set to a blocked hostname and REQUEST_URI '/' to get the DNSBL-Full block page; the "
            "marker is 'Site blocked via DNSBL' (dnsbl_default.php <title>). No webConfigurator login."
        ),
        markers=("Site blocked via DNSBL",),
    ),
)


@pytest.fixture(scope="module")
def php_error_log_guard(smoke_vm: SmokeVM, webui: WebUI) -> Iterator[PhpErrorLogGuard]:  # noqa: ARG001
    """Snapshot ``php_error.log`` once before the sweep, assert no growth after.

    Module-scoped so it brackets the WHOLE parametrized sweep (oracle condition
    (d)): a new error line written by ANY page during the sweep fails the
    teardown. ``webui`` is requested only to order this after login / VM
    readiness; the diff itself is read over the ``smoke_vm`` SSH path.
    """
    guard = PhpErrorLogGuard(smoke_vm)
    guard.snapshot()
    yield guard
    guard.assert_no_growth()


@pytest.mark.parametrize("page", PAGE_TABLE, ids=lambda p: p.name)
def test_page_renders_clean(page: Page, webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """Each pfBlockerNG page passes the per-page oracle (a)-(c).

    Requesting ``php_error_log_guard`` enrolls this test in the sweep-level (d)
    check: the guard snapshots ``php_error.log`` before the first parametrization
    and asserts no growth after the last, so a page that logs (but does not echo)
    a PHP diagnostic still fails the sweep.
    """
    # Fill the {domain} placeholder (threats page) with a unique uuid-*.com per
    # run; other paths carry no placeholder and pass through unchanged.
    path = page.path.format(domain=helpers.unique_domain()) if "{domain}" in page.path else page.path
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, page.markers)
    assert result.ok, f"render oracle failed for {page.name} ({path}): {result.detail}"


# ADR-11: the General page's pfb_agg_types multi-select must render with ALL FOUR
# option branches (Deny/Permit/Match/Native) AND its no-rule help caveat. Asserting
# every option proves each branch of the select is emitted (not just the label), and the
# caveat substring proves the help text — the user's only signal that an aggregate is
# Native (no firewall rule) — actually rendered. Substrings verified against the real
# pfblockerng_general.php: the four $options_pfb_agg_types keys render as Form_Select
# option values ('value="<Type>"'), and the setHelp() copy contains "no firewall rule".
_AGG_TYPE_OPTIONS = ("Deny", "Permit", "Match", "Native")
_AGG_HELP_CAVEAT = "no firewall rule"
_GENERAL_PAGE = "/pfblockerng/pfblockerng_general.php"


def test_general_page_renders_aggregate_select(webui: WebUI) -> None:
    """The General page renders the pfb_agg_types select: all four options + the caveat.

    Hermetic (no network — the General page renders from local config alone). GET the
    page and assert: (1) the ``pfb_agg_types`` field is present; (2) EACH of the four
    option values (Deny/Permit/Match/Native) is emitted — every branch of the multi-
    select, not just one (CLAUDE.md branch coverage); and (3) the "no firewall rule" help
    caveat — the load-bearing "these are Native reference IP-sets" wording — is present.
    Pairs with the PAGE_TABLE "Aggregated Aliases" label marker (the field's presence) to
    pin both the field and its full option set + help.
    """
    resp = webui.get(_GENERAL_PAGE)
    assert resp.status_code == 200, f"GET {_GENERAL_PAGE} -> HTTP {resp.status_code} (expected 200)"
    body = resp.text
    assert "pfb_agg_types" in body, "pfb_agg_types select not present on the General page"
    missing = [opt for opt in _AGG_TYPE_OPTIONS if f'value="{opt}"' not in body]
    assert not missing, f"pfb_agg_types select missing option value(s) {missing} (each is a branch that must render)"
    assert _AGG_HELP_CAVEAT in body, (
        f"pfb_agg_types help caveat {_AGG_HELP_CAVEAT!r} (the Native/no-rule wording) not rendered on the General page"
    )


def test_dnsbl_idn_blocking_fields_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The ADR-08 'IDN Blocking' selector + its two Confusable sub-toggles render
    cleanly on the DNSBL page — so a regression that drops or breaks the field is
    caught at the render tier (not just by the matcher smoke).

    Asserts the page passes the clean-render oracle AND that the three POST field
    names (``pfb_idn`` select + the two sub-toggle checkboxes) and the 'IDN Blocking'
    / 'Confusable' option labels are present in the body. ``php_error_log_guard``
    enrolls this GET in the module-level no-growth sweep.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        'name="pfb_idn"',
        'name="pfb_idn_block_malicious"',
        'name="pfb_idn_escalate_suspicious"',
        "IDN Blocking",
        ">Always<",  # the 'all' mode option label (renamed from "All-IDN")
        ">Confusable<",
    ):
        assert needle in body, f"DNSBL page is missing the IDN-mode marker {needle!r}"


# ADR-23: the setup wizard's DNSBL step now surfaces ADR-13's pfb_dnsvip_auto auto-VIP
# toggle. Core wizard.php renders ONE step per GET, indexed by a 0-based `stepid` (verified
# against pfSense upstream wizard.php: `$stepid` defaults to "0" and indexes $pkg['step']
# directly). The DNSBL step is the 4th <step> (<id>4</id>, "DNSBL Component Configuration")
# in pfblockerng_wizard.xml -> stepid=3. The wizard is NOT in PAGE_TABLE (a core-rendered
# www/wizards/ page, not a www/pfblockerng/ one), so it gets its own render assertion.
_WIZARD_DNSBL_STEP = "/wizard.php?xml=pfblockerng_wizard.xml&stepid=3"


def test_wizard_dnsbl_step_renders_auto_vip(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """ADR-23: the wizard DNSBL step renders the Auto VIP (pfb_dnsvip_auto) checkbox cleanly.

    The setup wizard exposes ADR-13's auto-create toggle on its DNSBL step so a first-run
    user need not pre-create a sinkhole VIP — a render regression that drops/breaks the field
    (or the wizard step itself) must fail here, not only in the maintainer on-box check. A
    direct authenticated GET renders the step regardless of the first-run dismissal the
    `webui` fixture performs (dismissal only suppresses general.php's auto-launch redirect,
    not wizard.php itself).

    Asserts the step passes the clean-render oracle (200, no PHP diagnostic, the step-title
    Form_Section marker present, not the login form) AND — from three independent wizard.php
    render paths — that the field's POST name (`pfb_dnsvip_auto`), its 'Auto VIP' displayname
    label, and the 'Create VIPs automatically' setHelp() wording are present. The IPv4/IPv6
    manual selectors carry the new "manual mode only" note, asserted too so the mode framing
    that pairs with the checkbox is pinned. `php_error_log_guard` enrolls this GET in the
    module-level no-growth sweep.
    """
    resp = webui.get(_WIZARD_DNSBL_STEP)
    result = evaluate_render(_WIZARD_DNSBL_STEP, resp.status_code, resp.text, ("DNSBL Component Configuration",))
    assert result.ok, f"wizard DNSBL-step render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        "pfb_dnsvip_auto",  # the checkbox field's POST name (input name/id)
        "Auto VIP",  # the <displayname> label
        "Create VIPs automatically",  # the <description> setHelp() wording
        "manual mode only",  # the pfb_dnsvip4/6 selectors' new mode-dependency note
    ):
        assert needle in body, f"wizard DNSBL step is missing the Auto VIP marker {needle!r}"


# threats.php's NEGATIVE branches: each malformed/absent param print_info_box()es
# a specific message and exit()s BEFORE the "$pgtitle" lookup-page chrome. These
# pair with the positive threats_{domain,host,port} entries above (CLAUDE.md
# branch coverage: prove the validators REJECT, not only that valid input renders).
THREATS_PAGE = "/pfblockerng/pfblockerng_threats.php"
# (id, query, expected info-box message) -- messages verified verbatim against
# pfblockerng_threats.php (is_ipaddr / is_port guards + the no-param else).
THREATS_REJECTS: tuple[tuple[str, str, str], ...] = (
    ("invalid_host", "host=not-an-ip", "Invalid IP Address, cannot proceed!"),
    ("invalid_port", "port=99999", "Invalid Port cannot proceed!"),
    ("no_request", "", "No Requests found, cannot proceed!"),
)
# The lookup-page chrome titles ("Threat <title> Lookup") that MUST be absent on a
# reject (the handler exit()s before rendering $pgtitle).
_THREATS_LOOKUP_TITLES = ("Threat Domain Lookup", "Threat Source IP Lookup", "Threat Port Lookup")


@pytest.mark.parametrize(("name", "query", "message"), THREATS_REJECTS, ids=[r[0] for r in THREATS_REJECTS])
def test_threats_rejects_malformed_lookup(name: str, query: str, message: str, webui: WebUI) -> None:
    """A malformed/absent threats lookup renders its info-box, NOT the lookup page.

    HTTP 200 (head.inc is included before the dispatch, so the page still renders
    its header) with the exact info-box message present and the "Threat ... Lookup"
    chrome absent -- proving the validator rejected and exit()ed rather than
    rendering the lookup view. The before-state (a valid param DOES render that
    chrome) is the positive threats_{domain,host,port} entries in PAGE_TABLE.
    """
    path = f"{THREATS_PAGE}?{query}" if query else THREATS_PAGE
    resp = webui.get(path)
    assert resp.status_code == 200, f"{name}: GET {path} -> HTTP {resp.status_code} (expected 200)"
    body = resp.text
    assert message in body, f"{name}: expected info-box {message!r} not present in {path} body"
    present = [title for title in _THREATS_LOOKUP_TITLES if title in body]
    assert not present, f"{name}: reject path unexpectedly rendered lookup chrome {present}"


# ADR-19: the "Software" page + tab are PROVENANCE-GATED — present ONLY on a build
# installed from one of OUR repos (pkg %R == pfblockerng / pfblockerng-nightly). The
# ADR-04 UI harness installs the branch .pkg with `pkg add -f` (offline), so its %R is
# NOT one of our repos -> the provenance gate HIDES the page and the tab. This is the
# NEGATIVE side of the gate, and it is the one this Tier-A deploy can prove live: the
# page's top-of-file guard `header('Location: /index.php'); exit;` fires, and
# pfb_software_add_tab() appends nothing. The POSITIVE render (200 + the
# 'pfb-software-panel' marker + the action buttons) belongs to Phase 5's `repo`-install
# journey, where the package IS installed from our repo so %R == pfblockerng.
_SOFTWARE_PAGE = "/pfblockerng/pfblockerng_software.php"
_SOFTWARE_PANEL_MARKER = "pfb-software-panel"
_SOFTWARE_TAB_HREF = "/pfblockerng/pfblockerng_software.php"


def test_software_page_provenance_gate_hides_on_nonour_build(
    webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """The Software page's provenance guard hides it on a non-our-repo install.

    Scenario: pfBlockerNG installed via `pkg add -f` (the UI harness), so the
    installed package's repo (`pkg query %R`) is NOT one of our repos.
      Given the standard Tier-A deploy (offline `pkg add -f`),
      When the Software page is GET (redirects NOT followed),
      Then the top-of-file provenance guard redirects to /index.php (a 3xx, not a
           200 panel body), the page-specific 'pfb-software-panel' marker is absent
           from the body, AND no new php_error.log line is produced (the guard is a
           clean redirect+exit, NOT a fatal). The enrolled php_error_log_guard pins
           the no-new-error-line condition over the sweep.
    """
    # Do NOT follow the redirect: assert the guard's 3xx -> /index.php directly, so a
    # broken guard that 200-renders the panel can't pass by following to a clean page.
    resp = webui.get(_SOFTWARE_PAGE, allow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308), (
        f"Software page expected a provenance-guard redirect, got HTTP {resp.status_code}"
    )
    location = resp.headers.get("Location", "")
    assert location.endswith("/index.php"), f"provenance guard should redirect to /index.php, got Location={location!r}"
    assert _SOFTWARE_PANEL_MARKER not in resp.text, (
        "provenance guard must NOT render the Software panel on a non-our-build"
    )


def test_software_tab_absent_on_nonour_build(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The 'Software' tab is absent from a normal pfBlockerNG page on a non-our-build.

    Given the same offline `pkg add -f` deploy (non-our-repo provenance),
    When the General page is GET,
    Then pfb_software_add_tab() appended nothing: the Software tab href is NOT in the
         tab bar. Pairs with the page-gate test above to prove BOTH gated surfaces
         (page + tab) are hidden. The positive (tab PRESENT) state is Phase 5's
         repo-install journey. php_error_log_guard enrolls this GET in the sweep.
    """
    resp = webui.get(_GENERAL_PAGE)
    result = evaluate_render(_GENERAL_PAGE, resp.status_code, resp.text, ("General Settings",))
    assert result.ok, f"General page render oracle failed: {result.detail}"
    assert _SOFTWARE_TAB_HREF not in resp.text, (
        "the Software tab must be ABSENT on a non-our-build (provenance gate hides it everywhere)"
    )


def test_page_table_covers_every_pfblockerng_page() -> None:
    """Guard: the table (plus the recorded exclusions) covers the on-disk page set.

    A new pfBlockerNG .php page added to src/ without a Tier-A entry should fail
    this -- the count is asserted so the sweep can't silently skip a page. 15
    servable main pages: general, ip, dnsbl, feeds, alerts, log, sync,
    safesearch, update, blacklist, category, category_edit, threats, hooks, plus
    the pfblockerng.php template (excluded). The widget + 2 DNSBL-VIP pages round
    it out; the VIP pages + the GeoIP/Reputation views are the recorded exclusions.
    """
    covered_paths = {p.path.split("?", 1)[0] for p in PAGE_TABLE}
    # 14 distinct main .php files are render-smoked here (pfblockerng.php is the
    # excluded template), plus the widget = 15 distinct paths.
    expected_main = {
        "/pfblockerng/pfblockerng_general.php",
        "/pfblockerng/pfblockerng_ip.php",
        "/pfblockerng/pfblockerng_dnsbl.php",
        "/pfblockerng/pfblockerng_feeds.php",
        "/pfblockerng/pfblockerng_alerts.php",
        "/pfblockerng/pfblockerng_log.php",
        "/pfblockerng/pfblockerng_sync.php",
        "/pfblockerng/pfblockerng_safesearch.php",
        "/pfblockerng/pfblockerng_update.php",
        "/pfblockerng/pfblockerng_blacklist.php",
        "/pfblockerng/pfblockerng_category.php",
        "/pfblockerng/pfblockerng_category_edit.php",
        "/pfblockerng/pfblockerng_threats.php",
        "/pfblockerng/pfblockerng_hooks.php",
        "/widgets/widgets/pfblockerng.widget.php",
    }
    missing = expected_main - covered_paths
    assert not missing, f"Tier-A page table is missing pages: {sorted(missing)}"
    # The two non-hermetic classes are recorded, not dropped.
    excluded_names = {e.name for e in EXCLUDED_FROM_TIER_A}
    assert "geoip_continent_views" in excluded_names
    assert "dnsbl_vip_sinkhole_pages" in excluded_names
