"""Tier-A HTTP render-smoke sweep over every pfBlockerNG page (ADR-14 Phase 2).

Marker ``ui_render`` -- collected only by the smoke/ui workflow
(``pytest tests/smoke -m ui_render --override-ini="addopts="``); the whole
``tests/smoke`` tree is ``--ignore``d in the default ``python -m pytest`` run, so
this never affects the default suite.

Every authenticated pfBlockerNG webConfigurator page (:data:`PAGE_TABLE`) is
GET via the reused Phase-1 :class:`~tests.smoke.ui.webui.WebUI` session and run
through the real oracle (:func:`~tests.smoke.ui.render_oracle.evaluate_render`):
HTTP 200 + no PHP diagnostic in the body + a page-specific marker present, AND
(sweep-level) the on-box ``php_error.log`` gained no new line during the sweep
(:class:`~tests.smoke.ui.render_oracle.PhpErrorLogGuard`). A bare 200 never
passes -- proven by ``test_render_oracle.py`` feeding the oracle a broken body.

Hermeticity (ADR §2 "Hermetic where it claims to be"): every page in the table
renders from local config alone -- none triggers a feed download to produce its
chrome. Pages whose *content* would need a network fetch (the GeoIP/Reputation
per-continent views generated by ``pfblockerng.php``, and the DNSBL-VIP sinkhole
pages served by a separate lighttpd) are recorded in :data:`EXCLUDED_FROM_TIER_A`
with the reason and the access note for Phase 5, NOT silently dropped.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import pytest

from .render_oracle import PhpErrorLogGuard, evaluate_render

if TYPE_CHECKING:
    from collections.abc import Iterator

    from ..conftest import SmokeVM
    from .webui import WebUI

pytestmark = pytest.mark.ui_render


@dataclass(frozen=True)
class Page:
    """One Tier-A page: a webConfigurator path + the markers that prove it rendered.

    ``markers`` are stable strings drawn from the page's real ``$pgtitle``
    breadcrumb crumb and/or a ``Form_Section`` panel title (rendered verbatim
    into the HTML). ``hermetic`` is documentary -- every entry here is hermetic;
    a non-hermetic page lives in :data:`EXCLUDED_FROM_TIER_A` instead.
    """

    name: str
    path: str
    markers: tuple[str, ...]
    hermetic: bool = True


# The authenticated main-webConfigurator pages under src/usr/local/www/pfblockerng/.
# Markers verified against each file's $pgtitle / Form_Section('...') title.
#
# Multi-mode pages are probed in EACH mode they expose via a query parameter, so
# both branches of the page's mode switch are exercised (CLAUDE.md branch
# coverage): pfblockerng_category.php and _category_edit.php render an IP view by
# default and a DNSBL view under ?type=dnsbl; both are listed.
PAGE_TABLE: tuple[Page, ...] = (
    Page("general", "/pfblockerng/pfblockerng_general.php", ("pfBlockerNG", "General Settings")),
    Page("ip", "/pfblockerng/pfblockerng_ip.php", ("IP Configuration", "ASN configuration")),
    Page("dnsbl", "/pfblockerng/pfblockerng_dnsbl.php", ("DNSBL Webserver Configuration", "DNSBL Configuration")),
    Page("feeds", "/pfblockerng/pfblockerng_feeds.php", ("Pre-defined Alias/Group/Feeds",)),
    Page("alerts", "/pfblockerng/pfblockerng_alerts.php", ("Alert Settings",)),
    Page("log", "/pfblockerng/pfblockerng_log.php", ("Log/File Browser selections",)),
    Page("sync", "/pfblockerng/pfblockerng_sync.php", ("XMLRPC Sync Settings",)),
    Page("safesearch", "/pfblockerng/pfblockerng_safesearch.php", ("SafeSearch settings", "DNSBL SafeSearch")),
    Page("update", "/pfblockerng/pfblockerng_update.php", ("Update Settings",)),
    # blacklist.php is always the DNSBL Category view; the long info line is a stable literal.
    Page(
        "blacklist",
        "/pfblockerng/pfblockerng_blacklist.php",
        ("DNSBL Category Feeds are processed first", "DNSBL Category"),
    ),
    # category.php: default IP view (?type=ipv4) AND the DNSBL view (?type=dnsbl).
    Page("category_ip", "/pfblockerng/pfblockerng_category.php?type=ipv4", ("Summary", "pfBlockerNG")),
    Page("category_dnsbl", "/pfblockerng/pfblockerng_category.php?type=dnsbl", ("Summary", "DNSBL")),
    # category_edit.php: default IP view AND the DNSBL view; Form_Section('Advanced Tuneables') is unique to it.
    Page("category_edit_ip", "/pfblockerng/pfblockerng_category_edit.php?type=ipv4", ("Advanced Tuneables",)),
    Page("category_edit_dnsbl", "/pfblockerng/pfblockerng_category_edit.php?type=dnsbl", ("Advanced Tuneables",)),
    # threats.php REQUIRES a host/domain/port param -- with none it print_info_box()es and exit()s
    # before rendering $pgtitle. A syntactically-valid domain renders the lookup page chrome; the
    # threat links it draws are <a href> only (no server-side network call), so it stays hermetic.
    Page("threats", "/pfblockerng/pfblockerng_threats.php?domain=example.com", ("Threat Domain", "Source IP")),
    # The dashboard widget (auth-gated; $nocsrf=true). A direct GET renders the alias-table panel
    # whose hidden inputs (id="pfblockerngack") are a stable marker; the AJAX getNew* paths need a
    # query param, so the plain GET exercises the full-render branch.
    Page("widget", "/widgets/widgets/pfblockerng.widget.php", ('id="pfblockerngack"', "Alias")),
)


@dataclass(frozen=True)
class ExcludedPage:
    """A pfBlockerNG page deliberately kept OUT of the hermetic Tier-A sweep.

    Recorded (ADR §2 "don't silently drop") with why it is non-hermetic / not
    reachable via the authenticated webConfigurator session, and how Phase 5/CI
    should reach it instead.
    """

    name: str
    path: str
    reason: str
    access_note: str
    markers: tuple[str, ...] = field(default_factory=tuple)


# Pages NOT in the hermetic Tier-A sweep, with the reason + the Phase-5 access note.
EXCLUDED_FROM_TIER_A: tuple[ExcludedPage, ...] = (
    ExcludedPage(
        name="geoip_continent_views",
        path="/pfblockerng/pfblockerng_<Continent>.php (+ pfblockerng_reputation.php)",
        reason=(
            "pfblockerng.php is a CLI dispatcher + a TEMPLATE: it generates the per-continent "
            "(Top Spammers/Africa/.../Proxy_and_Satellite) and Reputation PHP pages via "
            "file_put_contents only AFTER a MaxMind GeoIP update -- which needs a network download "
            "and a MaxMind key. Those files do not exist on a fresh box, so they cannot render "
            "hermetically."
        ),
        access_note=(
            "Phase 5 (egress-allowed Tier-B leg): run a GeoIP update so the continent pages are "
            "generated, then render-smoke them. A direct GET of pfblockerng.php itself runs the "
            "template path, not a settings page, so it is not a Tier-A target."
        ),
    ),
    ExcludedPage(
        name="dnsbl_vip_sinkhole_pages",
        path="/index.php and /dnsbl_default.php under www/ (DNSBL VIP webserver)",
        reason=(
            "www/index.php + dnsbl_default.php are served by the DNSBL sinkhole lighttpd on the "
            "DNSBL VIP (ports 8081/8443), NOT the main webConfigurator: no guiconfig auth, and "
            "index.php exit()s unless HTTP_HOST is a valid hostname and REQUEST_URI=='/' (otherwise "
            "it returns a 1x1 GIF). dnsbl_default.php is a template INCLUDED by dnsbl_active.php, "
            "never served standalone. The authenticated session on :8080 cannot reach them."
        ),
        access_note=(
            "Phase 5: fetch the VIP sinkhole directly -- http://<DNSBL_VIP>:8081/ with a Host header "
            "set to a blocked hostname and REQUEST_URI '/' to get the DNSBL-Full block page; the "
            "marker is 'Site blocked via DNSBL' (dnsbl_default.php <title>). No webConfigurator login."
        ),
        markers=("Site blocked via DNSBL",),
    ),
)


@pytest.fixture(scope="module")
def php_error_log_guard(smoke_vm: SmokeVM, webui: WebUI) -> Iterator[PhpErrorLogGuard]:  # noqa: ARG001
    """Snapshot ``php_error.log`` once before the sweep, assert no growth after.

    Module-scoped so it brackets the WHOLE parametrized sweep (oracle condition
    (d)): a new error line written by ANY page during the sweep fails the
    teardown. ``webui`` is requested only to order this after login / VM
    readiness; the diff itself is read over the ``smoke_vm`` SSH path.
    """
    guard = PhpErrorLogGuard(smoke_vm)
    guard.snapshot()
    yield guard
    guard.assert_no_growth()


@pytest.mark.parametrize("page", PAGE_TABLE, ids=lambda p: p.name)
def test_page_renders_clean(page: Page, webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """Each pfBlockerNG page passes the per-page oracle (a)-(c).

    Requesting ``php_error_log_guard`` enrolls this test in the sweep-level (d)
    check: the guard snapshots ``php_error.log`` before the first parametrization
    and asserts no growth after the last, so a page that logs (but does not echo)
    a PHP diagnostic still fails the sweep.
    """
    resp = webui.get(page.path)
    result = evaluate_render(page.path, resp.status_code, resp.text, page.markers)
    assert result.ok, f"render oracle failed for {page.name} ({page.path}): {result.detail}"


def test_page_table_covers_every_pfblockerng_page() -> None:
    """Guard: the table (plus the recorded exclusions) covers the on-disk page set.

    A new pfBlockerNG .php page added to src/ without a Tier-A entry should fail
    this -- the count is asserted so the sweep can't silently skip a page. 14
    servable main pages: general, ip, dnsbl, feeds, alerts, log, sync,
    safesearch, update, blacklist, category, category_edit, threats, plus the
    pfblockerng.php template (excluded). The widget + 2 DNSBL-VIP pages round it
    out; the VIP pages + the GeoIP/Reputation views are the recorded exclusions.
    """
    covered_paths = {p.path.split("?", 1)[0] for p in PAGE_TABLE}
    # 13 distinct main .php files are render-smoked here (pfblockerng.php is the
    # excluded template), plus the widget = 14 distinct paths.
    expected_main = {
        "/pfblockerng/pfblockerng_general.php",
        "/pfblockerng/pfblockerng_ip.php",
        "/pfblockerng/pfblockerng_dnsbl.php",
        "/pfblockerng/pfblockerng_feeds.php",
        "/pfblockerng/pfblockerng_alerts.php",
        "/pfblockerng/pfblockerng_log.php",
        "/pfblockerng/pfblockerng_sync.php",
        "/pfblockerng/pfblockerng_safesearch.php",
        "/pfblockerng/pfblockerng_update.php",
        "/pfblockerng/pfblockerng_blacklist.php",
        "/pfblockerng/pfblockerng_category.php",
        "/pfblockerng/pfblockerng_category_edit.php",
        "/pfblockerng/pfblockerng_threats.php",
        "/widgets/widgets/pfblockerng.widget.php",
    }
    missing = expected_main - covered_paths
    assert not missing, f"Tier-A page table is missing pages: {sorted(missing)}"
    # The two non-hermetic classes are recorded, not dropped.
    excluded_names = {e.name for e in EXCLUDED_FROM_TIER_A}
    assert "geoip_continent_views" in excluded_names
    assert "dnsbl_vip_sinkhole_pages" in excluded_names
