"""Tier-A HTTP render-smoke sweep over every pfBlockerNG page (ADR-14 Phase 2).

Marker ``ui_render`` -- collected only by the smoke/ui workflow
(``pytest tests/smoke -m ui_render --override-ini="addopts="``); the whole
``tests/smoke`` tree is ``--ignore``d in the default ``python -m pytest`` run, so
this never affects the default suite.

Every authenticated pfBlockerNG webConfigurator page (:data:`PAGE_TABLE`) is
GET via the reused Phase-1 :class:`~tests.smoke.ui.webui.WebUI` session and run
through the real oracle (:func:`~tests.smoke.ui.render_oracle.evaluate_render`):
HTTP 200 + no PHP diagnostic in the body + a page-specific marker present, AND
(sweep-level) the on-box ``php_error.log`` gained no new line during the sweep
(:class:`~tests.smoke.ui.render_oracle.PhpErrorLogGuard`). A bare 200 never
passes -- proven by ``test_render_oracle.py`` feeding the oracle a broken body.

Hermeticity (ADR §2 "Hermetic where it claims to be"): every page in the table
renders from local config alone -- none triggers a feed download to produce its
chrome. Pages whose *content* would need a network fetch (the GeoIP/Reputation
per-continent views generated by ``pfblockerng.php``, and the DNSBL-VIP sinkhole
pages served by a separate lighttpd) are recorded in :data:`EXCLUDED_FROM_TIER_A`
with the reason and the access note for Phase 5, NOT silently dropped.
"""

from __future__ import annotations

import json
import re
import subprocess
import uuid
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import pytest

from .. import helpers
from .render_oracle import PhpErrorLogGuard, evaluate_render

if TYPE_CHECKING:
    from collections.abc import Iterator

    from ..conftest import SmokeVM
    from .webui import WebUI

pytestmark = pytest.mark.ui_render


@dataclass(frozen=True)
class Page:
    """One Tier-A page: a webConfigurator path + the markers that prove it rendered.

    ``markers`` are stable strings drawn from the page's real ``$pgtitle``
    breadcrumb crumb and/or a ``Form_Section`` panel title (rendered verbatim
    into the HTML). ``hermetic`` is documentary -- every entry here is hermetic;
    a non-hermetic page lives in :data:`EXCLUDED_FROM_TIER_A` instead.
    """

    name: str
    path: str
    markers: tuple[str, ...]
    hermetic: bool = True


# The authenticated main-webConfigurator pages under src/usr/local/www/pfblockerng/.
# Markers verified against each file's $pgtitle / Form_Section('...') title.
#
# Multi-mode pages are probed in EACH mode they expose via a query parameter, so
# both branches of the page's mode switch are exercised (CLAUDE.md branch
# coverage): pfblockerng_category.php and _category_edit.php render an IP view by
# default and a DNSBL view under ?type=dnsbl; both are listed.
PAGE_TABLE: tuple[Page, ...] = (
    Page("general", "/pfblockerng/pfblockerng_general.php", ("pfBlockerNG", "General Settings")),
    # "Aggregated Aliases" is the ADR-11 pfb_agg_types multi-select label (rendered
    # verbatim) — a third marker so the gate also proves that field renders on the IP page.
    Page(
        "ip",
        "/pfblockerng/pfblockerng_ip.php",
        ("IP Configuration", "ASN configuration", "Aggregated Aliases", "Alias Table Apply Mode"),
    ),
    # "DNS Redirect" is the ADR-36 section title added to this page (Phase 3).
    # "DoT/DoQ Block" is the ADR-37 section title added to this page (Phase 3).
    # "Permit Firewall Rules" + "Interface(s)" are the two field labels of the #478
    # stacked layout (the toggle and the interface selector now render as separate
    # rows) -- the markers prove both fields render; the *visual* stacking is the
    # ui_browser/maintainer tier. "no-AAAA" is the #480 label/section text (verbatim
    # hyphenated form, guarding the #480 text against a casing/hyphen regression).
    Page(
        "dnsbl",
        "/pfblockerng/pfblockerng_dnsbl.php",
        (
            "DNSBL Webserver Configuration",
            "DNSBL Configuration",
            "DNS Redirect",
            "DoT/DoQ Block",
            "Permit Firewall Rules",
            "Interface(s)",
            "no-AAAA",
            "pfb_dnsbl_nonat",  # issue-#381 NAT opt-out checkbox (name= attr in rendered HTML)
            "pfB_DNSBLIP_v4",  # DNSBL IPs help text names the real alias (was stale 'pfB_DNSBL_IP')
            # Permit-rules help renders as one flowing sentence — a stray <br /> split
            # "...to access<br />the DNSBL Webserver", so this space-joined phrase is the
            # red→green guard (absent with the <br />, present once it is a space).
            "Selected Interface(s) to access the ",
        ),
    ),
    # feeds.php is split into IPv4/IPv6/DNSBL ?type sub-tabs (ADR-16 Phase 3). Each type
    # is probed; the type-specific marker is the active type's "Feed Settings" alias-name
    # StaticText label ("IPv4 Alias name(s):" etc.), which renders ONLY for the active
    # type -- so it distinguishes the three views (the panel title is shared by all). The
    # coverage guard strips "?", so all three collapse to the one base path.
    Page(
        "feeds_ipv4",
        "/pfblockerng/pfblockerng_feeds.php?type=ipv4",
        ("Pre-defined Alias/Group/Feeds", "IPv4 Alias name(s):"),
    ),
    Page(
        "feeds_ipv6",
        "/pfblockerng/pfblockerng_feeds.php?type=ipv6",
        ("Pre-defined Alias/Group/Feeds", "IPv6 Alias name(s):"),
    ),
    Page(
        "feeds_dnsbl",
        "/pfblockerng/pfblockerng_feeds.php?type=dnsbl",
        ("Pre-defined Alias/Group/Feeds", "DNSBL Alias name(s):"),
    ),
    Page("alerts", "/pfblockerng/pfblockerng_alerts.php", ("Alert Settings",)),
    # The Reports sub-tabs are the same page under ?view=; the stats views (IP Block
    # Stats + DNSBL Block Stats, issue #387) traverse the view switch + the per-stat-type
    # two-column render path. The sub-tab nav label is rendered on every view
    # (data-independent), so it is the marker. The pie panels themselves are alert-data
    # gated, and the responsive-layout + print-stylesheet *visual* correctness added for
    # #387 is an ADR-14 out-of-CI item (ui_browser tier + maintainer), not asserted here;
    # these entries guard the stats view-handler paths against a PHP render regression.
    Page("alerts_ip_block_stat", "/pfblockerng/pfblockerng_alerts.php?view=ip_block_stat", ("IP Block Stats",)),
    Page("alerts_dnsbl_stat", "/pfblockerng/pfblockerng_alerts.php?view=dnsbl_stat", ("DNSBL Block Stats",)),
    Page("log", "/pfblockerng/pfblockerng_log.php", ("Log/File Browser selections",)),
    Page("sync", "/pfblockerng/pfblockerng_sync.php", ("XMLRPC Sync Settings",)),
    Page("safesearch", "/pfblockerng/pfblockerng_safesearch.php", ("SafeSearch settings", "DNSBL SafeSearch")),
    Page(
        "update",
        "/pfblockerng/pfblockerng_update.php",
        ("Update Settings", "Schedule"),
    ),
    # blacklist.php is always the DNSBL Category view; the long info line is a stable literal.
    Page(
        "blacklist",
        "/pfblockerng/pfblockerng_blacklist.php",
        ("DNSBL Category Feeds are processed first", "DNSBL Category"),
    ),
    # category.php: default IP view (?type=ipv4) AND the DNSBL view (?type=dnsbl).
    Page("category_ip", "/pfblockerng/pfblockerng_category.php?type=ipv4", ("Summary", "pfBlockerNG")),
    Page("category_dnsbl", "/pfblockerng/pfblockerng_category.php?type=dnsbl", ("Summary", "DNSBL")),
    # category_edit.php: default IP view AND the DNSBL view; Form_Section('Advanced Tuneables') is unique to it.
    Page("category_edit_ip", "/pfblockerng/pfblockerng_category_edit.php?type=ipv4", ("Advanced Tuneables",)),
    Page("category_edit_dnsbl", "/pfblockerng/pfblockerng_category_edit.php?type=dnsbl", ("Advanced Tuneables",)),
    # threats.php REQUIRES a host/domain/port param -- with none it print_info_box()es and exit()s
    # before rendering $pgtitle. A syntactically-valid param renders the lookup page chrome; the
    # threat links it draws are <a href> only (no server-side network call), so it stays hermetic.
    # All THREE positive views ($title is 'Source IP'/'Domain'/'Port' -> the "Threat <title> Lookup"
    # breadcrumb + "Threat <title>:" panel) are probed (CLAUDE.md branch coverage); the reject /
    # no-request branches are covered by test_threats_rejects_malformed_lookup below. The {domain}
    # placeholder is filled per run with helpers.unique_domain() (uuid-*.com) -- the smoke-domain
    # rule (never a fixed/RFC-6761 name); host/port use a documentation IP (TEST-NET-3) + a valid
    # port (no network coupling either way).
    Page("threats_domain", "/pfblockerng/pfblockerng_threats.php?domain={domain}", ("Threat Domain", "Source IP")),
    Page(
        "threats_host", "/pfblockerng/pfblockerng_threats.php?host=203.0.113.5", ("Threat Source IP", "Threat Lookups")
    ),
    Page("threats_port", "/pfblockerng/pfblockerng_threats.php?port=8443", ("Threat Port",)),
    # ADR-12 Update Hooks (pre/post update-command list). Reached as the Update -> Hooks sub-tab;
    # the markers are the Form_Section titles ('Update Hooks (Pre/Post Update Scripts)' + 'Hook
    # Entries'), stable regardless of the tab restructure. The sub-tab nav itself is pinned by
    # test_update_hooks_subtab_relocation.
    Page("hooks", "/pfblockerng/pfblockerng_hooks.php", ("Update Hooks", "Hook Entries")),
    # The dashboard widget (auth-gated; $nocsrf=true). A direct GET renders the alias-table panel
    # whose hidden inputs (id="pfblockerngack") are a stable marker; the AJAX getNew* paths need a
    # query param, so the plain GET exercises the full-render branch. "Show Aggregated Aliases" is
    # the #494 settings checkbox label (rendered in the widget's settings panel), proving the new
    # toggle renders.
    Page(
        "widget",
        "/widgets/widgets/pfblockerng.widget.php",
        ('id="pfblockerngack"', "Alias", "Show Aggregated Aliases"),
    ),
)


@dataclass(frozen=True)
class ExcludedPage:
    """A pfBlockerNG page deliberately kept OUT of the hermetic Tier-A sweep.

    Recorded (ADR §2 "don't silently drop") with why it is non-hermetic / not
    reachable via the authenticated webConfigurator session, and how Phase 5/CI
    should reach it instead.
    """

    name: str
    path: str
    reason: str
    access_note: str
    markers: tuple[str, ...] = field(default_factory=tuple)


# Pages NOT in the hermetic Tier-A sweep, with the reason + the Phase-5 access note.
EXCLUDED_FROM_TIER_A: tuple[ExcludedPage, ...] = (
    ExcludedPage(
        name="geoip_continent_views",
        path="/pfblockerng/pfblockerng_<Continent>.php (+ pfblockerng_reputation.php)",
        reason=(
            "pfblockerng.php is a CLI dispatcher + a TEMPLATE: it generates the per-continent "
            "(Top Spammers/Africa/.../Proxy_and_Satellite) and Reputation PHP pages via "
            "file_put_contents only AFTER a MaxMind GeoIP update -- which needs a network download "
            "and a MaxMind key. Those files do not exist on a fresh box, so they cannot render "
            "hermetically."
        ),
        access_note=(
            "Phase 5 (egress-allowed Tier-B leg): run a GeoIP update so the continent pages are "
            "generated, then render-smoke them. A direct GET of pfblockerng.php itself runs the "
            "template path, not a settings page, so it is not a Tier-A target."
        ),
    ),
    ExcludedPage(
        name="dnsbl_vip_sinkhole_pages",
        path="/index.php and /dnsbl_default.php under www/ (DNSBL VIP webserver)",
        reason=(
            "www/index.php + dnsbl_default.php are served by the DNSBL sinkhole lighttpd on the "
            "DNSBL VIP (ports 8081/8443), NOT the main webConfigurator: no guiconfig auth, and "
            "index.php exit()s unless HTTP_HOST is a valid hostname and REQUEST_URI=='/' (otherwise "
            "it returns a 1x1 GIF). dnsbl_default.php is a template INCLUDED by dnsbl_active.php, "
            "never served standalone. The authenticated session on :8080 cannot reach them."
        ),
        access_note=(
            "Phase 5: fetch the VIP sinkhole directly -- http://<DNSBL_VIP>:8081/ with a Host header "
            "set to a blocked hostname and REQUEST_URI '/' to get the DNSBL-Full block page; the "
            "marker is 'Site blocked via DNSBL' (dnsbl_default.php <title>). No webConfigurator login."
        ),
        markers=("Site blocked via DNSBL",),
    ),
)


@pytest.fixture(scope="module")
def php_error_log_guard(smoke_vm: SmokeVM, webui: WebUI) -> Iterator[PhpErrorLogGuard]:  # noqa: ARG001
    """Snapshot ``php_error.log`` once before the sweep, assert no growth after.

    Module-scoped so it brackets the WHOLE parametrized sweep (oracle condition
    (d)): a new error line written by ANY page during the sweep fails the
    teardown. ``webui`` is requested only to order this after login / VM
    readiness; the diff itself is read over the ``smoke_vm`` SSH path.
    """
    guard = PhpErrorLogGuard(smoke_vm)
    guard.snapshot()
    yield guard
    guard.assert_no_growth()


@pytest.mark.parametrize("page", PAGE_TABLE, ids=lambda p: p.name)
def test_page_renders_clean(page: Page, webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """Each pfBlockerNG page passes the per-page oracle (a)-(c).

    Requesting ``php_error_log_guard`` enrolls this test in the sweep-level (d)
    check: the guard snapshots ``php_error.log`` before the first parametrization
    and asserts no growth after the last, so a page that logs (but does not echo)
    a PHP diagnostic still fails the sweep.
    """
    # Fill the {domain} placeholder (threats page) with a unique uuid-*.com per
    # run; other paths carry no placeholder and pass through unchanged.
    path = page.path.format(domain=helpers.unique_domain()) if "{domain}" in page.path else page.path
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, page.markers)
    assert result.ok, f"render oracle failed for {page.name} ({path}): {result.detail}"


# ADR-11: the IP page's pfb_agg_types multi-select must render with ALL FOUR
# option branches (Deny/Permit/Match/Native) AND its no-rule help caveat. Asserting
# every option proves each branch of the select is emitted (not just the label), and the
# caveat substring proves the help text — the user's only signal that an aggregate is
# reference-only (no firewall rule) — actually rendered. Substrings verified against the
# real pfblockerng_ip.php: the four $options_pfb_agg_types keys render as Form_Select
# option values ('value="<Type>"'), and the setHelp() copy contains "no firewall rule".
_AGG_TYPE_OPTIONS = ("Deny", "Permit", "Match", "Native")
_AGG_HELP_CAVEAT = "no firewall rule"
_GENERAL_PAGE = "/pfblockerng/pfblockerng_general.php"
_IP_PAGE = "/pfblockerng/pfblockerng_ip.php"


def test_ip_page_renders_aggregate_select(webui: WebUI) -> None:
    """The IP page renders the pfb_agg_types select: all four options + the caveat.

    Hermetic (no network — the IP page renders from local config alone). GET the
    page and assert: (1) the ``pfb_agg_types`` field is present; (2) EACH of the four
    option values (Deny/Permit/Match/Native) is emitted — every branch of the multi-
    select, not just one (CLAUDE.md branch coverage); and (3) the "no firewall rule" help
    caveat — the load-bearing "these are reference-only IP-sets" wording — is present.
    Pairs with the PAGE_TABLE "Aggregated Aliases" label marker (the field's presence) to
    pin both the field and its full option set + help.
    """
    resp = webui.get(_IP_PAGE)
    assert resp.status_code == 200, f"GET {_IP_PAGE} -> HTTP {resp.status_code} (expected 200)"
    body = resp.text
    assert "pfb_agg_types" in body, "pfb_agg_types select not present on the IP page"
    missing = [opt for opt in _AGG_TYPE_OPTIONS if f'value="{opt}"' not in body]
    assert not missing, f"pfb_agg_types select missing option value(s) {missing} (each is a branch that must render)"
    assert _AGG_HELP_CAVEAT in body, (
        f"pfb_agg_types help caveat {_AGG_HELP_CAVEAT!r} (the no-rule wording) not rendered on the IP page"
    )


_UPDATE_PAGE = "/pfblockerng/pfblockerng_update.php"
_HOOKS_PAGE = "/pfblockerng/pfblockerng_hooks.php"


def test_update_hooks_subtab_relocation(webui: WebUI) -> None:
    """Update Hooks moved from a top-level tab to an Update sub-tab (Run | Hooks).

    The standalone 'Update Hooks' top tab was replaced by a second display_top_tabs
    row under Update — Run -> the update page, Hooks -> the hooks page (the same
    sub-tab idiom the Feeds page uses). Assert the new shape AND that the old
    top-level tab is gone (hermetic — all three pages render from local config).

    Given the restructured tabs,
    When GET pfblockerng_update.php and pfblockerng_hooks.php,
    Then each renders the sub-tab row: a 'Run' anchor and a 'Hooks' anchor, with the
      Hooks one linking the hooks page and the Run one linking the update page (both
      anchors are NEW — neither page exposed a 'Run' or bare 'Hooks' tab before).
    And the old standalone 'Update Hooks' tab is gone: it is ABSENT from the update
      page entirely, and from the General witness page (a page that is neither Update
      nor Hooks) — while that page keeps its 'Update' top tab. The absence is the
      before/after guard: 'Update Hooks' was present as a top tab on every page before
      this change, so these assertions would have FAILED then and pass only after the
      move. (The hooks page itself still contains the literal 'Update Hooks' in its
      Form_Section title, so absence is asserted on the update + witness pages, not it.)

    The active-tab-tracks-the-page branch (Run active on the update page, Hooks active
    on the hooks page) is the Tier-B browser half (test_browser_hooks.py).
    """
    # --- Run page (pfblockerng_update.php): both sub-tabs render; old top tab gone. ---
    body = webui.get(_UPDATE_PAGE).text
    assert ">Run</a>" in body, "update page is missing the 'Run' sub-tab anchor"
    assert ">Hooks</a>" in body, "update page is missing the 'Hooks' sub-tab anchor"
    assert _HOOKS_PAGE in body, "update page 'Hooks' sub-tab does not link the hooks page"
    # "Update Hooks" is a tab-nav guard: the removed top tab was the ONLY occurrence of
    # that literal on the update page, so its absence proves the tab is gone. (If future
    # help text on this page ever references the hooks page by that name, narrow this to
    # the nav element rather than the whole body.)
    assert "Update Hooks" not in body, "stale 'Update Hooks' top-level tab still rendered on the update page"

    # --- Hooks page (pfblockerng_hooks.php): both sub-tabs render. ---
    body = webui.get(_HOOKS_PAGE).text
    assert ">Run</a>" in body, "hooks page is missing the 'Run' sub-tab anchor"
    assert ">Hooks</a>" in body, "hooks page is missing the 'Hooks' sub-tab anchor"
    assert _UPDATE_PAGE in body, "hooks page 'Run' sub-tab does not link the update page"

    # --- Witness page (General): the 'Update Hooks' top tab is gone; 'Update' remains. ---
    body = webui.get(_GENERAL_PAGE).text
    assert "Update Hooks" not in body, "'Update Hooks' top-level tab is still present on the General page"
    assert ">Update</a>" in body, "the 'Update' top-level tab was wrongly removed from the General page"
    assert _UPDATE_PAGE in body, "the General page no longer links the Update tab"


def test_general_page_keep_help_upgrade_warning(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:  # noqa: ARG001
    """The General page's 'Keep Settings' help warns that keep=off wipes settings on a version upgrade (#697).

    Given the General page,
    When GET,
    Then the 'Keep Settings' help text states the wipe also applies to pfSense version upgrades, and
    the removed 'Keep enabled during version upgrades' toggle is gone.

    Fail-before / pass-after: the disclaimer sentence is added in #697 (fails on the pre-#697 page),
    and the removed checkbox must be absent (fails while the old toggle still renders).
    """
    resp = webui.get(_GENERAL_PAGE)
    body = resp.text
    result = evaluate_render(_GENERAL_PAGE, resp.status_code, body, ("General Settings",))
    assert result.ok, f"General page render oracle failed: {result.detail}"
    assert "This also applies to a major pfSense version upgrade" in body, "keep=off upgrade-wipe disclaimer missing"
    assert 'name="pfb_keep_on_upgrade"' not in body, "the removed pfb_keep_on_upgrade toggle still renders (#697)"


def test_hooks_page_documents_lifecycle_env_vars(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:  # noqa: ARG001
    """The hooks page lists the PFB_POST_INSTALL / PFB_PRE_UNINSTALL env vars (#684 doc gap, #687).

    Given the hooks page,
    When GET,
    Then the Environment help text names both lifecycle variables so hook authors can react to
        install/upgrade and uninstall passes.

    Fail-before / pass-after: the vars shipped in the previous release without help text; both
    assertions fail on that build and pass once the help text lists them.
    """
    body = webui.get(_HOOKS_PAGE).text
    result = evaluate_render(_HOOKS_PAGE, 200, body, ("Update Hooks",))
    assert result.ok, f"Hooks page render oracle failed: {result.detail}"
    assert "PFB_POST_INSTALL" in body, "hooks page help does not document PFB_POST_INSTALL"
    assert "PFB_PRE_UNINSTALL" in body, "hooks page help does not document PFB_PRE_UNINSTALL"


def test_update_log_textareas_are_readonly(webui: WebUI) -> None:
    """The Update page's two log windows are display-only — they render readonly.

    The 'pfb_status' (progress) and 'pfb_output' (log) textareas are live-tail
    viewers, not input fields; before this change they were plain editable
    textareas, so a user could accidentally cut/type into them (the content is
    harmless — it is repopulated from the log file on refresh — but it is confusing
    and a footgun). Each must now carry the readonly attribute.

    Given the rendered Update page,
    When each log textarea opening tag is located by name,
    Then it contains the readonly attribute. (Pre-fix the tags had no readonly, so
      these assertions FAIL on the old markup and pass only after it.)
    """
    body = webui.get(_UPDATE_PAGE).text
    for name in ("pfb_status", "pfb_output"):
        m = re.search(r"<textarea\b[^>]*\bname=([\"'])" + re.escape(name) + r"\1[^>]*>", body)
        assert m is not None, f"update page is missing the '{name}' textarea"
        tag = m.group(0)
        assert re.search(r"\breadonly\b", tag), f"'{name}' textarea is editable (no readonly): {tag}"


def test_update_ajax_tail_returns_wellformed_json(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The ?ajax=tail live-log poll endpoint returns well-formed JSON with the poller's contract keys.

    The handler now calls session_write_close() before reading the log so the poll never holds the
    PHP session write-lock — otherwise every 1s poll serialises behind any other same-session
    request, and one such blocked poll freezes the live tail during a long no-output gap (an
    HAProxy graceful-restart drain in an update hook). This guards that early close: it must not
    emit a warning/notice into the response (which would corrupt the JSON) and the endpoint must
    still return the {running, done, offset} contract the client poller consumes.

    Given the Update page's AJAX tail endpoint,
    When it is fetched with no offset (the client's first poll),
    Then the body parses as JSON and carries the running/done/offset keys (done is a bool).
    """
    resp = webui.get(_UPDATE_PAGE + "?ajax=tail")
    assert resp.status_code == 200, f"ajax=tail returned HTTP {resp.status_code}, body={resp.text[:200]!r}"
    # json.loads FAILS if a PHP warning/notice leaked into the body ahead of the JSON — exactly
    # the failure a misplaced session_write_close() (or an un-started session) would produce.
    payload = json.loads(resp.text)
    for key in ("running", "done", "offset"):
        assert key in payload, f"ajax=tail JSON missing the poller-contract key {key!r}: {payload!r}"
    assert isinstance(payload["done"], bool), f"'done' must be a bool for the client stop-check: {payload!r}"


def test_update_revamp_controls_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """Update page revamp: new scope + force-mode controls present; old opaque ones gone.

    The opaque Force/Update/Cron/Reload radio trio was replaced with an explicit Run
    Scope radio (ip / dnsbl / both) and a Force radio group (none / parse / download /
    both).  A read-only Schedule section shows last-run and next-due per ledger job.

    Scenario: Update page revamp controls render after Phase 6 + Force-mode addition.
      Background: pfBlockerNG deployed; Update page renders cleanly.

    Given the Update page renders via the clean-render oracle (200, no PHP diagnostic,
      "Update Settings" + "Schedule" section markers present),

    When the body is inspected for the new control ids and the old control ids,

    Then the new scope radio IDs are PRESENT (``pfb_scope_both``, ``pfb_scope_ip``,
      ``pfb_scope_dnsbl``) — proving the scope selector rendered;
    And the Force radio group field name is PRESENT (``pfb_force_mode``) — proving the
      four-mode force selector rendered (none / parse / download / both);
    And ``Run Scope`` and ``Force`` group labels are PRESENT — proving the new form
      groups rendered;
    And ``Schedule`` section text is PRESENT — proving the new section rendered;
    And the old opaque radio IDs are ABSENT (``pfb_force_update``, ``pfb_force_cron``,
      ``pfb_force_reload``, ``pfb_reload_option_all``) — PRESENT before Phase 6 in the
      old Force/Reload radio groups, so their absence is the before/after fail guard;
    And the old ``pfb_run_force`` checkbox name is ABSENT — replaced by ``pfb_force_mode``.

    ``php_error_log_guard`` enrolls this GET in the module-level no-growth sweep.
    """
    resp = webui.get(_UPDATE_PAGE)
    result = evaluate_render(_UPDATE_PAGE, resp.status_code, resp.text, ("Update Settings", "Schedule"))
    assert result.ok, f"Update page render oracle failed: {result.detail}"
    body = resp.text

    # PRESENT: new Run Scope radio control IDs
    for needle in ('id="pfb_scope_both"', 'id="pfb_scope_ip"', 'id="pfb_scope_dnsbl"'):
        assert needle in body, f"Update page missing new scope radio {needle!r}"

    # PRESENT: Force radio group (four-mode: none / parse / download / both)
    assert 'name="pfb_force_mode"' in body, (
        "Update page missing 'pfb_force_mode' Force radio group — "
        "the four-mode force selector (none/parse/download/both) did not render"
    )

    # PRESENT: section / group labels confirming the new design
    for needle in ("Run Scope", "Force", "Schedule"):
        assert needle in body, f"Update page missing new label {needle!r}"

    # ABSENT: old opaque force/reload radio IDs (PRESENT in old code → fail before Phase 6)
    for needle in (
        'id="pfb_force_update"',
        'id="pfb_force_cron"',
        'id="pfb_force_reload"',
        'id="pfb_reload_option_all"',
    ):
        assert needle not in body, f"Update page still has old control {needle!r} — Phase-6 revamp not applied"

    # ABSENT: old single-checkbox force name (replaced by the four-mode radio group)
    assert 'name="pfb_run_force"' not in body, (
        "Update page still has old 'pfb_run_force' checkbox — it must be replaced by the 'pfb_force_mode' radio group"
    )


def test_update_page_schedule_and_help_polish(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """Update-page polish: honest DNSBL-category state, itemized Force help, clean Run-Scope
    help, and spaced Run/View buttons.

    Four user-reported alpha.6 rough edges on the Update page, all guarded here against
    regression (each assertion fails on the pre-fix markup):

    Scenario: the Update page renders the corrected Schedule + help + button markup.
      Background: pfBlockerNG deployed with the DNSBL Category feature NOT configured
      (the suite never enables it), so the category job can never run.

    Given the Update page renders cleanly (200, no PHP diagnostic, section markers),

    When the body is inspected,

    Then the DNSBL Category schedule row reports ``Disabled`` rather than the misleading
      ``Not yet run`` — the bl job only runs (and records a ledger entry) when the feature
      is enabled with a category selected, so an unconfigured install must say why it is
      not scheduled, not pretend a run is pending (pre-fix it showed ``<em>Not yet run</em>``);
    And the Run Scope help no longer carries the stray ``on Run Now`` qualifier;
    And the Force help is itemized per mode (a ``<strong>`` label per None/Parse/Download/Both)
      instead of one run-on sentence (pre-fix there were no ``<strong>`` mode labels);
    And the Run button carries an inline right margin so it is visibly separated from the
      View button on desktop too (pre-fix the column-wrapped buttons sat flush, the gap only
      appearing on mobile).

    ``php_error_log_guard`` enrolls this GET in the module-level no-growth sweep.
    """
    resp = webui.get(_UPDATE_PAGE)
    result = evaluate_render(_UPDATE_PAGE, resp.status_code, resp.text, ("Update Settings", "Schedule"))
    assert result.ok, f"Update page render oracle failed: {result.detail}"
    body = resp.text

    # DNSBL Category row: feature unconfigured ⇒ "Disabled". Scope to THIS row's value cell
    # (the markup right after its label), not the whole body, so unrelated markup can't pass it.
    assert "DNSBL category" in body, "Update page missing the 'DNSBL category' schedule row"
    cat_row = body.split("DNSBL category", 1)[1][:500]
    assert "<em>Disabled</em>" in cat_row, (
        "DNSBL category row should read 'Disabled' when the category feature is off, "
        f"not the misleading 'Not yet run' — row markup was: {cat_row[:200]!r}"
    )

    # Run Scope help: the stray 'on Run Now' qualifier is gone. Match the precise OLD help
    # string (not a bare "on Run Now", which also appears in an unrelated inline JS comment).
    assert "Which lists to sync: Both, IP-only, or DNSBL-only." in body, "Run Scope help text not updated"
    assert "Which lists to sync on Run Now" not in body, "Run Scope help still carries the stray 'on Run Now' qualifier"

    # Force help: itemized with a bold label per mode.
    for needle in (
        "<strong>None:</strong>",
        "<strong>Parse:</strong>",
        "<strong>Download:</strong>",
        "<strong>Both:</strong>",
    ):
        assert needle in body, f"Force help not itemized — missing {needle!r}"

    # Run button: inline right margin (desktop spacing). Scope to the Run Now <button>
    # element itself, not the whole body, so the margin is proven to be ON that button.
    run_btn = next((b for b in re.findall(r"<button\b.*?</button>", body, re.S) if "Run Now" in b), None)
    assert run_btn is not None, "Update page missing the Run Now button"
    assert "margin-right" in run_btn, (
        f"Run button has no inline right margin — it will sit flush against View on desktop: {run_btn!r}"
    )


def test_dnsbl_idn_blocking_fields_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The ADR-08 'IDN Blocking' selector + its two Confusable sub-toggles render
    cleanly on the DNSBL page — so a regression that drops or breaks the field is
    caught at the render tier (not just by the matcher smoke).

    Asserts the page passes the clean-render oracle AND that the three POST field
    names (``pfb_idn`` select + the two sub-toggle checkboxes) and the 'IDN Blocking'
    / 'Confusable' option labels are present in the body. ``php_error_log_guard``
    enrolls this GET in the module-level no-growth sweep.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        'name="pfb_idn"',
        'name="pfb_idn_block_malicious"',
        'name="pfb_idn_escalate_suspicious"',
        "IDN Blocking",
        ">Always<",  # the 'all' mode option label (renamed from "All-IDN")
        ">Confusable<",
    ):
        assert needle in body, f"DNSBL page is missing the IDN-mode marker {needle!r}"


def test_dnsbl_control_fields_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The DNSBL Control toggle + its deprecated legacy DNS-TXT sub-toggle (PFBL-03) render
    cleanly on the DNSBL page — so a regression that drops or breaks either field is caught
    at the render tier.

    Asserts the page passes the clean-render oracle AND that both POST field names
    (``pfb_control`` + ``pfb_control_legacy``) and their labels are present in the body.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        'name="pfb_control"',
        'name="pfb_control_legacy"',
        "DNSBL Control",
        "DNSBL Control (legacy DNS TXT)",
    ):
        assert needle in body, f"DNSBL page is missing the control marker {needle!r}"


def test_dnsbl_lenient_parsing_field_renders(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The ADR-22 'Lenient Feed Parsing' toggle renders cleanly on the DNSBL page — so a
    regression that drops or breaks the field is caught at the render tier (not only by the
    feed-parsing smoke).

    Asserts the page passes the clean-render oracle AND that the POST field name
    (``pfb_dnsbl_lenient``) and its 'Lenient Feed Parsing' label are present in the body.
    ``php_error_log_guard`` enrolls this GET in the module-level no-growth sweep.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        'name="pfb_dnsbl_lenient"',
        "Lenient Feed Parsing",
    ):
        assert needle in body, f"DNSBL page is missing the lenient-parsing marker {needle!r}"


def test_dnsbl_redir_exception_and_fill_fields_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The ADR-36/37 DNS-Redirect & DoT/DoQ-Block exception-alias autocomplete + the
    interface quick-fill rewrite render cleanly on the DNSBL page — so a regression that
    drops the autocomplete wiring or reverts the fill helper is caught at the render tier
    (the browser-only behaviours themselves are exercised by the Tier-B browser tests).

    Asserts the page passes the clean-render oracle AND that the markers for all three
    PR-660 fixes are present: the two exception-alias input field names, the autocomplete
    bootstrap function + its alias-name source array, and the ``.val(...)`` fill rewrite
    (the form that replaced the broken per-option ``.prop('selected')`` loop).
    ``php_error_log_guard`` enrolls this GET in the module-level no-growth sweep.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        # (2) Exception Alias fields + their autocomplete wiring.
        'name="dnsbl_redir_exclude"',
        'name="dnsbl_dot_block_exclude"',
        "pfb_redir_exclude_autocomplete",
        "pfb_alias_names",
        # (3) The fill rewrite — the canonical .val([...]) form (not the old .prop() loop),
        # AND the bracketed-name selectors: a pfSense multi-select renders id/name as
        # "<field>[]", so the fill must target it by name, not the broken bracket-free "#id".
        ".val(pfb_redir_fill_ifaces)",
        'select[name="dnsbl_redir_int[]"]',
        'select[name="dnsbl_dot_block_int[]"]',
    ):
        assert needle in body, f"DNSBL page is missing the redirect/fill marker {needle!r}"


def test_dnsbl_doh_list_select_is_bounded_scrollable(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The 'DoH/DoT/DoQ Blocking List' multi-select renders with a bounded, scrollable
    height instead of expanding to show all ~140 providers at once.

    A ``<select multiple>`` whose ``size`` exceeds its option count shows every row with no
    scrollbar; the field previously carried ``size="140"`` (one row per provider), so the
    list dominated the page. Capping ``size`` below the option count makes the browser render
    a fixed-height, natively scrollable box — matching the TLD multi-select (``size="20"``).

    Pins the change: against the pre-change page the oversized ``size="140"`` was present
    (this fails), against the post-change page it is gone and the field renders with the
    bounded ``size="20"`` (this passes). ``php_error_log_guard`` enrolls this GET in the
    module-level no-growth sweep.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    # The field still renders (a pfSense multi-select renders its name as "<field>[]").
    assert 'name="safesearch_doh_list[]"' in body, "DNSBL page is missing the DoH/DoT/DoQ Blocking List select"
    # The oversized, unscrollable height is gone and replaced by the bounded one.
    assert 'size="140"' not in body, "DoH/DoT/DoQ Blocking List select still renders the oversized size='140'"
    assert 'size="20"' in body, "DoH/DoT/DoQ Blocking List select is missing the bounded scrollable size='20'"


def test_dnsbl_encrypted_dns_sections_order(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The DNS Redirect and DoT/DoQ Block sections render ABOVE the DoH/DoT/DoQ Blocking
    (DNS over HTTPS/TLS/QUIC Blocking) section on the DNSBL page.

    The encrypted-DNS controls were reordered so the active interception controls (redirect
    plain DNS, block DoT/DoQ) come first and the provider-name blocklist (DoH/DoT/DoQ
    Blocking) sits last. This is a structural/positional change, so the order of the section
    headings in the rendered HTML is the oracle.

    Pins the change: pre-change the DoH section heading appeared FIRST (so it preceded the
    other two and these assertions fail); post-change it appears last and both ``DNS
    Redirect`` and ``DoT/DoQ Block`` precede it.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
    assert result.ok, f"DNSBL render oracle failed: {result.detail}"
    body = resp.text
    doh_pos = body.find("DNS over HTTPS/TLS/QUIC Blocking")
    redir_pos = body.find("DNS Redirect")
    dot_pos = body.find("DoT/DoQ Block")
    assert doh_pos != -1, "DNSBL page is missing the 'DNS over HTTPS/TLS/QUIC Blocking' section heading"
    assert redir_pos != -1, "DNSBL page is missing the 'DNS Redirect' section heading"
    assert dot_pos != -1, "DNSBL page is missing the 'DoT/DoQ Block' section heading"
    assert redir_pos < doh_pos, (
        f"'DNS Redirect' (pos {redir_pos}) must render above 'DNS over HTTPS/TLS/QUIC Blocking' (pos {doh_pos})"
    )
    assert dot_pos < doh_pos, (
        f"'DoT/DoQ Block' (pos {dot_pos}) must render above 'DNS over HTTPS/TLS/QUIC Blocking' (pos {doh_pos})"
    )


def test_feeds_custom_panel_heading_renders(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The second Feeds panel — the one listing user-configured feeds that don't match the
    predefined catalog — is headed "Custom Feeds", not the former "Unknown user defined Feeds".

    The heading is the shared panel title (renders on every ?type sub-tab, outside the
    row-rendering guard), so it is a stable render marker. This is a dedicated assertion rather
    than an entry in PAGE_TABLE because the render oracle matches markers with ``any()``: adding
    "Custom Feeds" to a tuple that already carries a present marker would pass on the old heading
    too (coverage theater). Asserting the new string present AND the old string absent gives an
    unambiguous fail-before / pass-after for the rename.
    """
    path = "/pfblockerng/pfblockerng_feeds.php?type=ipv4"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("Pre-defined Alias/Group/Feeds",))
    assert result.ok, f"Feeds render oracle failed: {result.detail}"
    body = resp.text
    assert "Custom Feeds" in body, "Feeds page is missing the 'Custom Feeds' panel heading"
    assert "Unknown user defined Feeds" not in body, (
        "Feeds page still shows the old 'Unknown user defined Feeds' heading"
    )


def test_states_removal_help_references_ip_tab(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The category-edit 'States Removal' help points at the IP tab, where 'Kill States' lives.

    The 'Kill States' (``killstates``) checkbox is on the IP tab (pfblockerng_ip.php), so the
    cross-reference in the IP-alias edit page's 'States Removal' help must read '(IP Tab)', not
    the stale '(General Tab)'.  The field renders only for the IPv4/IPv6 alias type, so this
    probes category_edit with ``?type=ipv4``.

    Fail-before / pass-after: before the fix the States Removal help reads '(General Tab)', so
    the '(IP Tab)' assertion fails; the negative assertion guards against the stale wording
    returning.

    Both needles are scoped to the States Removal sentence ('... you can disable States
    removal') so they cannot be satisfied by the sibling 'Enable Logging' help on the same
    page, which legitimately references the General tab (for the Global Logging override).
    """
    path = "/pfblockerng/pfblockerng_category_edit.php?type=ipv4"
    resp = webui.get(path)
    result = evaluate_render(path, resp.status_code, resp.text, ("States Removal",))
    assert result.ok, f"category_edit (ipv4) render oracle failed: {result.detail}"
    body = resp.text
    assert "(IP Tab), you can disable States removal" in body, (
        "States Removal help is missing the corrected '(IP Tab)' cross-reference "
        "(the 'Kill States' option lives on the IP tab)"
    )
    assert "(General Tab), you can disable States removal" not in body, (
        "States Removal help still carries the stale '(General Tab)' cross-reference -- "
        "'Kill States' is on the IP tab, not the General tab"
    )


# ADR-23: the setup wizard's DNSBL step now surfaces ADR-13's pfb_dnsvip_auto auto-VIP
# toggle. Core wizard.php renders ONE step per GET, indexed by a 0-based `stepid` (verified
# against pfSense upstream wizard.php: `$stepid` defaults to "0" and indexes $pkg['step']
# directly). The DNSBL step is the 4th <step> (<id>4</id>, "DNSBL Component Configuration")
# in pfblockerng_wizard.xml -> stepid=3. The wizard is NOT in PAGE_TABLE (a core-rendered
# www/wizards/ page, not a www/pfblockerng/ one), so it gets its own render assertion.
_WIZARD_DNSBL_STEP = "/wizard.php?xml=pfblockerng_wizard.xml&stepid=3"


def test_wizard_dnsbl_step_renders_auto_vip(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """ADR-23: the wizard DNSBL step renders the Auto VIP (pfb_dnsvip_auto) checkbox cleanly.

    The setup wizard exposes ADR-13's auto-create toggle on its DNSBL step so a first-run
    user need not pre-create a sinkhole VIP — a render regression that drops/breaks the field
    (or the wizard step itself) must fail here, not only in the maintainer on-box check. A
    direct authenticated GET renders the step regardless of the first-run dismissal the
    `webui` fixture performs (dismissal only suppresses general.php's auto-launch redirect,
    not wizard.php itself).

    Asserts the step passes the clean-render oracle (200, no PHP diagnostic, the step-title
    Form_Section marker present, not the login form) AND — from three independent wizard.php
    render paths — that the field's POST name (`pfb_dnsvip_auto`), its 'Auto VIP' displayname
    label, and the 'Create VIPs automatically' setHelp() wording are present. The IPv4/IPv6
    manual selectors carry the new "manual mode only" note, asserted too so the mode framing
    that pairs with the checkbox is pinned. `php_error_log_guard` enrolls this GET in the
    module-level no-growth sweep.
    """
    resp = webui.get(_WIZARD_DNSBL_STEP)
    result = evaluate_render(_WIZARD_DNSBL_STEP, resp.status_code, resp.text, ("DNSBL Component Configuration",))
    assert result.ok, f"wizard DNSBL-step render oracle failed: {result.detail}"
    body = resp.text
    for needle in (
        "pfb_dnsvip_auto",  # the checkbox field's POST name (input name/id)
        "Auto VIP",  # the <displayname> label
        "Create VIPs automatically",  # the <description> setHelp() wording
        "manual mode only",  # the pfb_dnsvip4/6 selectors' new mode-dependency note
    ):
        assert needle in body, f"wizard DNSBL step is missing the Auto VIP marker {needle!r}"


# threats.php's NEGATIVE branches: each malformed/absent param print_info_box()es
# a specific message and exit()s BEFORE the "$pgtitle" lookup-page chrome. These
# pair with the positive threats_{domain,host,port} entries above (CLAUDE.md
# branch coverage: prove the validators REJECT, not only that valid input renders).
THREATS_PAGE = "/pfblockerng/pfblockerng_threats.php"
# (id, query, expected info-box message) -- messages verified verbatim against
# pfblockerng_threats.php (is_ipaddr / is_port guards + the no-param else).
THREATS_REJECTS: tuple[tuple[str, str, str], ...] = (
    ("invalid_host", "host=not-an-ip", "Invalid IP Address, cannot proceed!"),
    ("invalid_port", "port=99999", "Invalid Port cannot proceed!"),
    ("no_request", "", "No Requests found, cannot proceed!"),
)
# The lookup-page chrome titles ("Threat <title> Lookup") that MUST be absent on a
# reject (the handler exit()s before rendering $pgtitle).
_THREATS_LOOKUP_TITLES = ("Threat Domain Lookup", "Threat Source IP Lookup", "Threat Port Lookup")


@pytest.mark.parametrize(("name", "query", "message"), THREATS_REJECTS, ids=[r[0] for r in THREATS_REJECTS])
def test_threats_rejects_malformed_lookup(name: str, query: str, message: str, webui: WebUI) -> None:
    """A malformed/absent threats lookup renders its info-box, NOT the lookup page.

    HTTP 200 (head.inc is included before the dispatch, so the page still renders
    its header) with the exact info-box message present and the "Threat ... Lookup"
    chrome absent -- proving the validator rejected and exit()ed rather than
    rendering the lookup view. The before-state (a valid param DOES render that
    chrome) is the positive threats_{domain,host,port} entries in PAGE_TABLE.
    """
    path = f"{THREATS_PAGE}?{query}" if query else THREATS_PAGE
    resp = webui.get(path)
    assert resp.status_code == 200, f"{name}: GET {path} -> HTTP {resp.status_code} (expected 200)"
    body = resp.text
    assert message in body, f"{name}: expected info-box {message!r} not present in {path} body"
    present = [title for title in _THREATS_LOOKUP_TITLES if title in body]
    assert not present, f"{name}: reject path unexpectedly rendered lookup chrome {present}"


# ADR-19: the "Software" page + tab are PROVENANCE-GATED — present ONLY on a build installed
# from one of OUR repos (pkg %R == pfblockerng / pfblockerng-nightly). The ADR-04 UI harness
# sideloads the branch .pkg with `pkg add -f` (offline), so its %R is empty -> the auto-detect
# HIDES the page and tab (the DEFAULT negative state, proven below). To exercise BOTH states
# deterministically on this same sideload deploy, pfblockerng.inc honours a HIDDEN override
# sentinel (PFB_SOFTWARE_PANEL_OVERRIDE, a file containing 'on'|'off'); software_panel_forced()
# drops/clears it over SSH so we can render the page ENABLED (positive: 200 + the
# 'pfb-software-panel' marker) and DISABLED (negative) without needing an our-repo install. The
# REAL %R-driven behaviour is separately validated by the `repo` flow (test_software_update.py).
_SOFTWARE_PAGE = "/pfblockerng/pfblockerng_software.php"
_SOFTWARE_PANEL_MARKER = "pfb-software-panel"
_SOFTWARE_TAB_HREF = "/pfblockerng/pfblockerng_software.php"
# Mirrors PFB_SOFTWARE_PANEL_OVERRIDE in pfblockerng.inc (the hidden test/support sentinel).
_SOFTWARE_OVERRIDE_NAME = ".pfb_software_panel"
_SOFTWARE_OVERRIDE_FILE = f"{helpers.PFB_DBDIR}/{_SOFTWARE_OVERRIDE_NAME}"


@contextmanager
def software_panel_forced(vm: SmokeVM, state: str) -> Iterator[None]:
    """Force the Software-page gate ``on``/``off`` for the block via the hidden sentinel, then
    remove it so subsequent tests see the default auto-detect. ``state`` is a fixed 'on'/'off'
    literal (never user input).

    The write goes through ``helpers.write_local_feed`` (bare ``mkdir -p`` argv + ``tee`` over
    stdin), NOT ``ssh "/bin/sh -c 'mkdir … && printf … > file'"``: ssh space-joins the remote
    argv and the pfSense root LOGIN shell (tcsh) re-parses it, so the compound ``sh -c`` form
    silently mis-runs (``mkdir`` gets no operand). ``write_local_feed`` already raises on a
    failed write, so a silent failure can't let the forced-off case pass on the default-hidden
    path; the cleanup ``rm`` is checked too so a failure can't leak override state into a later
    test."""
    helpers.write_local_feed(vm, _SOFTWARE_OVERRIDE_NAME, state)
    try:
        yield
    finally:
        clear = vm.ssh("/bin/rm", "-f", _SOFTWARE_OVERRIDE_FILE)
        assert clear.returncode == 0, f"failed to clear software override sentinel: {clear.stderr.strip()}"


def test_software_page_provenance_gate_hides_on_nonour_build(
    webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """The Software page's provenance guard hides it on a non-our-repo install.

    Scenario: pfBlockerNG installed via `pkg add -f` (the UI harness), so the
    installed package's repo (`pkg query %R`) is NOT one of our repos.
      Given the standard Tier-A deploy (offline `pkg add -f`),
      When the Software page is GET (redirects NOT followed),
      Then the top-of-file provenance guard redirects to /index.php (a 3xx, not a
           200 panel body), the page-specific 'pfb-software-panel' marker is absent
           from the body, AND no new php_error.log line is produced (the guard is a
           clean redirect+exit, NOT a fatal). The enrolled php_error_log_guard pins
           the no-new-error-line condition over the sweep.
    """
    # Do NOT follow the redirect: assert the guard's 3xx -> /index.php directly, so a
    # broken guard that 200-renders the panel can't pass by following to a clean page.
    resp = webui.get(_SOFTWARE_PAGE, allow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308), (
        f"Software page expected a provenance-guard redirect, got HTTP {resp.status_code}"
    )
    location = resp.headers.get("Location", "")
    assert location.endswith("/index.php"), f"provenance guard should redirect to /index.php, got Location={location!r}"
    assert _SOFTWARE_PANEL_MARKER not in resp.text, (
        "provenance guard must NOT render the Software panel on a non-our-build"
    )


def test_software_tab_absent_on_nonour_build(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The 'Software' tab is absent from a normal pfBlockerNG page on a non-our-build.

    Given the same offline `pkg add -f` deploy (non-our-repo provenance),
    When the General page is GET,
    Then pfb_software_add_tab() appended nothing: the Software tab href is NOT in the
         tab bar. Pairs with the page-gate test above to prove BOTH gated surfaces
         (page + tab) are hidden. The positive (tab PRESENT) state is Phase 5's
         repo-install journey. php_error_log_guard enrolls this GET in the sweep.
    """
    resp = webui.get(_GENERAL_PAGE)
    result = evaluate_render(_GENERAL_PAGE, resp.status_code, resp.text, ("General Settings",))
    assert result.ok, f"General page render oracle failed: {result.detail}"
    assert _SOFTWARE_TAB_HREF not in resp.text, (
        "the Software tab must be ABSENT on a non-our-build (provenance gate hides it everywhere)"
    )


def test_software_page_renders_when_override_forces_on(
    smoke_vm: SmokeVM, webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """Forcing the hidden override 'on' renders the Software page POSITIVELY on this sideload deploy.

    Scenario: the Tier-A deploy is a sideload (%R empty) — the page is hidden by default (the
    provenance tests above). Forcing the override 'on' is the ONLY change.
      Given the override sentinel set to 'on',
      When the Software page is GET,
      Then it renders clean (200, no Fatal/Warning/Notice/Uncaught, the 'pfb-software-panel'
           marker present) AND the Software tab now appears on a normal page — proving the gate's
           POSITIVE branch on the same deploy that otherwise hides it (before/after the flip).
      And no new php_error.log line (php_error_log_guard sweeps).
    """
    with software_panel_forced(smoke_vm, "on"):
        resp = webui.get(_SOFTWARE_PAGE)
        result = evaluate_render(_SOFTWARE_PAGE, resp.status_code, resp.text, (_SOFTWARE_PANEL_MARKER,))
        assert result.ok, f"forced-on Software page render failed: {result.detail}"
        # The tab is injected everywhere on an enabled build — the positive of the tab-absent test.
        general = webui.get(_GENERAL_PAGE)
        assert _SOFTWARE_TAB_HREF in general.text, "the Software tab must be PRESENT when the gate is forced on"


def test_software_actions_link_to_package_manager(
    smoke_vm: SmokeVM, webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """Update/Uninstall are LINKS to pfSense's base-system Package Manager (issue #684).

    The Software page no longer self-hosts the pkg operation (no detached daemon, no ``?ajax=tail``
    live tail). The Update and Uninstall controls are anchors to ``pkg_mgr_install.php`` — the
    base-system page that runs pkg and shows its own progress from a page that SURVIVES pfBlockerNG's
    own removal/upgrade.

    Scenario:
      Given the override sentinel set to 'on' (so the provenance gate passes),
      When the Software page is GET,
      Then the Uninstall control is an ``<a>`` whose href links directly to the Package Manager
          delete flow (``pkg_mgr_install.php?mode=delete&pkg=…``) — #697 removed the ?do=uninstall
          intent-marker detour, since a delete always tears pfBlockerNG down;
      And the Update control's href GATES on update-availability (CodeRabbit #685): with no cached
          newer version it is inert (``href="#"``, disabled), and with a newer version cached it is an
          actionable ``pkg_mgr_install.php?mode=reinstallpkg&pkg=…`` link — the href, not just CSS,
          is the gate (an anchor's ``disabled``/``aria-disabled`` are advisory only);
      And the page carries NO in-page pkg machinery — no ``?ajax=tail`` poller, no ``pfb_output``
          textarea, no old ``pkg_mgr_installed.php`` redirect;
      And the clean render oracle (200, no Fatal/Warning/Notice, marker present) holds.

    Fail-before / pass-after: the pre-#684 page ran ``pkg`` from a detached daemon and tailed it via
    ``?ajax=tail`` into a ``pfb_output`` textarea — so the ``pkg_mgr_install.php`` hrefs were absent
    and ``?ajax=tail`` / ``pfb_output`` were present, inverting the assertions below.
    """
    software_cache = "/var/db/pfblockerng/software_update.json"

    def _update_anchor(body: str) -> str:
        tag = re.search(r'<a\b[^>]*id=["\']pfb_sw_update["\'][^>]*>', body)
        assert tag is not None, f"Update control is not an <a> link in {_SOFTWARE_PAGE} body"
        return tag.group(0)

    def _has_pkgmgr_href(tag: str, mode: str) -> bool:
        # `&` may render HTML-escaped to `&amp;`; the pkg is our pfSense-pkg-pfBlockerNG*.
        pat = rf'href=["\']/pkg_mgr_install\.php\?mode={mode}&(?:amp;)?pkg=pfSense-pkg-pfBlockerNG'
        return bool(re.search(pat, tag))

    with software_panel_forced(smoke_vm, "on"):
        # (A) No cached 'latest' → no update available → the Update href is inert ('#'), NOT an
        #     actionable reinstall link (CodeRabbit #685: the href itself must gate, not just CSS).
        smoke_vm.ssh("/bin/rm", "-f", software_cache)
        resp = webui.get(_SOFTWARE_PAGE)
        result = evaluate_render(_SOFTWARE_PAGE, resp.status_code, resp.text, (_SOFTWARE_PANEL_MARKER,))
        assert result.ok, f"Software page render oracle failed: {result.detail}"
        body = resp.text

        up_tag = _update_anchor(body)
        assert not _has_pkgmgr_href(up_tag, "reinstallpkg"), (
            f"Update must NOT be an actionable reinstall link when no update is available, got: {up_tag!r}"
        )
        assert re.search(r'href=["\']#["\']', up_tag), f"Update href must be inert ('#') when no update: {up_tag!r}"

        # Uninstall is ALWAYS actionable (removal does not gate on availability) and links DIRECTLY
        # to pfSense's Package Manager delete flow. #697 removed the ?do=uninstall intent-marker
        # detour: a delete always tears pfBlockerNG down, so no marker is needed.
        un_tag = re.search(r'<a\b[^>]*id=["\']pfb_sw_uninstall["\'][^>]*>', body)
        assert un_tag is not None, f"Uninstall control is not an <a> link in {_SOFTWARE_PAGE} body"
        assert _has_pkgmgr_href(un_tag.group(0), "delete"), (
            f"Uninstall link must target pkg_mgr_install.php?mode=delete, got: {un_tag.group(0)!r}"
        )
        assert "?do=uninstall" not in un_tag.group(0), (
            "Uninstall must NOT route through the removed ?do=uninstall handler (#697)"
        )

        # The in-page pkg machinery is gone entirely.
        assert "?ajax=tail" not in body, "Software page must no longer host the ?ajax=tail poller"
        assert 'name="pfb_output"' not in body, "Software page must no longer render the pfb_output textarea"
        assert "/pkg_mgr_installed.php" not in body, "the old post-uninstall redirect target must be gone"

        # (B) Seed a newer cached 'latest' → update available → the Update href becomes the actionable
        #     reinstallpkg link (the ON branch of the availability gate). 99.0.0 > any real installed
        #     version, so pfb_update_available() is TRUE regardless of the branch build.
        try:
            smoke_vm.ssh("/bin/rm", "-f", software_cache)
            _seed_vm_file(smoke_vm, software_cache, '{"latest": "99.0.0", "last_checked": 1}')
            up_tag2 = _update_anchor(webui.get(_SOFTWARE_PAGE).text)
            assert _has_pkgmgr_href(up_tag2, "reinstallpkg"), (
                f"Update link must target pkg_mgr_install.php?mode=reinstallpkg when an update exists: {up_tag2!r}"
            )
        finally:
            smoke_vm.ssh("/bin/rm", "-f", software_cache)


def _pfb_output_value(body: str) -> str:
    """Return the rendered value (text between the tags) of the ``pfb_output`` textarea."""
    match = re.search(r'<textarea\b[^>]*name="pfb_output"[^>]*>(.*?)</textarea>', body, re.DOTALL)
    assert match is not None, "pfb_output textarea not found in body"
    return match.group(1)


def test_log_output_never_prefilled(smoke_vm: SmokeVM, webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:
    """The Update page never prefills the output textarea on a GET (#671 — live log AJAX-polled).

    Scenario (no prefill):
      Given the pfBlockerNG log seeded with a unique marker,
      When the Update page is GET -> pfb_output EMPTY.

    The live log is streamed by the client poller (``?ajax=tail``), so the rendered box is always
    empty; the #666 post-upgrade prefill is removed. The seeded marker makes the empty assertion
    meaningful (empty by choice, not an empty log). (The Software page no longer has an output
    textarea at all — its Update/Uninstall now link to pfSense's Package Manager, issue #684.)
    """
    upd_marker = f"pfb-upd-prefill-{uuid.uuid4().hex[:8]}"
    _seed_vm_file(smoke_vm, _PFB_LOG, upd_marker + "\n")

    # Update page → no prefill (clean render, and the seeded log marker must be absent).
    resp = webui.get(_UPDATE_PAGE)
    result = evaluate_render(_UPDATE_PAGE, resp.status_code, resp.text, ("Update Settings", "Schedule"))
    assert result.ok, f"Update page render oracle failed: {result.detail}"
    assert upd_marker not in _pfb_output_value(resp.text), "Update page must not prefill pfb_output"


def test_ajax_tail_endpoint_returns_json(
    smoke_vm: SmokeVM, webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """The ``?ajax=tail`` poll endpoint returns a well-formed JSON tail payload (#671).

    The live log is served by this endpoint instead of a blocking inline-<script> stream, which
    is why the page now completes loading (foot.inc + nav menu). A GET with no offset must return
    the JSON contract the client poller consumes — parseable JSON (not an HTML page) carrying the
    data/offset/done/source keys — on BOTH pages.

    For the Update source the per-run log is seeded, so the payload tails it: source 'run' with the
    marker present. fail-before: there was no such endpoint, so the request rendered the full HTML
    page and ``json.loads`` would raise. (The Software page no longer has an ``?ajax=tail`` endpoint
    — its Update/Uninstall link to pfSense's Package Manager, issue #684.)
    """
    run_marker = f"pfb-tail-{uuid.uuid4().hex[:8]}"
    _seed_vm_file(smoke_vm, _PFB_RUNLOG, run_marker + "\n")

    resp = webui.get(f"{_UPDATE_PAGE}?ajax=tail")
    assert resp.status_code == 200, f"ajax=tail status {resp.status_code}"
    payload = json.loads(resp.text)  # must parse as JSON, not HTML
    for key in ("data", "offset", "done", "source"):
        assert key in payload, f"update ajax=tail payload missing {key!r}: {payload}"
    assert payload["source"] == "run", f"seeded run log should be tailed (source 'run'): {payload}"
    assert run_marker in payload["data"], f"seeded run-log marker missing from tail data: {payload}"


def test_software_page_hidden_when_override_forces_off(
    smoke_vm: SmokeVM, webui: WebUI, php_error_log_guard: PhpErrorLogGuard
) -> None:
    """Forcing the override 'off' hides the page DETERMINISTICALLY — independent of install %R.

    The 'off' branch must win even on a box that WOULD auto-detect as our-build, so support can
    force the page away. GET (redirects not followed) -> the guard's 3xx to /index.php, marker
    absent — the explicit negative branch paired with the forced-on positive above.
    """
    with software_panel_forced(smoke_vm, "off"):
        resp = webui.get(_SOFTWARE_PAGE, allow_redirects=False)
        assert resp.status_code in (301, 302, 303, 307, 308), (
            f"forced-off Software page expected a redirect, got HTTP {resp.status_code}"
        )
        assert resp.headers.get("Location", "").endswith("/index.php")
        assert _SOFTWARE_PANEL_MARKER not in resp.text, "forced-off must NOT render the Software panel"


def test_log_settings_section_redesign_render(webui: WebUI, php_error_log_guard: PhpErrorLogGuard) -> None:  # noqa: ARG001
    """The Log Settings section was regrouped into aligned per-log rows with a single 3-item
    column-help intro and category header rows (issue #489).

    Scenario: Log Settings section redesigned — grouped by category, aligned columns.
      Background: pfBlockerNG deployed; General page renders cleanly.

    Given the General page renders via the clean-render oracle (200, no Fatal/Warning/Notice,
      "General Settings" section marker present),

    When the body is inspected for the new grouped-column structure,

    Then the three column-header texts are present in the body, emitted by the per-category
      header ``Form_Group`` rows (PRESENT: new design);
    And the 3-item intro wording markers are present (the column-purpose ``<ul>`` sentences
      written in issue #489's intro ``Form_StaticText``);
    And a representative set of field names spanning all four categories are present —
      proving no control was dropped by the redesign;
    And the old repeated per-field help suffix ("</strong> Log", the pattern emitted by
      ``setHelp("Default: <strong>20000<br />{$descr}</strong> Log")`` on every row) is
      ABSENT — the repetition was removed (ABSENT: old design, before/after evidence);
    And the old "Unified Log" label is ABSENT — the trailing " Log" was dropped to "Unified"
      (ABSENT: old design, before/after evidence). ``php_error_log_guard`` enrolls this GET
      in the module-level no-growth sweep.

    Source-inspection proof of fail-before/pass-after:
    - PRESENT markers ("rolling cap", "discards that period", "cushion for remote log
      shippers", ">Max lines<", ">Schedule<", ">Keep lines<") exist ONLY in the new
      PHP code (the intro ``Form_StaticText`` and header ``Form_Group`` rows); they are
      absent from ``origin/devel``, so the test FAILS on the old code and PASSES after.
    - ABSENT markers ("</strong> Log", "Unified Log") exist ONLY in the old
      ``setHelp("Default: <strong>20000<br />{$descr}</strong> Log")`` calls and the old
      ``'Unified Log'`` key; they are absent from the new code, so the test PASSES after
      the change and would FAIL if the old code were reinstated.
    """
    resp = webui.get(_GENERAL_PAGE)
    result = evaluate_render(_GENERAL_PAGE, resp.status_code, resp.text, ("General Settings",))
    assert result.ok, f"General page render oracle failed: {result.detail}"
    body = resp.text

    # PRESENT: new 3-item intro wording (emitted by the intro Form_StaticText).
    for needle in (
        "rolling cap",
        "discards that period",
        "cushion for remote log shippers",
    ):
        assert needle in body, f"Log Settings intro wording {needle!r} missing — redesign intro not rendered"

    # PRESENT: column headers (emitted by the per-category header Form_Group rows).
    for needle in (">Max lines<", ">Schedule<", ">Keep lines<"):
        assert needle in body, f"Log Settings column header {needle!r} missing — header rows not rendered"

    # PRESENT: field names spanning all four categories — no control dropped.
    for field_name in (
        'name="log_max_log"',  # General: pfBlockerNG
        'name="log_rotate_dnslog"',  # DNSBL
        'name="log_reset_keep_unilog"',  # General: Unified
        'name="log_max_ip_blocklog"',  # IP
        'name="log_rotate_dnsreplylog"',  # DNS Reply
    ):
        assert field_name in body, f"Log Settings field {field_name!r} missing — control dropped by redesign"

    # ABSENT: old repeated per-field help suffix (was emitted by every row in the old code).
    assert "</strong> Log" not in body, (
        'old repeated per-field help suffix "</strong> Log" still present — setHelp repetition not removed'
    )

    # ABSENT: old "Unified Log" label (renamed to "Unified" in the redesign).
    assert "Unified Log" not in body, (
        '"Unified Log" label still present — label not updated to "Unified" (issue #489 rename)'
    )


def test_page_table_covers_every_pfblockerng_page() -> None:
    """Guard: the table (plus the recorded exclusions) covers the on-disk page set.

    A new pfBlockerNG .php page added to src/ without a Tier-A entry should fail
    this -- the count is asserted so the sweep can't silently skip a page. 15
    servable main pages: general, ip, dnsbl, feeds, alerts, log, sync,
    safesearch, update, blacklist, category, category_edit, threats, hooks, plus
    the pfblockerng.php template (excluded). The widget + 2 DNSBL-VIP pages round
    it out; the VIP pages + the GeoIP/Reputation views are the recorded exclusions.
    """
    covered_paths = {p.path.split("?", 1)[0] for p in PAGE_TABLE}
    # 14 distinct main .php files are render-smoked here (pfblockerng.php is the
    # excluded template), plus the widget = 15 distinct paths.
    expected_main = {
        "/pfblockerng/pfblockerng_general.php",
        "/pfblockerng/pfblockerng_ip.php",
        "/pfblockerng/pfblockerng_dnsbl.php",
        "/pfblockerng/pfblockerng_feeds.php",
        "/pfblockerng/pfblockerng_alerts.php",
        "/pfblockerng/pfblockerng_log.php",
        "/pfblockerng/pfblockerng_sync.php",
        "/pfblockerng/pfblockerng_safesearch.php",
        "/pfblockerng/pfblockerng_update.php",
        "/pfblockerng/pfblockerng_blacklist.php",
        "/pfblockerng/pfblockerng_category.php",
        "/pfblockerng/pfblockerng_category_edit.php",
        "/pfblockerng/pfblockerng_threats.php",
        "/pfblockerng/pfblockerng_hooks.php",
        "/widgets/widgets/pfblockerng.widget.php",
    }
    missing = expected_main - covered_paths
    assert not missing, f"Tier-A page table is missing pages: {sorted(missing)}"
    # The two non-hermetic classes are recorded, not dropped.
    excluded_names = {e.name for e in EXCLUDED_FROM_TIER_A}
    assert "geoip_continent_views" in excluded_names
    assert "dnsbl_vip_sinkhole_pages" in excluded_names


# ---------------------------------------------------------------------------
# Tier-B tests — ui_e2e marker; schedule/dispatch-only, NOT PR-blocking.
# These require VM state setup (seeding files or multi-step POST → GET flows).
# ---------------------------------------------------------------------------

_PFB_LOG = "/var/log/pfblockerng/pfblockerng.log"
_PFB_RUNLOG = "/var/log/pfblockerng/pfblockerng_run.log"


def _seed_vm_file(vm: SmokeVM, path: str, content: str, *, timeout: float = 30.0) -> None:
    """Append *content* to *path* on the guest via ``tee -a``.

    Uses ``subprocess.run`` directly so ``input=`` can carry the data (the
    ``SmokeVM.ssh()`` helper captures stdout/stderr only, no stdin pipe).
    The parent directory must already exist (``/var/log/pfblockerng/`` is
    created by pfBlockerNG on install — always present after ``pkg add``).
    """
    result = subprocess.run(
        vm.ssh_argv("tee", "-a", path),
        input=content,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"_seed_vm_file({path!r}) failed: rc={result.returncode} {result.stderr!r}")


_PENDING_MARKER = "/usr/local/etc/pfb_pending_changes"
_PENDING_NEEDLE = "Pending changes will be applied on the next list update"


def test_pending_changes_banner_tracks_the_marker(
    smoke_vm: SmokeVM,
    webui: WebUI,
    php_error_log_guard: PhpErrorLogGuard,  # noqa: ARG001
) -> None:
    """The "pending changes" banner shows on a settings page iff there are unapplied
    settings changes, and disappears once an Update has applied them.

    A save on a deferred page (DNSBL/IP/Feeds) writes config but only the next Update
    applies it, so the GUI flags the wait with a banner linking to the Update page. The
    flag is the persisted marker file at ``/usr/local/etc/pfb_pending_changes``.

    Scenario:
      Given no marker (no pending changes), the DNSBL page renders WITHOUT the banner;
      When the marker is present (settings changed, no Update run yet),
      Then the DNSBL page renders WITH the banner + its "go to the Update tab" link.
    Driving the marker file directly stands in for the save (which sets it) and the
    Update (which clears it) — a genuine before/after, not a one-sided assertion.
    """
    path = "/pfblockerng/pfblockerng_dnsbl.php"
    try:
        # Given a clean state — banner ABSENT, page still renders cleanly.
        smoke_vm.ssh("rm", "-f", _PENDING_MARKER)
        resp = webui.get(path)
        result = evaluate_render(path, resp.status_code, resp.text, ("DNSBL Configuration",))
        assert result.ok, f"DNSBL render oracle failed (clean state): {result.detail}"
        assert _PENDING_NEEDLE not in resp.text, "pending-changes banner must be ABSENT when there is no marker file"

        # When settings have changed but no Update has run — banner SHOWS, with its link.
        smoke_vm.ssh("touch", _PENDING_MARKER)
        resp2 = webui.get(path)
        result2 = evaluate_render(path, resp2.status_code, resp2.text, ("DNSBL Configuration",))
        assert result2.ok, f"DNSBL render oracle failed (pending state): {result2.detail}"
        assert _PENDING_NEEDLE in resp2.text, "pending-changes banner must SHOW when the marker file exists"
        assert "To run an update now, go to the" in resp2.text, (
            "pending-changes banner must carry the Update-page call to action"
        )

        # On the Update page itself ($on_update_page=TRUE) the banner SHOWS but drops the
        # redundant self-link — exercising the other branch of pfb_print_pending_changes_box().
        update_path = "/pfblockerng/pfblockerng_update.php"
        resp3 = webui.get(update_path)
        result3 = evaluate_render(update_path, resp3.status_code, resp3.text, ("Update Settings",))
        assert result3.ok, f"Update render oracle failed (pending state): {result3.detail}"
        assert _PENDING_NEEDLE in resp3.text, "banner must SHOW on the Update page too when pending"
        assert "To run an update now, go to the" not in resp3.text, (
            "on the Update page the banner must NOT carry the go-to-Update self-link"
        )
    finally:
        smoke_vm.ssh("rm", "-f", _PENDING_MARKER)
